### ISSUE TITLE
PHP Fatal error: Unsupported operand types

### ISSUE THREAD

**Issue by garyprosser** [turnitin/moodle-plagiarism_turnitin#10]
we upgrade from moodle 2.8 to 2.9.2 - carried out by removing all moodle files and replacing with new
we got report that turnitin plugins (x2) were missing from disk
uploaded plagiarism_turnitin_moodle29_2015040107.zip and mod_turnitintooltwo_moodle29_2015040107.zip
no errors reported
checking updates for plugins got report that newer versions were available
then uploaded plagiarism_turnitin_moodle29_2015040110.zip and mod_turnitintooltwo_moodle29_2015040110
no errors reported
on editing settings for an existing assignment and on attempting to create a new assignment I got blank pages and in server php error log:
PHP Fatal error: Unsupported operand types in /srv/[our-domain]/public/htdocs/plagiarism/turnitin/turnitinplugin_view.class.php on line 119
that line has
// Merge the arrays, prioitising instructor owned arrays.
$rubrics = $rubrics + $turnitinclass->sharedrubrics;

**Comment by jmcgettrick** [comment]
Hi @garyprosser, I can reproduce this but only if I change accounts. Are you using the same Turnitin account? 

There's a call to read the class from Turnitin which returns the shared rubrics on the account. If the class can't be read then $turnitinclass->sharedrubrics isn't initialised which is causing the error. When I've reproduced it, the call to read class will fail as that class belongs to a different account.

**Comment by garyprosser** [comment]
Hi John

Thanks for your prompt response.

The Turnitin setup wasn't changed during, or after, the upgrading process.

However, I can add a little more information on this issue...

I tested several assignments (which pre-existed the upgrade). Of these 3 
were 'standard', 1 was 'turnitin'. I mean that the 'standard' have url's 
like this

/mod/assign/view.php?id=22

the 'turnitin' one like this

/mod/turnitintooltwo/view.php?id=17

I have no problem with editing settings of the 'turnitin' assignment, 
but get the reported error trying to edit settings of the 'standard' 
assignments.

Gary

On 22/10/15 09:39, John McGettrick wrote:
>
> Hi @garyprosser <https://github.com/garyprosser>, I can reproduce this 
> but only if I change accounts. Are you using the same Turnitin account?
>
> There's a call to read the class from Turnitin which returns the 
> shared rubrics on the account. If the class can't be read then 
> $turnitinclass->sharedrubrics isn't initialised which is causing the 
> error. When I've reproduced it, the call to read class will fail as 
> that class belongs to a different account.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/turnitin/moodle-plagiarism_turnitin/issues/10#issuecomment-150149023>.
>
> -- 
> This email was Virus checked by UTM 9. http://www.sophos.com

-- 
Gary Prosser
IT Manager
Trinity College Bristol

T: +44 (0) 117 968 2803

W: trinitycollegebristol.ac.uk
F: facebook.com/trinitycollegebristol
T: twitter.com/trinity_bristol

**Comment by jmcgettrick** [comment]
Out of interest, can you reproduce the error and check the API logs (you''ll need to enable diagnostic mode in the Turnitin Assignment 2 plugin first) to see if there is an error when reading course section?

We'll get this fixed anyway, it'll just be a case of initialising sharedrubrics as an array when creating the $turnitinclass object.

**Comment by garyprosser** [comment]
John

a question - from a purely PHP angle any variable (likely to be) 
subsequently called elsewhere should always be initialised ? eg

$turnitinclass->sharedrubrics = array();

Gary

On 22/10/15 09:39, John McGettrick wrote:
>
> Hi @garyprosser <https://github.com/garyprosser>, I can reproduce this 
> but only if I change accounts. Are you using the same Turnitin account?
>
> There's a call to read the class from Turnitin which returns the 
> shared rubrics on the account. If the class can't be read then 
> $turnitinclass->sharedrubrics isn't initialised which is causing the 
> error. When I've reproduced it, the call to read class will fail as 
> that class belongs to a different account.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/turnitin/moodle-plagiarism_turnitin/issues/10#issuecomment-150149023>.
>
> -- 
> This email was Virus checked by UTM 9. http://www.sophos.com

-- 
Gary Prosser
IT Manager
Trinity College Bristol

T: +44 (0) 117 968 2803

W: trinitycollegebristol.ac.uk
F: facebook.com/trinitycollegebristol
T: twitter.com/trinity_bristol

**Comment by garyprosser** [comment]
Oops, sorry about my 14.51 email, just seen this reply of your making 
the same point !

I'll check the API logs and report back.
G

On 22/10/15 12:21, John McGettrick wrote:
>
> Out of interest, can you reproduce the error and check the API logs 
> (you''ll need to enable diagnostic mode in the Turnitin Assignment 2 
> plugin first) to see if there is an error when reading course section?
>
> We'll get this fixed anyway, it'll just be a case of initialising 
> sharedrubrics as an array when creating the $turnitinclass object.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/turnitin/moodle-plagiarism_turnitin/issues/10#issuecomment-150184698>.
>
> -- 
> This email was Virus checked by UTM 9. http://www.sophos.com

-- 
Gary Prosser
IT Manager
Trinity College Bristol

T: +44 (0) 117 968 2803

W: trinitycollegebristol.ac.uk
F: facebook.com/trinitycollegebristol
T: twitter.com/trinity_bristol

**Comment by jmcgettrick** [comment]
No problem @garyprosser, it is initialised as an array() it's just that it's during the try/catch that fails.

**Comment by garyprosser** [comment]
John

I turned on diagnostic mode in Turnitin

admin/settings.php?section=modsettingturnitintooltwo

then went to edit settings in

course/view.php?id=2# (this a 'standard' assignment activity)

got the blank page

then went to

plagiarism/turnitin/settings.php?do=errors

- no results found

I'm attaching the download from 'Save Data Dump'

I also went to

admin/settings.php?section=modsettingturnitintooltwo

and got the 'Save Data Dump' - also attached

Gary

On 22/10/2015 12:21, John McGettrick wrote:
>
> Out of interest, can you reproduce the error and check the API logs 
> (you''ll need to enable diagnostic mode in the Turnitin Assignment 2 
> plugin first) to see if there is an error when reading course section?
>
> We'll get this fixed anyway, it'll just be a case of initialising 
> sharedrubrics as an array when creating the $turnitinclass object.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/turnitin/moodle-plagiarism_turnitin/issues/10#issuecomment-150184698>.
>
> -- 
> This email was Virus checked by UTM 9. http://www.sophos.com

-- 

Gary Prosser
IT Manager
Trinity College Bristol

T: +44 (0) 117 968 2803 D: +44 (0) 117 968 0217

W: trinitycollegebristol.ac.uk
F: facebook.com/trinitycollegebristol
T: twitter.com/trinity_bristol

====== Turnitin Plagiarism Plugin Data Dump File ======

== plagiarism_turnitin_config ==

=========================================================================================================================================
| id                              | cm                              | name                            | value                           |
=========================================================================================================================================
| 183                             | 0                               | use_turnitin                    | 0                               |
| 184                             | 0                               | use_turnitin_lock               | 0                               |
| 185                             | 0                               | plagiarism_show_student_report  | 0                               |
| 186                             | 0                               | plagiarism_show_student_report_l| 0                               |
| 187                             | 0                               | plagiarism_draft_submit         | 0                               |
| 188                             | 0                               | plagiarism_draft_submit_lock    | 0                               |
| 189                             | 0                               | plagiarism_allow_non_or_submissi| 0                               |
| 190                             | 0                               | plagiarism_allow_non_or_submissi| 0                               |
| 191                             | 0                               | plagiarism_submitpapersto       | 0                               |
| 192                             | 0                               | plagiarism_submitpapersto_lock  | 0                               |
| 193                             | 0                               | plagiarism_compare_student_paper| 0                               |
| 194                             | 0                               | plagiarism_compare_student_paper| 0                               |
| 195                             | 0                               | plagiarism_compare_internet     | 0                               |
| 196                             | 0                               | plagiarism_compare_internet_lock| 0                               |
| 197                             | 0                               | plagiarism_compare_journals     | 0                               |
| 198                             | 0                               | plagiarism_compare_journals_lock| 0                               |
| 199                             | 0                               | plagiarism_report_gen           | 0                               |
| 200                             | 0                               | plagiarism_report_gen_lock      | 0                               |
| 201                             | 0                               | plagiarism_compare_institution  |                                 |
| 202                             | 0                               | plagiarism_compare_institution_l|                                 |
| 203                             | 0                               | plagiarism_exclude_biblio       | 0                               |
| 204                             | 0                               | plagiarism_exclude_biblio_lock  | 0                               |
| 205                             | 0                               | plagiarism_exclude_quoted       | 0                               |
| 206                             | 0                               | plagiarism_exclude_quoted_lock  | 0                               |
| 207                             | 0                               | plagiarism_exclude_matches      | 0                               |
| 208                             | 0                               | plagiarism_exclude_matches_lock | 0                               |
| 209                             | 0                               | plagiarism_exclude_matches_value|                                 |
| 210                             | 0                               | plagiarism_exclude_matches_value|                                 |
| 211                             | 0                               | plagiarism_rubric               |                                 |
| 212                             | 0                               | plagiarism_rubric_lock          |                                 |
| 213                             | 0                               | plagiarism_erater               |                                 |
| 214                             | 0                               | plagiarism_erater_lock          |                                 |
| 215                             | 0                               | plagiarism_erater_handbook      |                                 |
| 216                             | 0                               | plagiarism_erater_handbook_lock |                                 |
| 217                             | 0                               | plagiarism_erater_dictionary    |                                 |
| 218                             | 0                               | plagiarism_erater_dictionary_loc|                                 |
| 219                             | 0                               | plagiarism_erater_spelling      |                                 |
| 220                             | 0                               | plagiarism_erater_spelling_lock |                                 |
| 221                             | 0                               | plagiarism_erater_grammar       |                                 |
| 222                             | 0                               | plagiarism_erater_grammar_lock  |                                 |
| 223                             | 0                               | plagiarism_erater_usage         |                                 |
| 224                             | 0                               | plagiarism_erater_usage_lock    |                                 |
| 225                             | 0                               | plagiarism_erater_mechanics     |                                 |
| 226                             | 0                               | plagiarism_erater_mechanics_lock|                                 |
| 227                             | 0                               | plagiarism_erater_style         |                                 |
| 228                             | 0                               | plagiarism_erater_style_lock    |                                 |
| 229                             | 0                               | plagiarism_anonymity            | 0                               |
| 230                             | 0                               | plagiarism_anonymity_lock       |                                 |
| 231                             | 0                               | plagiarism_transmatch           | 0                               |
| 232                             | 0                               | plagiarism_transmatch_lock      |                                 |
| 233                             | 0                               | plagiarism_locked_message       | This setting is locked at the si|
| 234                             | 15                              | use_turnitin                    | 1                               |
| 235                             | 15                              | plagiarism_show_student_report  | 0                               |
| 236                             | 15                              | plagiarism_draft_submit         | 0                               |
| 237                             | 15                              | plagiarism_allow_non_or_submissi| 0                               |
| 238                             | 15                              | plagiarism_submitpapersto       | 0                               |
| 239                             | 15                              | plagiarism_compare_student_paper| 0                               |
| 240                             | 15                              | plagiarism_compare_internet     | 0                               |
| 241                             | 15                              | plagiarism_compare_journals     | 0                               |
| 242                             | 15                              | plagiarism_report_gen           | 0                               |
| 243                             | 15                              | plagiarism_exclude_biblio       | 0                               |
| 244                             | 15                              | plagiarism_exclude_quoted       | 0                               |
| 245                             | 15                              | plagiarism_exclude_matches      | 0                               |
| 246                             | 15                              | plagiarism_exclude_matches_value|                                 |
| 247                             | 15                              | plagiarism_rubric               |                                 |
| 248                             | 15                              | plagiarism_anonymity            | 0                               |
| 249                             | 15                              | plagiarism_transmatch           | 0                               |
| 250                             | 15                              | turnitin_assignid               | 5094768                         |
| 251                             | 15                              | plagiarism_post_date            | 1440025200                      |
| 252                             | 16                              | use_turnitin                    | 1                               |
| 253                             | 16                              | plagiarism_show_student_report  | 0                               |
| 254                             | 16                              | plagiarism_draft_submit         | 0                               |
| 255                             | 16                              | plagiarism_allow_non_or_submissi| 0                               |
| 256                             | 16                              | plagiarism_submitpapersto       | 1                               |
| 257                             | 16                              | plagiarism_compare_student_paper| 0                               |
| 258                             | 16                              | plagiarism_compare_internet     | 0                               |
| 259                             | 16                              | plagiarism_compare_journals     | 0                               |
| 260                             | 16                              | plagiarism_report_gen           | 0                               |
| 261                             | 16                              | plagiarism_exclude_biblio       | 0                               |
| 262                             | 16                              | plagiarism_exclude_quoted       | 0                               |
| 263                             | 16                              | plagiarism_exclude_matches      | 0                               |
| 264                             | 16                              | plagiarism_exclude_matches_value|                                 |
| 265                             | 16                              | plagiarism_rubric               | 353081                          |
| 266                             | 16                              | plagiarism_anonymity            | 0                               |
| 267                             | 16                              | plagiarism_transmatch           | 0                               |
| 268                             | 18                              | use_turnitin                    | 1                               |
| 269                             | 18                              | plagiarism_show_student_report  | 0                               |
| 270                             | 18                              | plagiarism_draft_submit         | 0                               |
| 271                             | 18                              | plagiarism_allow_non_or_submissi| 0                               |
| 272                             | 18                              | plagiarism_submitpapersto       | 0                               |
| 273                             | 18                              | plagiarism_compare_student_paper| 0                               |
| 274                             | 18                              | plagiarism_compare_internet     | 0                               |
| 275                             | 18                              | plagiarism_compare_journals     | 0                               |
| 276                             | 18                              | plagiarism_report_gen           | 0                               |
| 277                             | 18                              | plagiarism_exclude_biblio       | 0                               |
| 278                             | 18                              | plagiarism_exclude_quoted       | 0                               |
| 279                             | 18                              | plagiarism_exclude_matches      | 0                               |
| 280                             | 18                              | plagiarism_exclude_matches_value|                                 |
| 281                             | 18                              | plagiarism_rubric               |                                 |
| 282                             | 18                              | plagiarism_anonymity            | 0                               |
| 283                             | 18                              | plagiarism_transmatch           | 0                               |
| 284                             | 19                              | use_turnitin                    | 1                               |
| 285                             | 19                              | plagiarism_show_student_report  | 0                               |
| 286                             | 19                              | plagiarism_draft_submit         | 0                               |
| 287                             | 19                              | plagiarism_allow_non_or_submissi| 0                               |
| 288                             | 19                              | plagiarism_submitpapersto       | 0                               |
| 289                             | 19                              | plagiarism_compare_student_paper| 0                               |
| 290                             | 19                              | plagiarism_compare_internet     | 0                               |
| 291                             | 19                              | plagiarism_compare_journals     | 0                               |
| 292                             | 19                              | plagiarism_report_gen           | 0                               |
| 293                             | 19                              | plagiarism_exclude_biblio       | 0                               |
| 294                             | 19                              | plagiarism_exclude_quoted       | 0                               |
| 295                             | 19                              | plagiarism_exclude_matches      | 0                               |
| 296                             | 19                              | plagiarism_exclude_matches_value|                                 |
| 297                             | 19                              | plagiarism_rubric               |                                 |
| 298                             | 19                              | plagiarism_anonymity            | 0                               |
| 299                             | 19                              | plagiarism_transmatch           | 0                               |
| 316                             | 21                              | use_turnitin                    | 1                               |
| 317                             | 21                              | plagiarism_show_student_report  | 0                               |
| 318                             | 21                              | plagiarism_draft_submit         | 0                               |
| 319                             | 21                              | plagiarism_allow_non_or_submissi| 0                               |
| 320                             | 21                              | plagiarism_submitpapersto       | 0                               |
| 321                             | 21                              | plagiarism_compare_student_paper| 0                               |
| 322                             | 21                              | plagiarism_compare_internet     | 0                               |
| 323                             | 21                              | plagiarism_compare_journals     | 0                               |
| 324                             | 21                              | plagiarism_report_gen           | 0                               |
| 325                             | 21                              | plagiarism_exclude_biblio       | 0                               |
| 326                             | 21                              | plagiarism_exclude_quoted       | 0                               |
| 327                             | 21                              | plagiarism_exclude_matches      | 0                               |
| 328                             | 21                              | plagiarism_exclude_matches_value|                                 |
| 329                             | 21                              | plagiarism_rubric               | 353056                          |
| 330                             | 21                              | plagiarism_anonymity            | 0                               |
| 331                             | 21                              | plagiarism_transmatch           | 0                               |
| 332                             | 22                              | use_turnitin                    | 1                               |
| 333                             | 22                              | plagiarism_show_student_report  | 0                               |
| 334                             | 22                              | plagiarism_draft_submit         | 0                               |
| 335                             | 22                              | plagiarism_allow_non_or_submissi| 0                               |
| 336                             | 22                              | plagiarism_submitpapersto       | 0                               |
| 337                             | 22                              | plagiarism_compare_student_paper| 1                               |
| 338                             | 22                              | plagiarism_compare_internet     | 1                               |
| 339                             | 22                              | plagiarism_compare_journals     | 1                               |
| 340                             | 22                              | plagiarism_report_gen           | 0                               |
| 341                             | 22                              | plagiarism_exclude_biblio       | 0                               |
| 342                             | 22                              | plagiarism_exclude_quoted       | 0                               |
| 343                             | 22                              | plagiarism_exclude_matches      | 0                               |
| 344                             | 22                              | plagiarism_exclude_matches_value|                                 |
| 345                             | 22                              | plagiarism_rubric               | 355158                          |
| 346                             | 22                              | plagiarism_anonymity            | 1                               |
| 347                             | 22                              | plagiarism_transmatch           | 0                               |
-----------------------------------------------------------------------------------------------------------------------------------------

== plagiarism_turnitin_files ==

=============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================
| id                       | cm                       | userid                   | identifier               | externalid               | externalstatus           | statuscode               | similarityscore          | attempt                  | apimd5                   | legacyteacher            | transmatch               | lastmodified             | grade                    | submissiontype           | orcapable                | errorcode                | errormsg                 | student_read             |
=============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================
| 12                       | 15                       | 14                       | db6976d74d93fc7777570213d|                          | 0                        | pending                  |                          | 2                        |                          | 0                        | 0                        | 1440152591               |                          | file                     |                          | 0                        | Turnitin has returned an |                          |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


====== Turnitintool Data Dump File ======

== turnitintooltwo_users ==

=========================================================================================================================================================================================================================
| id                       | userid                   | turnitin_uid             | turnitin_utp             | instructor_defaults      | instructor_rubrics       | user_agreement_accepted  | Name                     |
=========================================================================================================================================================================================================================
| 1                        | 5                        | 267400                   | 2                        |                          | {&quot;353056&quot;:&quot;test grading f| 1                        | Mat Ridley               |
| 2                        | 3                        | 7013503                  | 2                        |                          | {&quot;353081&quot;:&quot;Essays; writte| 0                        | Ken Farrimond            |
| 3                        | 7                        | 7026368                  | 1                        |                          |                          | 1                        | Test Student             |
| 4                        | 8                        | 7026406                  | 2                        |                          | []                       | 0                        | test staff               |
| 5                        | 2                        | 7018090                  | 2                        |                          | []                       | 0                        | Admin User               |
| 6                        | 9                        | 7026448                  | 2                        |                          |                          | 0                        | Liz Curry                |
| 7                        | 10                       | 7030002                  | 2                        |                          | {&quot;353083&quot;:&quot;test by dummy | 0                        | Dummy Tutor              |
| 8                        | 11                       | 7018098                  | 2                        |                          | []                       | 0                        | Dummy Tutor2             |
| 9                        | 12                       | 7030089                  | 2                        |                          | []                       | 0                        | Test Tutor2              |
| 10                       | 13                       | 7031049                  | 2                        |                          | []                       | 0                        | Test Tutor3              |
| 11                       | 14                       | 7032180                  | 1                        |                          |                          | 1                        | Test Student2            |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

== turnitintooltwo_courses ==

===================================================================================================================================================================
| id                       | courseid                 | ownerid                  | turnitin_ctl             | turnitin_cid             | course_type              |
===================================================================================================================================================================
| 2                        | 2                        | 8                        | First Course (Moodle PP) | 2956788                  | PP                       |
| 3                        | 2                        | 3                        | First Course (Moodle TT) | 2958193                  | TT                       |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

== turnitintooltwo ==

=======================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================
| id                  | course              | type                | name                | grade               | numparts            | defaultdtstart      | defaultdtdue        | defaultdtpost       | anon                | submitted           | portfolio           | allowlate           | reportgenspeed      | submitpapersto      | spapercheck         | internetcheck       | journalcheck        | maxfilesize         | intro               | introformat         | timecreated         | timemodified        | studentreports      | dateformat          | usegrademark        | gradedisplay        | autoupdates         | commentedittime     | commentmaxsize      | autosubmission      | shownonsubmission   | excludebiblio       | excludequoted       | excludevalue        | excludetype         | perpage             | erater              | erater_handbook     | erater_dictionary   | erater_spelling     | erater_grammar      | erater_usage        | erater_mechanics    | erater_style        | transmatch          | rubric              | allownonor          | needs_updating      |
=======================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================
| 2                   | 2                   | 0                   | test5               | 100                 | 1                   | 0                   | 0                   | 0                   | 0                   | 1                   | 0                   | 0                   | 0                   | 1                   | 1                   | 1                   | 1                   | 0                   | &lt;p&gt;test5&lt;br&gt;&lt;/p&gt;    | 1                   | 1440154086          | 1440154086          | 0                   | d/m/Y               | 1                   | 1                   | 1                   | 1800                | 800                 | 1                   | 1                   | 0                   | 0                   | 0                   | 0                   | 25                  | 0                   | 0                   |                     | 0                   | 0                   | 0                   | 0                   | 0                   | 0                   | 0                   | 0                   | 0                   |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

== turnitintooltwo_parts ==

=====================================================================================================================================================================================================================================================================================================================================
| id                       | turnitintooltwoid        | partname                 | tiiassignid              | dtstart                  | dtdue                    | dtpost                   | maxmarks                 | deleted                  | migrated                 | unanon                   | submitted                |
=====================================================================================================================================================================================================================================================================================================================================
| 2                        | 2                        | Part 1                   | 5107960                  | 1440154020               | 1440758820               | 1440758820               | 100                      | 0                        | 0                        | 0                        | 1                        |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

== turnitintooltwo_submissions ==

=========================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================
| id                       | userid                   | turnitintooltwoid        | submission_part          | submission_title         | submission_type          | submission_filename      | submission_objectid      | submission_score         | submission_grade         | submission_gmimaged      | submission_status        | submission_queued        | submission_attempts      | submission_modified      | submission_parent        | submission_nmuserid      | submission_nmfirstname   | submission_nmlastname    | submission_unanon        | submission_unanonreason  | submission_transmatch    | submission_acceptnothing | submission_orcapable     |
=========================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================
| 3                        | 14                       | 2                        | 2                        | essay                    | 1                        |                          | 46495523                 | 100                      |                          | 0                        |                          |                          | 0                        | 1440154186               | 0                        | 0                        |                          |                          | 1                        |                          | 0                        | 0                        | 1                        |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by jmcgettrick** [comment]
That fix has been released with 2015040111.
