### ISSUE TITLE
Cannot launch Turnitin QuickMark Manager or Rubric Manager from Moodle Assignment edit screen

### ISSUE THREAD

**Issue by mjr66** [turnitin/moodle-plagiarism_turnitin#101]
Hello there,

We recently updated our Moodle site to version 2.9.4+, and our Turnitin plugins to version 2016011104, and have noticed a new problem that has arisen when editing the settings for an assignment (or creating a new one).

We are using the default Moodle assignment in conjunction with the Turnitin plagiarism plugin. If we go to the edit settings screen for an assignment, we find that if we click on either the "Launch Quickmark Manager" link, or the "Launch Rubric Manager" link, neither Manager will launch. All that happens is that the web page goes dim and an animated "loading" icon appears (although sometimes we don't get the icon, just a dimmed webpage). If I click around the edges of the dimmed webpage, the screen un-dims and I am back on the assignment edit page again. If I click in the centre of the screen, nothing happens. This behaviour is reproducable in Chrome, Firefox and Internet Explorer 11.

Although we don't use it, the "Launch PeerMark Manager" link seems to work fine - if we click on that, the screen goes dim, a window pops up, and we have a "close" link in the top right corner of the screen.

**Comment by fawells** [comment]
Also have this problem with 2016011104.
Lines 102 and 103 of \plagiarism\turnitin\turnitinplugin_view.class.php changed in 04 from:
`        $PAGE->requires->string_for_js('changerubricwarning', 'turnitintooltwo');
        $PAGE->requires->string_for_js('closebutton', 'turnitintooltwo');`
to 
`        $PAGE->requires->string_for_js('changerubricwarning', 'plagiarism_turnitin');
        $PAGE->requires->string_for_js('closebutton', 'plagiarism_turnitin');`
 
JS language string is called from 1061 of \mod\turnitintooltwo\jquery\turnitintooltwo.(min.)js

Either reverting the change or changing the language string to `M.str.plagiarism_turnitin.closebutton` works

**Comment by dhattonturnitin** [comment]
Fixed in release v2016011105
