### ISSUE TITLE
Another issue affecting cron

### ISSUE THREAD

**Issue by jerryhops** [turnitin/moodle-plagiarism_turnitin#106]
Cron is sticking with the error shown in the two screen shots below:

<img width="415" alt="tii-error" src="https://cloud.githubusercontent.com/assets/16592978/13569629/0a86f74a-e461-11e5-94e7-a6a3e0b2e5c5.PNG">

<img width="605" alt="tii-error2" src="https://cloud.githubusercontent.com/assets/16592978/13569672/4d36ced0-e461-11e5-86e0-b45b6526fb4d.PNG">

**Comment by jmcgettrick** [comment]
Hi @jerryhops a database upgrade was missed when upgrading from 2016011102 to 2016011103. There needs to be a field created in plagiarism_turnitin_files called duedate_report_refresh. See: https://github.com/turnitin/moodle-plagiarism_turnitin/blob/master/db/upgrade.php#L186-L192

**Comment by jerryhops** [comment]
Thanks, would an upgrade to 2016011104 fix that?

**Comment by jmcgettrick** [comment]
Yes, that'll create the field in your database. You could just create it manually if you wish though?
