### ISSUE TITLE
Word count generated incorrectly for non-plaintext files

### ISSUE THREAD

**Issue by pauln** [turnitin/moodle-plagiarism_turnitin#111]
The word count (used to determine whether a submission contains enough content for an OR to be generated) is based on the number of space-separated chunks in the raw file content, which is only accurate in a plain text file.  In other file types (especially those which employ compression, such as MS Word's .docx files), this can give an incredibly low "word count" - I've encountered a perfectly fine .docx file which is being deemed to only contain 12 words, and therefore isn't being submitted despite actually containing around 300 words!

The offending code block can be seen at https://github.com/turnitin/moodle-plagiarism_turnitin/blob/develop/lib.php#L2517-L2521 - at that point, $textcontent contains the raw content of the file.

**Comment by pauln** [comment]
Further to this, that same block of code reveals that enabling the "Allow submission of any file type?" option within the assignment's TII settings will bypass the word count check, though it'll also mean that all files uploaded to the assignment will be sent to TII (even those that genuinely can't have an OR generated).

**Comment by jmcgettrick** [comment]
We'll take a look at removing the word count check within the plugin, the count is performed at the Turnitin end anyway so isn't really necessary.

The second point is correct as users are supposed to be able to grade anything. That means that we need to image a file for use in the Document Viewer even if there will be no Originality Report generated.

**Comment by micaherne** [comment]
There are a couple of other issues with the word count that I raised a while back in #85

**Comment by jmcgettrick** [comment]
Word count has been removed from the plugin as of 2016072601.
