### ISSUE TITLE
No message in submission list when EULA hasn't been accepted

### ISSUE THREAD

**Issue by pauln** [turnitin/moodle-plagiarism_turnitin#112]
When a student's assignment submission is not submitted to TII because the student has not accepted the TII EULA, a red icon with a cross through it is shown - but with no explanation.

This can cause confusion for some teaching staff; the lack of a "resubmit" link makes sense, but a brief note to say that the student has not accepted the EULA would help make this much clearer.

The code responsible for the lack of message in this situation can be seen at https://github.com/turnitin/moodle-plagiarism_turnitin/blob/develop/lib.php#L936-L937

**Comment by jmcgettrick** [comment]
There is a message if you hover over the X which we decided was the most feasible way to show a meaningful message here. Unfortunately there just isn't a lot of space in the box to put anything but the most basic of messages in without overly impinging on the inbox layout.

**Comment by pauln** [comment]
Ah yes - I see that an error string was recently added as title text.  Sorry, I must have missed that change, as we haven't updated the plugin since our first semester for the year began.

It'd still be much clearer if there was a brief string displayed directly with the icon, saying "EULA not accepted" or something like that, so that teaching staff can see the problem immediately; title text is not ideal as it requires the user to realise that there might be something there, and be using a device which allows for hovering over elements easily.  If sufficiently succinct error messages can be composed for all other relevant error states, it'd also be good to display those along with the icon, with the resubmit link being added where relevant.  The prominence of the resubmit link, with no obvious explanation for why it's there, seems likely to cause confusion - and in some cases, repeated attempts to resubmit the same broken file (leading to frustration with TII and time-wasting support tickets - either within the institution, or in some cases perhaps even with TII support).
