### ISSUE TITLE
Submissions not sent on EULA acceptance

### ISSUE THREAD

**Issue by pauln** [turnitin/moodle-plagiarism_turnitin#113]
When a student accepts the EULA, any of their submissions which were skipped due to non-acceptance should be submitted to TII (as long as the assignment is still accepting submissions).  This does not appear to be the case at present.

One approach would be to fire an event when the EULA is accepted (https://github.com/turnitin/moodle-plagiarism_turnitin/blob/develop/ajax.php#L196-L197), and have an event handler which re-queues any submissions by that user which were not send due to non-acceptance of the EULA.

**Comment by jmcgettrick** [comment]
We don't send previous papers as there is the quite likely scenario where the student has accepted our EULA by mistake. The plugin then submitting all of their previous submissions to Turnitin would then have a knock on effect for the student's data privacy. This aligns with our workflow in our other integrations.

Programmatically it could potentially be quite a laborious task to go through all modules for which the plugin is enabled and pick out what hasn't been submitted. 

We advise the instructor to speak to the student or vice-versa in this case as the student will have to resubmit their work within Moodle.
