### ISSUE TITLE
DB get_in_or_equal does not accept empty arrays

### ISSUE THREAD

**Issue by sk-unikent** [turnitin/moodle-plagiarism_turnitin#119]
I keep getting a "DB get_in_or_equal does not accept empty arrays" in clean_old_turnitin_submissions (events 1 API events then fail).
Line 2268, ``` list($itemidsinsql, $itemidsparams) = $DB->get_in_or_equal(array_keys($itemids));```
It seems the line above that
```
$itemids = $DB->get_records('assign_submission', array(
                                                                    'assignment' => $cm->instance,
                                                                    'userid' => $userid
                                                                    ), '', 'id');
```
Does not always return results.

**Comment by jmcgettrick** [comment]
I've never seen that before, but we'll get it changed to check that the array isn't empty.

**Comment by jmcgettrick** [comment]
This looks to be the same issue highlighted by @mhughes2k and @trevor-c in https://github.com/turnitin/moodle-plagiarism_turnitin/issues/115.
