### ISSUE TITLE
Invalid get_string() identifier: 'pp_createsubmissionerror' or component 'plagiarism_turnitin'.

### ISSUE THREAD

**Issue by sk-unikent** [turnitin/moodle-plagiarism_turnitin#120]
I think there is a missing string!
https://github.com/turnitin/moodle-plagiarism_turnitin/blob/master/lib.php#L2672
https://github.com/turnitin/moodle-plagiarism_turnitin/blob/develop/lib.php#L2681

**Comment by jmcgettrick** [comment]
This has been added back in as of 2016072601
