### ISSUE TITLE
File size / word count issues

### ISSUE THREAD

**Issue by sk-unikent** [turnitin/moodle-plagiarism_turnitin#121]
Sorry for the third issue, we've been having quite a few issues recently!

We had a student submit a 235MiB PDF full of images to a mod_assign with the plagiarism plugin enabled.
Obviously this was going to fail, but it ended up breaking the whole cron system as it ran out of memory trying to explode the raw contents of the PDF :)

This line will be meaningless for docs and pdfs surely? The contents will be meaningless to the checks below. (just a ton of "K��}FG�;t�?n�;" etc)
https://github.com/turnitin/moodle-plagiarism_turnitin/blob/develop/lib.php#L2396

This doesn't work well with big files:
https://github.com/turnitin/moodle-plagiarism_turnitin/blob/develop/lib.php#L2518

The good news is I can patch it quite easily by wrapping ``if ($errorcode !== 2) {...}`` around the explode and that if. This means it won't check word counts if the file is too big anyway.
However, I thought given that the checks mean nothing for docs and pdfs anyway a proper fix should be sought?

**Comment by sk-unikent** [comment]
Ah looks like this is a duplicate of https://github.com/turnitin/moodle-plagiarism_turnitin/issues/85 - sorry!

**Comment by jmcgettrick** [comment]
No probs @sk-unikent.
