### ISSUE TITLE
Turnitin Class Creation Error breaks Moodle Mod Assign page

### ISSUE THREAD

**Issue by mhughes2k** [turnitin/moodle-plagiarism_turnitin#122]
Admittedly this happened on a test server but it's been raised before as not good practice:
![image](https://cloud.githubusercontent.com/assets/694841/14349480/4815c5e2-fcbb-11e5-97ec-d1d9013c660b.png)

Turnitin plagiarism plugin failed to create a Turnitin class when I hit the Moodle Add Assignment in the activity picker, due to a curl error and caused a complete failure of the entire Moodle add module process.

I've said it before, but please can TII *not* break Moodle when it fails!

**Comment by mkpelletier** [comment]
This happens to us and was reported in #110 Is this not the same thing?

**Comment by jmcgettrick** [comment]
Fixed in https://github.com/turnitin/moodle-plagiarism_turnitin/issues/110
