### ISSUE TITLE
Error on Turnitin Assignment creation

### ISSUE THREAD

**Issue by hiorie** [turnitin/moodle-plagiarism_turnitin#123]
Hi All,

Got this message from Moodle upon creating a turnitin assignment.

![image](https://cloud.githubusercontent.com/assets/18344443/14377371/d99db984-fda1-11e5-95a3-10c0ed8c473b.png)

My googling found 1 moodle tracker regarding this issue (https://tracker.moodle.org/browse/CONTRIB-6028) but unresolved.

The error only happened for some courses.

Posting from John from in previous issue ("pending" result after upgrade #6) its look like the class was deleted in Turnitin.

API LOG give the following message :
turnitintooltwo/Could not update Turnitin Class data
Fault Code: unknownobject | File: [dirroot]/mod/turnitintooltwo/sdk/classsoap.class.php | Line: 48 | Message: Class CourseSection not found. | Code: 0

We using the latest Turnitin v2 2016011104. I've also lodged a ticket to turnitin today with case no #00508029

Thank you for your time and effort.

**Comment by mkpelletier** [comment]
I am also getting this error along with: 
Fault Code: unknownobject | File: /storage/www/mysats/mod/turnitintooltwo/sdk/usersoap.class.php | Line: 57 | Message: User not found. | Code: 0
2016-04-15 10:24:25 +0200 (PRINT_ERROR) - Could not update user data

Fault Code: unknownobject | File: /storage/www/mysats/mod/turnitintooltwo/sdk/usersoap.class.php | Line: 57 | Message: User not found. | Code: 0
2016-04-15 10:24:31 +0200 (API_ERROR) - There was an error trying to create the assignment in Turnitin

Fault Code: unknownobject | File: /storage/www/mysats/mod/turnitintooltwo/sdk/assignmentsoap.class.php | Line: 33 | Message: Class CourseSection not found. | Code: 0
2016-04-15 10:24:34 +0200 (API_ERROR) - Could not update user data

Fault Code: unknownobject | File: /storage/www/mysats/mod/turnitintooltwo/sdk/usersoap.class.php | Line: 57 | Message: User not found. | Code: 0
2016-04-15 10:24:34 +0200 (PRINT_ERROR) - Could not update user data

Fault Code: unknownobject | File: /storage/www/mysats/mod/turnitintooltwo/sdk/usersoap.class.php | Line: 57 | Message: User not found. | Code: 0

All this despite the users already showing in the Turnitin web interface.  Could this have anything to do with the ongoing DDOS attacks reported via twitter?

**Comment by cb526** [comment]
This issue appears to still exist in the latest release of (TII Version: 2016072601).

**Comment by cb526** [comment]
I don't know what causes this problem but here's now to fix it:

1.  Go to the TII plugin settings ([yourmoodlesite]/mod/turnitintooltwo/settings_extras.php?cmd=courses
2. Click on the "Turnitin Class Restoration" tab.
3. Search for the course where the issue occurs.
4. When the course is listed below the search area, you will find that it does not have the tick box indicating that there is no link between it and TII (see image attached).
5. An option to 'Recreate Courses' will appear. Select it.
6. When you return to your course page, you should be able to create a TII assignment.

![2016-07-29_15-12-59](https://cloud.githubusercontent.com/assets/15820803/17251328/327643f4-55a0-11e6-8524-2c807b46014b.png)

**Comment by jmcgettrick** [comment]
If you create a new Moodle course then try to create a Turnitin Assignment do you get a class creation error? Either in the browser or in the API logs?
