### ISSUE TITLE
Failed Submissions Stuck in Pending under very particular circumstances

### ISSUE THREAD

**Issue by davidmhatton** [turnitin/moodle-plagiarism_turnitin#129]
If "require students click submit button" is set to "Yes" in course settings, then any submissions that fail are not resubmitted. Any resubmission attempt results in these assignments becoming stuck in "Pending" status.

The problem lies in lib.php, within the function `event_handler`:

```
// If draft submissions are turned on then only send to Turnitin if the draft submit setting is set.
                if ($moduledata->submissiondrafts && $plagiarismsettings["plagiarism_draft_submit"] == 1 &&
                    ($eventdata->event_type == 'file_uploaded' || $eventdata->event_type == 'content_uploaded')) {
                    return true;
                }
```

**Comment by mkpelletier** [comment]
This problem is wreaking havoc with our site submissions.  This needs to be fixed as a matter of urgency.   The twitter feed for @turnitinstatus is also alive with numerous complaints that would seem to point to this bug.

**Comment by cwestgarth** [comment]
Hi @mkpelletier, 

We will be looking into it for you. We need to confirm whether the issue which we've raised above is the reason why your papers are stuck in pending. I can see that you have been in contact with our Support Team, they will be in touch once we have had a chance to look into this. 

Regards

Caroline Westgarth
Product Manager, Integrations (Turnitin)

**Comment by dwinn** [comment]
Hi @mkpelletier ,

We have released an update in our latest release v2017012501 that will prevent this from happening. It can only occur on versions prior to this.
