### ISSUE TITLE
PLAGIARISM_TURNITIN_CRON_SUBMISSIONS_LIMIT set too low

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-plagiarism_turnitin#132]
a limit of 50 items per cron cycle is really too low - for high use sites you might have several hundred submissions made within a short timeframe and they get backed up on the moodle server instead of submitting directly to Turnitin. If you have a lot of different assignments with a similar deadline on the site it can take several hours for all those files to be submitted to Turnitin - particularly for older sites that run cron every 5 or 10min

**Comment by dwinn** [comment]
This has now been changed to 100 in the latest release v2016072601.
