### ISSUE TITLE
Default settings not applied if not "locked"

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-plagiarism_turnitin#135]
The default settings in plagiarism/turnitin/settings.php?do=defaults only appear to be used if the setting is also set to "locked" when creating new assignments.

it looks like the function get_settings() is used to return the defaults but this function only returns values if the field is locked.

**Comment by danmarsden** [comment]
in get_form_elements() I think the following line is wrong:
$cmid = optional_param('update', 0, PARAM_INT);

should be replaced with:
$cmid = optional_param('update', null, PARAM_INT);

**Comment by dwinn** [comment]
Thanks Dan, we'll look into this.

**Comment by jmcgettrick** [comment]
Applied to develop in https://github.com/turnitin/moodle-plagiarism_turnitin/pull/139. Thanks @danmarsden

**Comment by danmarsden** [comment]
:+1:

**Comment by dwinn** [comment]
This has now been fixed in the latest release v2016072601.
