### ISSUE TITLE
plugin sends notifications even if notifications are turned off

### ISSUE THREAD

**Issue by mkpelletier** [turnitin/moodle-plagiarism_turnitin#138]
Turnitin Version 2: 2016011105
Plagiarism Plugin: 2016011105
Moodle 2.9.3+ (Build: 20151119)

Steps to recreate:
1. Create an assignment
2. Activate plagiarism plugin
3. Change the three notification settings to "No" in the assignment settings
4. Submit an assignment
5. Turnitin sends the Turnitin Digital Receipt

The expectation with the above settings is that no notifications should be sent.  If the submission receipt is conceptually separate from the assignment notifications, there ought to be an option to turn this off as well.

**Comment by aspark21** [comment]
Duplicate - see https://github.com/turnitin/moodle-mod_turnitintooltwo/issues/148

**Comment by mkpelletier** [comment]
Thanks Alistair,

I see that the referenced thread applies to Teacher notifications, but it was not clear if this included the user as well.  If #148 does indeed include student notifications as well, then this would be a duplicate.  Let's wait for the fix there and see if it corrects this behaviour as well.
