### ISSUE TITLE
automatically refresh scores

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-plagiarism_turnitin#14]
Is there a way for the Moodle code to regularly ask Turnitin for a list of assignments that have had their originality scores updated due to new sources not available at the time of original submission? Or can we set up some form of automated refresh on the due date of the assignment or after a certain time period since the last assignment was submitted?

eg: last file submitted was 10/5/2015 so automatically refresh all scores within the moodle assignment on the 11/5/2015 - it might also be useful to notify/email the teachers in the course if any significant deviation was found between the first score generated and the new one which would likely suggest a match against someone else in the same class?

**Comment by cwestgarth** [comment]
Hi @danmarsden, 

Thank you for raising this with us, we will investigate this further. 

Many thanks 

Caroline

**Comment by danmarsden** [comment]
Thanks Caroline - this came up in an assignment that had 2 students with a score less than 10% listed in Moodle but over 60% listed within Turnitin - looked like they had copied off each other but both files were submitted at a similar time and weren't initially picked up in the first comparison.

**Comment by cwestgarth** [comment]
No worries @danmarsden, thanks again for raising this.
We'll be in touch once we have looked into this further. 

Caroline

**Comment by mkpelletier** [comment]
This would also seem to apply to instances where a student is repeating a course and submits some work from the previous instance.  In these cases we exclude the matches to his previous assignment, but the SI in the plagiarism plugin does not update in every case.

**Comment by jmcgettrick** [comment]
This has now been released in 20160111103.
