### ISSUE TITLE
Turnitin settings reset to default retrospectively 

### ISSUE THREAD

**Issue by hitteshahuja** [turnitin/moodle-plagiarism_turnitin#143]
Hi ,
Using plugin verison 2016011105

Steps to reproduce : 
1. Create a new assignment in Moodle 
2. Do not touch turnitin settings i.e leave it as it is to default.
3. Confirm that default settings set for the plugin under "Default Settings" tab are present
![tii_plugin_default_settings](https://cloud.githubusercontent.com/assets/2855029/15298365/cc42c154-1b96-11e6-9239-86ff18928adf.png)
4. Save and Display Assignment
5. Edit Assignment 
6. tii plugin settings revert back to system default settings ( as opposed to user default set by the admin )

**Comment by dwinn** [comment]
This has now been fixed in the latest release v2016072601.
