### ISSUE TITLE
There isn't a string for $string['coursegeterror'] under plagiarism/turnitin/lang/en 

### ISSUE THREAD

**Issue by hitteshahuja** [turnitin/moodle-plagiarism_turnitin#146]
Relates to this line : https://github.com/turnitin/moodle-plagiarism_turnitin/blob/master/classes/turnitin_class.class.php#L70

**Comment by dwinn** [comment]
Hi @hitteshahuja 
Thanks for the report. We are aware that several error language strings are missing from the PP language string file. We will get this fixed. It happened when we separated the PP language strings from the Moodle Direct V2 plugin.

**Comment by dwinn** [comment]
This has now been fixed in the latest release v2016072601.
