### ISSUE TITLE
Enabling blind marking on an existing assignment breaks cron

### ISSUE THREAD

**Issue by pauln** [turnitin/moodle-plagiarism_turnitin#147]
If an assignment has no submissions, it is possible to enable blind marking within the assignment on Moodle.  However, if the assignment already exists on TII, when this mod update event gets processed, the updateLineItemRequest API call fails with the error "anonymous_marking_enabled - cannot set anonymous_marking_enabled field".

This results in the event handler reporting a failure, which leaves the event on the queue to be retried next time the event queue is processed - but of course, it fails again each time, leaving the event queue "stuck".

**Comment by jmcgettrick** [comment]
Is anonymous marking enabled on your Turnitin account? That might be preventing that being set.
