### ISSUE TITLE
Some forum posts get assigned a word count over 1000 and don't submit.

### ISSUE THREAD

**Issue by Syxton** [turnitin/moodle-plagiarism_turnitin#149]
We are seeing instances where a student will reply to a forum post, and the Turnitin word count will show a number over 1000 and the post will fail to submit.  Re-submission fails immediately.  Upon editing and reposting (not removing any words but making a small change) the word count drops to the actual number (in my case ~500 words) and then is stuck in PENDING.

**Comment by jmcgettrick** [comment]
The word count has been removed from the plugin as of 2016072601
