### ISSUE TITLE
Feature: Enable hover for notices

### ISSUE THREAD

**Issue by marcusboon** [turnitin/moodle-plagiarism_turnitin#153]
Some error messages are a bit daunting for students, coupled with the bug in issue #151 students were confused as to what was really happening and lecturer's did not have the necessary information to help the students. This is more of a cosmetic change, but it hides some of the more scary error messages inside a more innocuous hover (instead of the big red error message)

**Comment by roperto** [comment]
hi @marcusboon -- I think this issued was addressed in v2.7 already in master.
