### ISSUE TITLE
Legacy events API deprecated in Moodle 3.1

### ISSUE THREAD

**Issue by mrmark** [turnitin/moodle-plagiarism_turnitin#155]
All of the `$handlers` in `db/events.php` need to be migrated to the `$observers` for compatibility with Moodle 3.1.  When this is done, the plugin's version needs to be bumped so the old handlers are removed from the database.

**Comment by jmcgettrick** [comment]
This won't be in our next release but will definitely need to be done soon. We've found that the events currently work in 3.1 with a warning being shown if the debugging level is sufficiently high.

**Comment by mrmark** [comment]
Thanks for the reply and good to hear a fix is inbound.  The debugging is an unfortunate problem if you are running things in CI as debugging notices are counted as failures.  Thanks again!

**Comment by mrmark** [comment]
Hello @jmcgettrick, sorry for the noise but any updates on this?  We are getting closer to upgrading our clients to 3.1 and would be good to have this functioning for them.

**Comment by dwinn** [comment]
Hi @mrmark ,

This has been fixed in the latest release v2015012501

**Comment by mrmark** [comment]
Thanks!

**Comment by Deleyna** [comment]
I apologize for adding this here, but I'm getting desperate for an answer. I'm getting: The following plugins in your system are using Events 1 API deprecated handlers: ''.  on my notifications screen. Note that the list is blank. Can anyone give me a hint as to where and what I should be looking for to clean this?

**Comment by jmcgettrick** [comment]
Hi @Deleyna, What version of the plugin are you currently on?

**Comment by Deleyna** [comment]
Sorry, somehow I missed the reply, and I should explain: I'm not using your plugin. I was just hoping that someone who has dealt with this Events 1 API deprecation could give me a hint as to how to figure out which plugin is throwing the error when I have a blank list like that. This was the only place that it seemed like anyone understood what was going on.

**Comment by jmcgettrick** [comment]
The main thing will be that you've still got a plugin installed that has event handlers defined. Look in every mod/.../db folder for an events.php file and check if it contains `$handlers`

**Comment by Deleyna** [comment]
Thank you. It turns out there was an obsolete entry in the events_handlers table.

**Comment by idigorasu** [comment]
> Thank you. It turns out there was an obsolete entry in the events_handlers table.

Thank you so much! I was going crazy with the same deprecated handlers error you had. Turns out the events_handlers table was the answer! Finally!
