### ISSUE TITLE
New release now shows problems creating assignments.

### ISSUE THREAD

**Issue by Syxton** [turnitin/moodle-plagiarism_turnitin#167]
![error1](https://cloud.githubusercontent.com/assets/989354/17145303/a953334a-5327-11e6-8353-944707ea2c3e.png)

This is the error shown when an assignment is submitted to.

If as the teacher I go to the Launch Peermark Manager link in the assignment settings I see:
![error2](https://cloud.githubusercontent.com/assets/989354/17145379/e22d56f0-5327-11e6-877e-d12f38838063.png)

The API log looks like this: 
[errorlog.txt](https://github.com/turnitin/moodle-plagiarism_turnitin/files/384248/errorlog.txt)

**Comment by Syxton** [comment]
We are running Moodle 3.1.1 and the api connection test is successful.

**Comment by Syxton** [comment]
Also, the turnitintooltwo assignment is working fine from the same course.

**Comment by davidmhatton** [comment]
Hi @Syxton, 
Could you confirm for me which version you upgraded _from_?

**Comment by Syxton** [comment]
looks like 2016011105

**Comment by Syxton** [comment]
I'm also getting this in our error logs:

* line 495 of /lib/setuplib.php: moodle_exception thrown
* line 686 of /mod/turnitintooltwo/lib.php: call to print_error()
* line 149 of /mod/turnitintooltwo/turnitintooltwo_comms.class.php: call to turnitintooltwo_print_error()
* line 844" while reading response header from upstream, client: 137.112.34.167, server: localhost, request: "GET /plagiarism/turnitin/ajax.php?cmid=349982&action=peermarkmanager&view_context=box HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "moodle-dev.rose-hulman.edu", referrer: "https://moodle-dev.rose-hulman.edu/course/modedit.php?update=349982&return=1"
2016/07/26 11:46:47 [error] 1624#1624: *3056 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: turnitin_assignid in /var/www/moodle/plagiarism/turnitin/lib.php on line 1087" while reading response header from upstream, client: 137.112.34.167, server: localhost, request: "POST /plagiarism/turnitin/ajax.php HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "moodle-dev.rose-hulman.edu", referrer: "https://moodle-dev.rose-hulman.edu/course/modedit.php?update=349982&return=1"
2016/07/26 11:52:02 [error] 1624#1624: *3119 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: turnitin_assignid in /var/www/moodle/plagiarism/turnitin/lib.php on line 1087" while reading response header from upstream, client: 137.112.34.167, server: localhost, request: "POST /plagiarism/turnitin/ajax.php HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "moodle-dev.rose-hulman.edu", referrer: "https://moodle-dev.rose-hulman.edu/course/modedit.php?update=349982&return=1"
2016/07/26 11:52:04 [error] 1624#1624: *3119 FastCGI sent in stderr: "PHP message: Default exception handler: turnitintooltwo/There was an error trying to create the assignment in Turnitin<br /><br />Fault Code: invaliddata | File: [dirroot]/mod/turnitintooltwo/sdk/assignmentsoap.class.php | Line: 33 | Message: submit_papers_to - invalid value 
 | Code: 0 Debug: 
Error code: There was an error trying to create the assignment in Turnitin<br/><br/>Fault Code: invaliddata | File: [dirroot]/mod/turnitintooltwo/sdk/assignmentsoap.class.php | Line: 33 | Message: submit_papers_to - invalid value 
 | Code: 0
$a contents: There was an error trying to create the assignment in Turnitin<br/><br/>Fault Code: invaliddata | File: [dirroot]/mod/turnitintooltwo/sdk/assignmentsoap.class.php | Line: 33 | Message: submit_papers_to - invalid value 
 | Code: 0

**Comment by davidmhatton** [comment]
Hi @Syxton 

I think we have an answer for you, but it's account-specific. Try changing the _Store Student Papers_ dropdown to the other option to the one you are using (sorry for the convoluted phrasing but I'm reluctant to discuss actual setting values on an open forum).
In essence the settings values on the plugin must match the values enforced by the account settings.

David

**Comment by Syxton** [comment]
@davidmhatton I have checked the setting.  In the turnitintwo tool setting, I had it set so that it was always standard, and this made the plagiarism setting not show up (this was ideal).  I changed the setting to allow the instructor to have options, and locked the setting with the checkbox, but this didn't actually lock the setting.  However it does submit files to Turnitin now.  I hope I was clear.  I was trying to be equally as discrete.

**Comment by davidmhatton** [comment]
@Syxton thanks for confirming.
I'll close this issue as resolved. If you have any further problems please don't hesitate to contact our support team.

**Comment by Syxton** [comment]
@davidmhatton I wanted to say thank you for your help and I saw the change in the Changelog to help curb this issue.  However, my settings already matched my account settings.  Having the system force the standard repo stopped working.

**Comment by davidmhatton** [comment]
Hi @Syxton,

This sounds like something a bit more involved and in-depth. if you contact our support team they should be able to provide greater levels of assistance.

Kind regards

David
