### ISSUE TITLE
Error Update sql to include additional name fields

### ISSUE THREAD

**Issue by christos312** [turnitin/moodle-plagiarism_turnitin#173]
Hello, I am getting the error below in my logs, is it something that I have to worry about?

The plugin version is 2016072601

Debugging: You need to update your sql to include additional name fields in the user object. in \n* line 3269 of /lib/moodlelib.php: call to debugging()\n* line 193 of /mod/turnitintooltwo/turnitintooltwo_submission.class.php: call to fullname()\n* line 69 of /mod/turnitintooltwo/turnitintooltwo_submission.class.php: call to turnitintooltwo_submission->get_submission_details()\n* line 1557 of /mod/turnitintooltwo/turnitintooltwo_assignment.class.php: call to turnitintooltwo_submission->__construct()\n* line 1606 of /mod/turnitintooltwo/turnitintooltwo_assignment.class.php: call to turnitintooltwo_assignment->update_submissions_from_tii()\n* line 247 of /mod/turnitintooltwo/ajax.php: call to turnitintooltwo_assignment->refresh_submissions()\n,

Thanks

**Comment by dwinn** [comment]
Hi @christos312 ,

This is nothing to worry about. We will look into fixing it however.

**Comment by christos312** [comment]
All right, thank you :D
