### ISSUE TITLE
[Regression] Grades revealed when grade is assigned in Gradebook

### ISSUE THREAD

**Issue by mhughes2k** [turnitin/moodle-plagiarism_turnitin#177]
This is a follow up to the #141.

I tested the latest version in the Moodle Plugins directory (2016091401) and found that the behaviour in #141 appears.

I tested our current version installed (2016072601) and found that this behaviour _isn't_ demonstrated.

Which is odd, so I diffed the two and found that in lib.php the upgrade_grade() function has changed.

In 2016072601 there is a clause which checks the assign module instances's blindmarking and revealgrades properties.

In 2016091401this check has disappeared, and it simply calls the `assign_grade_item_update()` function.

![tiiregression](https://cloud.githubusercontent.com/assets/694841/19119764/b8eaa846-8b18-11e6-8741-86eb2c1216f3.png)

[diff.zip](https://github.com/turnitin/moodle-plagiarism_turnitin/files/511585/diff.zip)

**Comment by mhughes2k** [comment]
Any news on this?

**Comment by amclarty** [comment]
@mhughes2k I'll run through the workflow today and let you know.

**Comment by amclarty** [comment]
@mhughes2k This is fixed in the develop branch: 88ccd0f8236e81537de6c838e6bb1d7ced59a238

We should be releasing shortly. Apologies for the delay.

**Comment by dwinn** [comment]
Hi @mhughes2k ,

This has been fixed in the latest release v2015012501

**Comment by mhughes2k** [comment]
Is that the right version number? 2015??

**Comment by dwinn** [comment]
Hi @mhughes2k,

Thanks for noticing this. You are right, 2015012501 was not correct originally. It was correct in the release code, I just made a typing error when closing a number of issues on here and then went back through and edited the comments to fix it. The correct version number is v2017012501.
