### ISSUE TITLE
Using turnitin rubrics does not allow students to view Grademark tool

### ISSUE THREAD

**Issue by upats** [turnitin/moodle-plagiarism_turnitin#18]
As described above, it seems that if using a Rubric to grade an assignment with the turnitin plagiarism plugin enabled, students can't click on anything to view the Grademark tool which would show them inline comments from their instructor.

There is only the rubric icon on their submission page which opens up the rubric with their scores. There's no other way I can find that allows the student to see comments in Grademark.

**Comment by jmcgettrick** [comment]
The Grademark icon should be visible to the student if there has been a grade set in GradeMark. Has a grade been set as well as feedback or is just feedback?

**Comment by upats** [comment]
Ahh, thanks, I had forgotten about this!

This has happened to us a few times now... would there possibly be a way to trigger the Grademark feature if Comments have been added AND/OR a grade has been entered? Professors assume that if they enter comments into grademark that students will be able to view them. They don't necessarily use Grademark to actually enter a numerical grade.

-Tony

**Comment by upats** [comment]
Also, when using a Rubric there is no need to enter a numerical grade!

**Comment by jmcgettrick** [comment]
No problem Tony, we'll get that fixed.

**Comment by jmcgettrick** [comment]
This has been fixed in 2016011101
