### ISSUE TITLE
default values in submitter and student_read columns are inconsistent.

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-plagiarism_turnitin#190]
the upgrade scripts set the default value for the fields submitter and student_read to NULL, but the install.xml file sets the default as "0"
https://github.com/turnitin/moodle-plagiarism_turnitin/blob/master/db/upgrade.php#L162
https://github.com/turnitin/moodle-plagiarism_turnitin/blob/master/db/upgrade.php#L171

can you please add a new upgrade step to fix the default value to the same value as set in install.xml? - or fix the install.xml to use null and then add an upgrade step to set the default to Null for those installs that have it set to "0" - it is important for the db structure to match what is set in the install.xml files.

**Comment by danmarsden** [comment]
the upgrade script to add the field looks like it allows null values, but the install.xml has not null set - you will need to run an update call to fix the null values and set them to 0 before running the upgrade script to fix the default values.

**Comment by dwinn** [comment]
Hi @danmarsden ,

Thanks for pointing this out, we will get it fixed.

**Comment by dwinn** [comment]
Hi @danmarsden ,

This has been fixed in the latest release v2015012501
