### ISSUE TITLE
allow modification to the cron_submissions_limit

### ISSUE THREAD

**Issue by upats** [turnitin/moodle-plagiarism_turnitin#193]
I noticed there's a limit on how many updates will process during the cron as defined by the 'PLAGIARISM_TURNITIN_CRON_SUBMISSIONS_LIMIT'. It's hardcoded at 100. Would it be possible to make this a modifiable setting in the plugin's setting page?

We notice that grade/submission updates get quite back-logged during peak turnitin usage times (end of semester, especially) and it would be nice if we could up the limit of submissions to process in each batch.

Of course I could change the limit that's hard coded but I'm sure it was put there for a reason.

**Comment by amclarty** [comment]
Hi @upats, thanks for your suggestion!

We'll get this implemented in a future release. I'll leave this ticket open and post here once the feature is released.

We chose the number 100 as some institutions have a cron that runs frequently. With hindsight this should have been a setting, so thanks for bringing it up.

**Comment by jmcgettrick** [comment]
Hi, @upats we won't be adding this as another setting. We are currently looking at ways to simplify this plugin so don't really want to add additional settings.
