### ISSUE TITLE
Turnitin slows mod/forum/post.php even when TII is not enabled for that mod.

### ISSUE THREAD

**Issue by roperto** [turnitin/moodle-plagiarism_turnitin#194]
A call to mod/forum/post.php may trigger a print_disclosure() for all plagiarism plugins.

If the TII server is slow (or there is a timeout), the page becomes very slow even when turn it in is not needed.

**Comment by roperto** [comment]
Hi,

I created pull requests to both master and develop as I am not sure how workflow with TII.

Cheers,
Daniel

**Comment by danmarsden** [comment]
afaik they go to develop first and then TII pushes through to master on release.

**Comment by roperto** [comment]
Thanks dan, when (if) they merge one then I will remove the other request :-)

**Comment by jmcgettrick** [comment]
Fixed in v2017052401
