### ISSUE TITLE
Students unable to access rubrics

### ISSUE THREAD

**Issue by ghost** [turnitin/moodle-plagiarism_turnitin#198]
Our students are unable to access Rubrics from the assignment summary page. When they click the _View the Rubric used for marking_ button, a form within a completely unrelated block is submitted (in this case, a library search block).

This is caused by the fact that the plugin injects HTML into the page, finds a form at index 0 within the page, then submits it. Unfortunately the form within the library search block happens to be at position 0 within the HTML page.

The issue seems to be caused by a line in the following file: https://github.com/turnitin/moodle-plagiarism_turnitin/blob/master/ajax.php#L157. A number of other forms within the plugin are also likely to be affected by this.

The plugin assumes that no other forms will be on the page, however this is not an assumption that can be made; the form index cannot be relied upon, as blocks, themes and other plugins can introduce their own forms that will change the index of the injected forms. I would recommend that the plugin finds the form by ID rather than numerical index.

The assignment summary page:
![rubric issue](https://cloud.githubusercontent.com/assets/15365068/20801575/5522aa66-b7e1-11e6-8475-1466b3fc69ea.png)

**Comment by dwinn** [comment]
Hi @jbriggscmet,

Thank you for the detailed report. This does indeed sound like a bug, so we will make a ticket and get it fixed.

**Comment by carl-hostrander** [comment]
This is in the release today which the version is 20240724.

**Comment by carl-hostrander** [comment]
This is in the release today.
