### ISSUE TITLE
In Moodle 3.x grader interface the jquery is failing.

### ISSUE THREAD

**Issue by Syxton** [turnitin/moodle-plagiarism_turnitin#200]
![error](https://cloud.githubusercontent.com/assets/989354/20975171/9c40d348-bc6c-11e6-8589-82ce6850bbc3.png)

**Comment by jmcgettrick** [comment]
Hi @Syxton - we'll get this looked at.

**Comment by tonyjbutler** [comment]
+1 for this being fixed. Cheers

**Comment by tonyjbutler** [comment]
@jmcgettrick Any idea when this may be fixed?
Thanks.

**Comment by jbriggscmet** [comment]
This is happening intermittently for us as well, however we are using Moodle 3.0.4.

Looks as though the JS in `turnitin_module.js`/`turnitintooltwo.js` is sometimes executed before jQuery has loaded.

Any ETA on a fix?
Thanks

![tii jquery issue](https://cloud.githubusercontent.com/assets/15365068/24854120/2ce59144-1dd5-11e7-95a9-a5e55a6655fa.PNG)

**Comment by jmcgettrick** [comment]
Re-opening. PR 241 closed this automatically and it had to be reverted.

**Comment by jmcgettrick** [comment]
This is fixed in v2017052401. There are still come JS errors in the console though which require a refactor to fix.
