### ISSUE TITLE
Boost Theme, Moodle 3.2 top menu, course name and breadcrumb not visible

### ISSUE THREAD

**Issue by jamatrucola** [turnitin/moodle-plagiarism_turnitin#202]
Just a heads-up as you guys work on upgrading the plugin for Moodle 3.2.  I loaded version 2016091401 in an environment where I'm testing the new Boost theme in Moodle 3.2.  I'm finding that several components that are supposed to be at the top of the page (the top menu, course name and breadcrumb) are not visible on a Turnitin 2 assignment page (/mod/turnitintooltwo/view.php?id=xxx).

FYI, in case it helps.  I noticed the same problem on at least one other core Moodle page, and reported the issue in the Moodle tracker as [MDL-57367](https://tracker.moodle.org/browse/MDL-57367?filter=14274).

**Comment by amclarty** [comment]
Thanks @jamatrucola.

We're currently working on supporting Moodle 3.2 and the new theme. We'll add this to the list!

**Comment by jmcgettrick** [comment]
Fixed in v2017022201
