### ISSUE TITLE
Duplicated entries in plagiarism_turnitin_config

### ISSUE THREAD

**Issue by roperto** [turnitin/moodle-plagiarism_turnitin#204]
I've found some duplicated entries (same `cm` and `name`) in table `plagiarism_turnitin_config`.

I believe this table should have a unique index with those columns as it would prevent generation of this duplicates.

**Comment by dwinn** [comment]
Hi @roperto,

Thanks for the report. We will look into this.

**Comment by jmcgettrick** [comment]
Fixed in v2017022201
