### ISSUE TITLE
Error in plugin update

### ISSUE THREAD

**Issue by fidelleon** [turnitin/moodle-plagiarism_turnitin#213]
plagiarism_turnitin
Field "submitter" does not exist in table "plagiarism_turnitin_files"

More information about this error

×Debug info: 
Error code: ddlfieldnotexist
×Stack trace:
line 586 of /lib/ddl/database_manager.php: ddl_field_missing_exception thrown
line 632 of /lib/ddl/database_manager.php: call to database_manager->change_field_type()
line 248 of /plagiarism/turnitin/db/upgrade.php: call to database_manager->change_field_notnull()
line 552 of /lib/upgradelib.php: call to xmldb_plagiarism_turnitin_upgrade()
line 1742 of /lib/upgradelib.php: call to upgrade_plugins()
line 683 of /admin/index.php: call to upgrade_noncore()

Moodle 3.1.4+ (Build: 20170127)

Plugin current version: 2.6+ 2016091401
Turnitintwo version: 2.7+ 2017012501

**Comment by dwinn** [comment]
Hi @fidelleon ,

We made a change to this field in the last release but that was just to allow null values. If the field doesn't exist in your table that may throw an error but I can't see why the field would not exist as it is added during the original install as well as during an upgrade in a 2015 version for people using older versions than that.

Would you be able to tell us which database you are using? And could you also check your database and see if the submitter field is in this table? It should also appear in the data dump if it is easier to access that.

**Comment by jmcgettrick** [comment]
We have released a patch for this. Version 2017013101.

**Comment by fidelleon** [comment]
Sorry for the late timing. I have just deployed such version and the upgrade has run flawless, thanks!
