### ISSUE TITLE
Undefined property: turnitintooltwo_user::$useragreementaccepted

### ISSUE THREAD

**Issue by roperto** [turnitin/moodle-plagiarism_turnitin#217]
`Notice: Undefined property: turnitintooltwo_user::$useragreementaccepted in .../plagiarism/turnitin/lib.php on line 431`

I am getting this error when submitting an assignment.

**Comment by jmcgettrick** [comment]
Hi @roperto - is this in Moodle 3.2?

**Comment by roperto** [comment]
Hi @jmcgettrick 

I am using it on Moodle 3.1,

Cheers,

Daniel

**Comment by dwinn** [comment]
Hi @roperto,

We changed some variable names in the last release as a result of Travis linting suggestions. PP depends on Moodle Direct V2, did you also update this plugin? This could explain the variable names not matching up.

**Comment by roperto** [comment]
Hi. I didn't update Moodle Direct V2 (what is it?) but I did forget to update `mod/turnitintooltwo`

After updating `mod/turnitintooltwo` it worked, so I am closing this issue.

Thanks for the feedback,

Daniel

**Comment by dwinn** [comment]
Hi @roperto,

Glad to hear you have resolved the issue.

Moodle Direct V2 is a separate plugin which creates a Turnitin assignment module, whereas the Plagiarism Plugin adds Turnitin functionality to the Moodle assignment module. As they both connect to Turnitin they share a fair bit of code.
