### ISSUE TITLE
Cannot upgrade Moodle from earlier versions due to deprecated library require_once.

### ISSUE THREAD

**Issue by nhoobin** [turnitin/moodle-plagiarism_turnitin#219]
MDL-46122 has removed lib/pluginlib.php from the code base.

When upgrading from Moodle 2.7 the database considers itself to be on the $CFG->branch = 27 while the code could be 3.1+, the file does not exist and the upgrade will fail. lib.php:40

**Comment by jmcgettrick** [comment]
Fixed in v2017052401
