### ISSUE TITLE
Missing language string in the "en" pack

### ISSUE THREAD

**Issue by Syxton** [turnitin/moodle-plagiarism_turnitin#223]
Invalid get_string() identifier: 'task_name' or component 'plagiarism_turnitin'. Perhaps you are missing $string['task_name'] = ''; in /var/www/moodle/plagiarism/turnitin/lang/en/plagiarism_turnitin.php?

**Comment by dwinn** [comment]
Hi @Syxton,

Which version are you using? This language string was previously used in the file `classes/task/plagiarism_turnitin_task.php` but we removed this file in the release v2017012501 when we changed to the Events 2 API and replaced it with two new cron tasks which should exist in the same directory - send_submission and update_reports. This older task shouldn't be getting called in that version or the latest v2017013101.

**Comment by Syxton** [comment]
plagiarism plugin v2017013101
turnitintooltwo v2017012501

I'm seeing the error message on the Scheduled Task page

**Comment by dwinn** [comment]
Which tasks (or files) do you have listed in the `classes/task/` directory from the root of the PP?

**Comment by Syxton** [comment]
plagiarism_turnitin_task.php
send_submissions.php
update_reports.php

**Comment by Syxton** [comment]
I can see that an old file is still there.  I'll look into this again.  Thanks for your help

**Comment by dwinn** [comment]
That's interesting - the file plagiarism_turnitin_task shouldn't exist in the version you are using, and its corresponding task should have also been removed from the database. Perhaps something went wrong during your upgrade.

The task in the database will be in the table `mdl_task_scheduled`. If you're comfortable with using SQL on the database you could check this with the query:

`SELECT * FROM mdl_task_scheduled WHERE component = 'plagiarism_turnitin' AND classname = '\plagiarism_turnitin\task\plagiarism_turnitin_task';`

The query should result in 0 rows returned.

**Comment by Syxton** [comment]
Thank you for your feedback @dwinn.  I would assume that our IT staff moved the new files and overwrote the files instead of deleting the old files and then moving the new files in.

**Comment by danmarsden** [comment]
yeah - that's a pretty common mistake - @dwinn - I expect you'll have a few more reports like this, If it was my code I'd be tempted to add a big warning/notification somewhere if someone has updated the code but not removed the old files.

**Comment by jmcgettrick** [comment]
Closing. This was fixed in v2017013101.
