### ISSUE TITLE
Papers stuck in "Queued" Status

### ISSUE THREAD

**Issue by mkpelletier** [turnitin/moodle-plagiarism_turnitin#224]
PP Version: 2.7+ (2017013101)
TITool2 Version: 2.7+ (2017012501)
Moodle Version: 3.1.3+(20161129)

After installing the above update, we have many papers stuck in "Queued" status.  From looking at the Activity Log and API Log, we are getting these errors which are causing the cronjob to stop before processing the papers in the queue:
Fault Code: invaliddata | File: ..../turnitintooltwo/sdk/usersoap.class.php | Line: 39 | Message: email - This field is required 
 | Code: 0
2017-02-07 14:44:56 +0200 (PRINT_ERROR) - Turnitin user creation failed

Fault Code: invaliddata | File: ...../turnitintooltwo/sdk/usersoap.class.php | Line: 39 | Message: email - This field is required 
 | Code: 0

In spite of the error, the log reports a number of other files being processed (in other courses?).  I have a vague memory of reporting a similar error a couple of years ago, before these plugins were moved from John's github account to turnitin.  I believe the error is related to user accounts that are not fully setup or which are missing an email address.

**Comment by Syxton** [comment]
I am seeing similar issues after updating.  On our dev system I uninstalled the plagairism plugin and reinstalled and now it is working, but that isn't a solution for us because it would remove all previous Turnitin submission results.

**Comment by jmcgettrick** [comment]
Is there a particular user that is errorring?

**Comment by Syxton** [comment]
For me it is a dev user account I have used countless times.

**Comment by jmcgettrick** [comment]
That's strange. Were they unlinked? I assume they have an email address?

**Comment by Syxton** [comment]
They do have an email address however it isn't real.  testuser1@local.host  Though it has worked in previous versions

**Comment by jmcgettrick** [comment]
Can you both check the first submission in your files table that has a statuscode of 'pending' or 'queued' please? Is the submitter value blank or NULL?

**Comment by danmarsden** [comment]
we're seeing similar issues - files stuck in a queued state in Moodle but the report shows fine when you log directly into Turnitin.
I'm also seeing lines like these in the apilogs which have started appearing since the update.

Fault Code: unknownobject | File: mod/turnitintooltwo/sdk/usersoap.class.php | Line: 57 | Message: User not found. | Code: 0
2017-02-08 21:22:27 +1300 (REQUEST) - Turnitin Assignment part updated - id: 24796570
2017-02-08 21:22:28 +1300 (API_ERROR) - Could not update user data

I'll try to take a look closer.

**Comment by danmarsden** [comment]
all the records in my mdl_plagiarism_turnitin_files table with "statuscode" => "pending" have the submitter field set to NULL
all the records with statuscode => "queued" have the submitter set to a valid integer.

**Comment by danmarsden** [comment]
Here are the records for 2 files from one student that show as queued but apparently the report is available if you log into to turnitin directly.

  id   |  cm   | userid |                identifier                | externalid | statuscode | similarityscore | attempt | transmatch | lastmodified | grade | submissiontype | orcapable | errorcode | errormsg | submitter | student_read | gm_feedback | duedate_report_refresh | itemid 
-------+-------+--------+------------------------------------------+------------+------------+-----------------+---------+------------+--------------+-------+----------------+-----------+-----------+----------+-----------+--------------+-------------+------------------------+--------
 50980 | 35420 |   4237 | 7668d661bff84d75ec7d5dbe42e21437a3714451 |            | queued     |                 |       3 |          0 |   1486591114 |       | file           |           |           |          |      4237 |              |           0 |                      2 |  77964
 50981 | 35420 |   4237 | 308dbe92ff8341e729910ce8ba4c33b7a0d514d9 |            | queued     |                 |       2 |          0 |   1486591114 |       | file           |           |           |          |      4237 |              |           0 |                      0 |  77964
(2 rows)

**Comment by dwinn** [comment]
Hi @danmarsden,

We found a bug today relating to what @jmcgettrick was saying earlier. If the value of submitter is NULL for those pending entries then the queue will get stuck. A work around is to update these rows where the submitter field is NULL and set the submitter value to be that of the userid.

We are currently investigating this further and we will get it fixed.

The changes in the release that implemented queued gave the cron two tasks instead of the one it previously had. Task one sends the files to Turnitin and the second task updates the scores, so that may explain why you are seeing scores in Turnitin that aren't appearing in Moodle. If the cron is getting stuck due to that bug then this could be another side effect.

**Comment by danmarsden** [comment]
ran this which updated 161 records in this particular site:
update mdl_plagiarism_turnitin_files set submitter = userid where statuscode = 'pending' AND submitter is null;

1hr later still the same 161 records in the same state - and the "queued" records with a report in Turnitin have not updated in Moodle yet.

I do notice in this site there are several records with userid = 0 and statuscode = 'pending' - I'd guess they can probably be cleared out. (this site was using my old plugin but upgraded to this new one a couple of years ago)

**Comment by jmcgettrick** [comment]
Hi @danmarsden Did you clear out the records with userid = 0?

**Comment by Syxton** [comment]
@jmcgettrick Just wanted to point out that a very old record (just 1) was causing the plagiarism_turnitin_send_queued_submissions task to fail and #231 fixed it.  Thank you for this quick work.

**Comment by danmarsden** [comment]
thanks - shouldn't this be a "continue" call though? 
https://github.com/turnitin/moodle-plagiarism_turnitin/pull/231/commits/2f16fd3755d4e0c6d8e34901923a0b0ce3f2ccc3#diff-828043dc9f8d10ccd58ff8b96297794fR2538

**Comment by danmarsden** [comment]
looks like that's a general issue with that function - break is used instead of continue in a few places that look incorrect. I've created #232 for that.

**Comment by danmarsden** [comment]
- the patch in #231 does seem to fix this, just really slowly processes the queue if there are several items with userid =0 or null as when it finds a record like this it stops the cron process.

**Comment by jmcgettrick** [comment]
Fixed in v2017022201

**Comment by mkpelletier** [comment]
Excellent!  I'll give it a whirl and let you know if anything comes up.
