### ISSUE TITLE
Error message returned from TII not saved.

### ISSUE THREAD

**Issue by roperto** [turnitin/moodle-plagiarism_turnitin#226]
To reproduce:

* Submit an assignment with less than 20 words.
* Run the task
   * `php admin/tool/task/cli/schedule_task.php --execute=\\plagiarism_turnitin\\task\\send_submissions`
   * You should see: `Turnitin has returned an error with your submission:: Your submission must contain 20 words or more.`
* Go to the submissions page
   * You should see `This file has not been submitted to Turnitin, please consult your tutor for further details.`
   * I expected to see the previous more descriptive error message.

**Comment by roperto** [comment]
See pull request: https://github.com/turnitin/moodle-plagiarism_turnitin/pull/227

**Comment by jmcgettrick** [comment]
Thanks @roperto, that's been merged.
