### ISSUE TITLE
$pathnamehash not defined in function

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-plagiarism_turnitin#230]
looks like a copy/paste from a different function, but $pathnamehas isn't defined here.

https://github.com/turnitin/moodle-plagiarism_turnitin/blob/master/lib.php#L2585

just saw this when flicking through the code - not sure if it will cause a problem anywhere though.

**Comment by danmarsden** [comment]
fixed in https://github.com/turnitin/moodle-plagiarism_turnitin/commit/12c87fe2a885af1c5c35ed244aff18e0232c892a

**Comment by jmcgettrick** [comment]
Fixed in v2017022201
