### ISSUE TITLE
use of break in plagiarism_turnitin_send_queued_submissions for loop incorrect

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-plagiarism_turnitin#232]
a number of locations inside the main queueditems loop the "break" call is used when it would be more appropriate to use "continue"
Particularly when the file cannot be sent becauese the course cannot be created, or the submission has an empty userid, or if the user has not signed the EULA - this should not prevent all other submissions from being processed by calling "break" - "continue" should be used to allow the next queued item to be processed.

**Comment by danmarsden** [comment]
Looked like it may also have ended up in some cases causing the scheduled task to not return true and Moodle then thinks it's in a error state so delays the next cron by 24 hrs.

**Comment by dwinn** [comment]
Hi @danmarsden ,

Thanks for the report. We will get this looked at. I think you are right continue would make more sense for that functionality.

**Comment by jmcgettrick** [comment]
Fixed in v2017022201
