### ISSUE TITLE
PHP Notice:  Trying to get property of non-object in /plagiarism/turnitin/lib.php on line 2664

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-plagiarism_turnitin#233]
line 2664:
$textcontent = strip_tags($forumpost->message);

probably because $forumpost is empty and couldn't be found.

**Comment by danmarsden** [comment]
(saw this in cron log.)

**Comment by dwinn** [comment]
Hi @danmarsden,

Thanks for the report. We'll get this fixed.

**Comment by jmcgettrick** [comment]
Fixed in https://github.com/turnitin/moodle-plagiarism_turnitin/pull/235

**Comment by jmcgettrick** [comment]
Fixed in v2017022201
