### ISSUE TITLE
Fatal error/PHP notices - undefined var title/filename/textcontent

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-plagiarism_turnitin#234]
I see this in the cronlog: (all at once but I've added the code from those lines to help you find the specific case as my line numbers might be slightly different as I have cherry-picked fixes from the develop branch)

PHP Notice:  Undefined variable: title in plagiarism/turnitin/lib.php on line 2672
$submissiontitle = explode('.', $title)

PHP Notice:  Undefined variable: filename in /plagiarism/turnitin/lib.php on line 2692
$tempfile = turnitintooltwo_tempfile($filestring, $filename);

PHP Notice:  Undefined variable: textcontent in plagiarism/turnitin/lib.php on line 2706
fwrite($fh, $textcontent);

PHP Notice:  Undefined variable: apimethod in plagiarism/turnitin/lib.php on line 2712
if ($apimethod == "replaceSubmission") {

PHP Notice:  Undefined variable: title in plagiarism/turnitin/lib.php on line 2715
$submission->setTitle($title);

PHP Notice:  Undefined variable: apimethod in  plagiarism/turnitin/lib.php on line 2737
PHP Fatal error:  Method name must be a string in plagiarism/turnitin/lib.php on line 2737
$response = $turnitincall->$apimethod($submission);

**Comment by jmcgettrick** [comment]
Cheers @danmarsden, does the first submission being processed have a value for submissiontype?

**Comment by danmarsden** [comment]
not sure about the submissiontype sorry - I think you're right that you just need to add a few validation checks before using/submitting the files etc. Feel free to close this as a duplicate - I just thought it would be useful to have the errors here (and indexed by Google for others that might run into this)

**Comment by jmcgettrick** [comment]
No, keep it open. I just meant that it was a similar fix.

**Comment by danmarsden** [comment]
I'm seeing this on every cron run now - I suspect the fatal error is also causing further processing to stop. Probably an invalid file somewhere in the queue.

**Comment by danmarsden** [comment]
yeah - submissiontype was empty in those records which was holding up the queue.

**Comment by jmcgettrick** [comment]
These should all be fixed in https://github.com/turnitin/moodle-plagiarism_turnitin/pull/235

**Comment by jmcgettrick** [comment]
Fixed in v2017022201
