### ISSUE TITLE
Deprecated use of stdClass object at message_send

### ISSUE THREAD

**Issue by guillalva06** [turnitin/moodle-plagiarism_turnitin#239]
The use of an stdClass object as first parameter of the function message_send was deprecated(See https://tracker.moodle.org/browse/MDL-47162). Now, you have to use a \core\message\message object as parameter.  The function message_send with their wrong object parameter is in pp_receipt_message.php. Could you replace the wrong parameter?

**Comment by jmcgettrick** [comment]
We'll get this looked at.

**Comment by jmcgettrick** [comment]
Fixed in #458
