### ISSUE TITLE
Submissions are stuck at "Turnitin status: Queued"

### ISSUE THREAD

**Issue by mike-wilson-uk** [turnitin/moodle-plagiarism_turnitin#240]
Moodle: 2016052303
Turnitin Plagiarism Plugin: 2017022201
Turnitintooltwo: 2017031301

Similarity scores aren't being returned to our Moodle site. The submission is labelled as "Turnitin status: Queued" and doesn't move from this no matter how many times we run the CRON.

We're occasionally seeing a message in the CRON log of:
[Turnitin Plagiarism Plugin] Aborted Cron call because of active task mode

I've read through previous solutions to similar issues stating that  moodle.mdl_plagiarism_turnitin_files.submitter contains some records with 0 or null values. This isn't the case for us, the fields are populated with the students userid.

Any help would be greatly appreciated.

Mike

**Comment by jmcgettrick** [comment]
Hi @mike-wilson-uk - the problem is always with the first file with the status of Pending or Queued. Is there anything about that particular record that's strange? E.g. the cm no longer exists or the file has been deleted?

**Comment by mike-wilson-uk** [comment]
Hi @jmcgettrick I can't see anything that stands out with the file it's just a standard docx. I've created a number of new assignments to test it without joy. I've even uninstalled and re-installed the plugin in case there's some sitting in cache the could affected it. 

There are only three rows in mdl_plagiarism_turnitin_files after the reinstall (data below if it's of any use). 

We did have some 0 and null records when I first upgraded the plugin but updating with userids and ultimately reinstalling the plugin didn't fix the problem.

Cheers

# id, cm, userid, submitter, identifier, externalid, itemid, statuscode, similarityscore, attempt, transmatch, lastmodified, grade, submissiontype, orcapable, errorcode, errormsg, student_read, gm_feedback, duedate_report_refresh
'1', '435134', '108791', '108791', '300ffd27e4879e21836e09502cde85b3e58748fb', NULL, '67078', 'queued', NULL, '0', '0', '1492589719', NULL, 'file', NULL, NULL, NULL, NULL, '0', '0'
'2', '435134', '90679', '90679', '9e38a83025dc0484b465be58ac0afb00b49a5709', NULL, '67097', 'queued', NULL, '0', '0', '1492590308', NULL, 'file', NULL, NULL, NULL, NULL, '0', '0'
'3', '435135', '90679', '90679', 'a78cbb19712ea76c2addb2eb84c1dafd2d3ed394', NULL, '67100', 'queued', NULL, '2', '0', '1492593435', NULL, 'file', NULL, NULL, NULL, NULL, '0', '0'

**Comment by jmcgettrick** [comment]
That all looks ok, are you able to contact our customer support and we'll take a look at it?

**Comment by mike-wilson-uk** [comment]
Okey doke, will do. Thanks for your help, much appreciated.
