### ISSUE TITLE
Feature request: allow users to switch PeerMark and GradeMark on or off independently of mod_turnitintooltwo setting

### ISSUE THREAD

**Issue by porcospino** [turnitin/moodle-plagiarism_turnitin#245]
Hello

The display of icons and links to PeerMark and GradeMark are presently controlled by global configuration settings in mod_turnitintooltwo.

We would like to make these features available to users of mod_turnitintooltwo, but to disable them for Moodle assignments that make use of plagiarism_turnitin

The current settings are determined by `$config->enablepeermark` and `$config->usegrademark`, which are properties of the object returned by `turnitintooltwo_admin_config()`

It would be great if "Enable PeerMark" and "Enable GradeMark" were preferences that could be overridden on the settings page for the Plagiarism Plug-in

Chris

**Comment by jmcgettrick** [comment]
This was added in 2019050201
