### ISSUE TITLE
Add support for multi-part submissions via the PP

### ISSUE THREAD

**Issue by aspark21** [turnitin/moodle-plagiarism_turnitin#246]
The TII assignment supports parts but the PP doesn't.

As we primarily use TII via Coursework, we want to be able to have students submit multiple files per submission when needed. The logical way to do that would be to use the parts approach you have already implemented in the TII assignment V1 & V2.

**Comment by dwinn** [comment]
Hi @aspark21,

We can't implement parts into PP in the way we did in V2 as PP uses the Moodle assignment. The Moodle assignment does however support multi file upload using the setting "Maximum number of uploaded files", and that works with Turnitin. So you can use that to do what you want.
