### ISSUE TITLE
Feedback Studio showing old drafts submitted with PP

### ISSUE THREAD

**Issue by mkpelletier** [turnitin/moodle-plagiarism_turnitin#248]
We have a recent problem that has manifested itself in Feedback studio.  In Moodle we are using draft submissions.  This allows students to submit multiple drafts before the due date.  Some teachers are accustomed to opening an assignment from Moodle and marking in Feedback Studio (FS).  Then, rather than closing the FS window and letting Moodle refresh, they navigate between submissions within FS.  This used to work in Grademark, but it seems now that FS is showing _not just the final submission_ in the list of submissions, _but also preliminary drafts._  To further complicate matters, there is no clear distinction in the FS submission list which one is the final or latest submission.

The end result is:

1. Assignments are not synced in Moodle with the grade in FS
2. Teachers unwittingly mark a draft submission
3. The admin needs to go to the assignment edit screen to manually refresh the submissions
4. Some submissions never refresh because of the discontinuity between the final submission and what the teacher marked in FS (a draft submission).

**Comment by jmcgettrick** [comment]
Hi @mkpelletier - sorry for the delay in responding. How is the assignment set up? Is it using attempts? 

When the new submissions are being added by students are they replacing the previous files?

**Comment by mkpelletier** [comment]
Hi John,

Yes, assignments are set up to accept drafts or multiple provisional
submissions.  The students then submit when they are happy with their
submissions. These final submissions do NOT replace the provisional
submissions.  Instead, multiple submissions for a single student show in
feedback studio. This fact makes the quick navigation on the top right
useless.

Sent from my phone
pardon brevity and typos

**Comment by amolteno** [comment]
Hi, has there been any further progress on this issue? We are experiencing the same, often with markers marking and downloading the incorrect version (i.e. not the final submission) of the assignment.

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
