### ISSUE TITLE
EULA issue with already accepted users 

### ISSUE THREAD

**Issue by hitteshahuja** [turnitin/moodle-plagiarism_turnitin#250]
Using version 2016011105 . 
Installed the plugin on a brand new Moodle site. Setup correctly as Moodle can connect to tii without any issues. When trying to submit the file as an existing user, I always keep getting 

**This file has not been submitted to Turnitin because the user has not accepted the Turnitin End User Licence Agreement.**
This is incorrect because the user I am testing has already accepted the eula for the turinitin service, albeit on a different moodle site. Moreover, I dont see a link presented by the plugin to accept the EULA again. 

the api logs seems fine for the same  . I see classes created and users sent through but their submissions are not being accepted it seems. 

```
2017-05-31 15:49:06 +0100 (REQUEST) - Part created as Turnitin Assignment (789xxxx) - Tool Id: (0) - Part num: (0)
2017-05-31 15:49:24 +0100 (REQUEST) - User 3 (400xxxx) joined to class (3496xxx)
2017-05-31 15:50:08 +0100 (REQUEST) - Turnitin Assignment part updated - id: 789xxxx
2017-05-31 15:50:12 +0100 (REQUEST) - Turnitin Assignment part updated - id: 789xxxx
2017-05-31 15:59:05 +0100 (REQUEST) - Turnitin Assignment part updated - id: 789xxxx
2017-05-31 15:59:08 +0100 (REQUEST) - Turnitin Assignment part updated - id: 789xxxx
2017-05-31 16:02:09 +0100 (REQUEST) - Turnitin Assignment part updated - id: 789xxxx
2017-05-31 16:02:13 +0100 (REQUEST) - Turnitin Assignment part updated - id: 789xxxx
2017-05-31 16:02:59 +0100 (REQUEST) - User 4 (5515290) joined to class (3496xxx)
```

**Comment by hitteshahuja** [comment]
![image](https://cloud.githubusercontent.com/assets/2855029/26640459/af5b41ce-461f-11e7-87c3-4bcc7fcd9b20.png)

**Comment by jmcgettrick** [comment]
Hi, we can't reproduce this here. We've released six updated plugins since 2016011105 though, can you reproduce on the current version?

**Comment by hitteshahuja** [comment]
Hi John,
Yes, we can reproduce it on 2017052401. This is what we have done to reproduce the error :

- As a user who has never accepted the EULA, try to upload a file to an assignment and wait for the tii eula to show up. Click on 'Dont agree' and continue to upload the file anyways. As expected, the file will not be sent to turnitin and since the user did not accept the EULA there is an error = 3 status code in the mdl_plagiarism_turnitin_files table against the user. 

- As the same user try uploading a file in a different assignment and this time accept the EULA. This time  it writes it to the mdl_turnitintooltwo_users table with the user_agreement_accepted field set to 1 against that user and then this is processed to turnitin. 

- Although the user has retrospectively accepted the EULA this has not reset their previous submissions as they still hold errorcode = 3 and with a status of error hence never being processed (?). 

There seems to be a conflict between user_agreement_accepted in mdl_turnitintooltwo_users and errorcode = 3 in the mdl_plagiarism_turnitin_files table in my opinion which is stopping them going through. 

What I believe should happen is that the code should check for users who have retrospectively accepted the EULA and reset their submissions with their status code wiped off so they can be sent through the cron again , perhaps here: https://github.com/turnitin/moodle-plagiarism_turnitin/blob/master/lib.php#L2344 ?

**Comment by jmcgettrick** [comment]
I'm afraid that is the current intended behaviour. We have found that institutions have differing workflows where our EULA is concerned. From a Turnitin perspective, the user can't enrol themselves in Turnitin without accepting our EULA. We therefore can't go back and retrospectively submit as we don't know why the user declined the EULA at that particular time.

**Comment by haleyngonadi** [comment]
Hey, I'm not sure you understand what we mean. Users that have already accepted the EULA are the ones getting this error. For example, if the user already submitted an assignment using the Turnitin Module, when they have to submit an assignment that used the plagarism plugin instead, they are told they need to accept the EULA, which they already accepted. Sometimes, on my end, it even shows User Not Found.

**Comment by cwestgarth** [comment]
Hey @haleyngonadi, 

Are you able to tell me the plugin version you are seeing this error? Are you still experiencing the issue?

Thanks

**Comment by gpillsbury** [comment]
This issue just affected one of our users.  Thanks to the above information, I was able to solve it by manually updating the "errorcode" field from "3" to NULL in the user's row in the `mdl_plagiarism_turnitin_files` table. I then returned to the assignment and resubmitted to Turnitin. A few moments later, I had the originality report, so all seems well.
