### ISSUE TITLE
Turnitin jquery breaks Moodle 3.3 bulk completion editing

### ISSUE THREAD

**Issue by Syxton** [turnitin/moodle-plagiarism_turnitin#251]
Assuming:  Moodle 3.3

Course completion -> Bulk edit activity completion -> Select any assignment -> Edit

The following error is given:
Stack trace:
line 890 of /lib/pagelib.php: coding_exception thrown
line 86 of /completion/classes/bulkedit_form.php: call to moodle_page->start_collecting_javascript_requirements()
line 112 of /completion/classes/bulkedit_form.php: call to core_completion_bulkedit_form->get_module_form()
line 204 of /lib/formslib.php: call to core_completion_bulkedit_form->definition()
line 58 of /course/editbulkcompletion.php: call to moodleform->__construct()

Output buffer: </div><div class="notifytiny debuggingmessage" data-rel="debugging">Can not add jQuery plugins after starting page output!<ul style="text-align: left" data-rel="backtrace"><li>line 501 of /lib/outputrequirementslib.php: call to debugging()</li><li>line 155 of /plagiarism/turnitin/turnitinplugin_view.class.php: call to page_requirements_manager->jquery_plugin()</li><li>line 271 of /plagiarism/turnitin/lib.php: call to turnitinplugin_view->add_elements_to_settings_form()</li><li>line 117 of /lib/plagiarismlib.php: call to plagiarism_plugin_turnitin->get_form_elements_module()</li><li>line 192 of /mod/assign/mod_form.php: call to plagiarism_get_form_elements_module()</li><li>line 204 of /lib/formslib.php: call to mod_assign_mod_form->definition()</li><li>line 97 of /course/moodleform_mod.php: call to moodleform->__construct()</li><li>line 87 of /completion/classes/bulkedit_form.php: call to moodleform_mod->__construct()</li><li>line 101 of /completion/classes/edit_base_form.php: call to core_completion_bulkedit_form->get_module_form()</li><li>line 210 of /completion/classes/edit_base_form.php: call to core_completion_edit_base_form->add_custom_completion_rules()</li><li>line 110 of /completion/classes/bulkedit_form.php: call to core_completion_edit_base_form->definition()</li><li>line 204 of /lib/formslib.php: call to core_completion_bulkedit_form->definition()</li><li>line 58 of /course/editbulkcompletion.php: call to moodleform->__construct()</li></ul></div><div class="notifytiny debuggingmessage" data-rel="debugging">Can not add jQuery plugins after starting page output!<ul style="text-align: left" data-rel="backtrace"><li>line 501 of /lib/outputrequirementslib.php: call to debugging()</li><li>line 156 of /plagiarism/turnitin/turnitinplugin_view.class.php: call to page_requirements_manager->jquery_plugin()</li><li>line 271 of /plagiarism/turnitin/lib.php: call to turnitinplugin_view->add_elements_to_settings_form()</li><li>line 117 of /lib/plagiarismlib.php: call to plagiarism_plugin_turnitin->get_form_elements_module()</li><li>line 192 of /mod/assign/mod_form.php: call to plagiarism_get_form_elements_module()</li><li>line 204 of /lib/formslib.php: call to mod_assign_mod_form->definition()</li><li>line 97 of /course/moodleform_mod.php: call to moodleform->__construct()</li><li>line 87 of /completion/classes/bulkedit_form.php: call to moodleform_mod->__construct()</li><li>line 101 of /completion/classes/edit_base_form.php: call to core_completion_bulkedit_form->get_module_form()</li><li>line 210 of /completion/classes/edit_base_form.php: call to core_completion_edit_base_form->add_custom_completion_rules()</li><li>line 110 of /completion/classes/bulkedit_form.php: call to core_completion_edit_base_form->definition()</li><li>line 204 of /lib/formslib.php: call to core_completion_bulkedit_form->definition()</li><li>line 58 of /course/editbulkcompletion.php: call to moodleform->__construct()</li></ul></div><div class="notifytiny debuggingmessage" data-rel="debugging">Could not add custom completion rule of module assign to this form, this has to be fixed by the developer<ul style="text-align: left" data-rel="backtrace"><li>line 109 of /completion/classes/edit_base_form.php: call to debugging()</li><li>line 210 of /completion/classes/edit_base_form.php: call to core_completion_edit_base_form->add_custom_completion_rules()</li><li>line 110 of /completion/classes/bulkedit_form.php: call to core_completion_edit_base_form->definition()</li><li>line 204 of /lib/formslib.php: call to core_completion_bulkedit_form->definition()</li><li>line 58 of /course/editbulkcompletion.php: call to moodleform->__construct()</li></ul></div>

**Comment by Syxton** [comment]
Doubt it is the correct fix, but adding the following as the first line of logic in the function add_elements_to_settings_form() in turnitinplugin_view.class.php

        if ($PAGE->pagetype == 'course-editbulkcompletion') {
            return;
        }

**Comment by dwinn** [comment]
Hi @Syxton,

Thank you for the report. We will get this looked at. We are still testing the plugins in 3.3 and aim to support it soon.

**Comment by dwinn** [comment]
Hi @Syxton,

We will be fixing this in our next release. I don't see any issues with your fix either as we don't need the add_elements_to_settings_form() function on this page of Moodle. However I have modified it slightly so that we just don't call the function on that page rather than returning at the top of it.

**Comment by dwinn** [comment]
Hi @Syxton,

This has been fixed in today's release v2017070301.
