### ISSUE TITLE
Mod created event: error reading from database due to missing module

### ISSUE THREAD

**Issue by agrowe** [turnitin/moodle-plagiarism_turnitin#256]
We have many (many) rows in our events table due to plugins that no longer exist but still have existing rows in the events table.

When the the `lib/deprecatedlib.php` `events_dispatch()` function calls the plagiarism event handler, it is doing so with a modulename that no longer exists and Moodle's core code is not picking it up.

In `lib.php` of this plugin, for the function `event_handler($eventdata)`, can another check be added, before the `if` statement where it gets the course module id, to check if it is a valid modulename?

Something like the below?

````
if (!$DB->record_exists('modules', array('name' => $eventdata->modulename)) {
    return true;
}
````

Or check if the plugin is part of the enabled plugins for the module? e.g. only assignment if we disabled forum and workshop?

Below if the full error stact trace that we see in the event queue.

````
Handler function of component plagiarism_turnitin: s:37:"plagiarism_turnitin_event_mod_created"; threw exception :Error reading from database
* line 1088 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
* line 1527 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_records_sql()
* line 1297 of /lib/datalib.php: call to moodle_database->get_record_sql()
* line 1989 of /plagiarism/turnitin/lib.php: call to get_coursemodule_from_id()
* line 2826 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin->event_handler()
* line ? of unknownfile: call to plagiarism_turnitin_event_mod_created()
* line 3955 of /lib/deprecatedlib.php: call to call_user_func()
* line 3999 of /lib/deprecatedlib.php: call to events_dispatch()
* line 4147 of /lib/deprecatedlib.php: call to events_process_queued_handler()
* line 45 of /lib/classes/task/events_cron_task.php: call to events_cron()
* line 75 of /lib/cronlib.php: call to core\task\events_cron_task->execute()
* line 61 of /admin/cli/cron.php: call to cron_run()
Table 'health-hed.mdl_autoattendmod' doesn't exist
SELECT cm.*, m.name, md.name AS modname 
              FROM mdl_course_modules cm
                   JOIN mdl_modules md ON md.id = cm.module
                   JOIN mdl_autoattendmod m ON m.id = cm.instance
                   
             WHERE cm.id = ? AND md.name = ?
                   
[array (
  0 => 215377,
  1 => 'autoattendmod',
)]
````

**Comment by agrowe** [comment]
Would moving the line:

````
$moduletiienabled = $this->get_config_settings('mod_'.$eventdata->modulename);
````

To above `get_coursemodule_from_id()` or to be first called in `event_handler()` resolve this issue?

It would be better to check if the plugin should work on this type of plugin first of all before continuing onto other checks.

**Comment by jmcgettrick** [comment]
Yes @agrowe, either that or querying the modules table directly should sort it. Events from something like autoattendmod shouldn't really be getting into there though to my mind.

**Comment by agrowe** [comment]
Thanks, I moved the `$moduletiienabled` line and added an `if (empty($moduletiienabled)) {...` line to remove the event but we have so many events in there that we then ran into issues with Moodle cron timing out.

**Comment by jmcgettrick** [comment]
Good to hear @agrowe - glad it's sorted.
