### ISSUE TITLE
Core Moodle 3.3 unit test fails check of plugin state

### ISSUE THREAD

**Issue by azrek** [turnitin/moodle-plagiarism_turnitin#259]
Moodle version: 2017051500.10
DB: psql (PostgreSQL) 9.5.7
OS: Linux 16.04
moodle-plagiarism_turnitin version: 2017070301

We are upgrading to Moodle 3.3 and get this unit test error with the latest plagairism_turnitin plugin:

1) core_plugin_manager_testcase::test_plugin_states
Invalid plagiarism_turnitin state
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-uptodate
+upgrade

/home/clients/moodle/lib/tests/plugin_manager_test.php:287
/home/clients/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
vendor/bin/phpunit core_plugin_manager_testcase lib/tests/plugin_manager_test.php

FAILURES!

**Comment by jmcgettrick** [comment]
Thanks @azrek - we'll get that looked at.

**Comment by jmcgettrick** [comment]
Closing as tests are passing consistently.
