### ISSUE TITLE
Enforcing jQuery 1.8.2!!??

### ISSUE THREAD

**Issue by opitz** [turnitin/moodle-plagiarism_turnitin#261]
Hi!
I think there is an issue with loading jQuery 1.8.2 (lib.php - line 509+510) without checking the Moodle version first. This should happen only for Moodle 2.5 or below methinks.
We want to use Moodle 3.2 with a theme that requires bootstrap - which itself requires at least jQuery 1.9.1. 
So some pages fail with errors. 
Until I comment out these two lines - then everything seems to work fine.

Since Moodle 3.2 comes with jQuery 3.1.0 already loaded I wonder if there would be a reason to load the library in the first place..?
In mod/turnitintooltwo/mod_form.php you catch the version of Moodle running and load jQuery only of it is 2.5 or below - I suggest a similar solution here if possible.
Does that make sense?

Best,

m!

**Comment by opitz** [comment]
I suggest to replace 
        $jsurl = new moodle_url($CFG->wwwroot.'/plagiarism/turnitin/jquery/jquery-1.8.2.min.js');
        $PAGE->requires->js($jsurl);

with 
        if ($CFG->branch <= 25) {
            $jsurl = new moodle_url($CFG->wwwroot.'/plagiarism/turnitin/jquery/jquery-1.8.2.min.js');
            $PAGE->requires->js($jsurl);
        }
        else {
            $PAGE->requires->jquery();
        }

m!

**Comment by jmcgettrick** [comment]
We've had problems previously with this particular code where requiring jquery has caused a fatal error because the page headers have already been output.
We'll take another look at it though and thanks for the PR.

**Comment by porcospino** [comment]
I guess this is fixed in #297

**Comment by jmcgettrick** [comment]
Yes @porcospino - fixed now.
