### ISSUE TITLE
"Not authorised" error for group assignments

### ISSUE THREAD

**Issue by micaherne** [turnitin/moodle-plagiarism_turnitin#288]
We are seeing the following error message for most group assignments after upgrading to 2017112302 (from 2017022201):

> Turnitin has returned an error with your submission: You are not authorized to access this resource.

This appears to be caused by the fix to #277, which is changing the author to be the first person in the group alphabetically. If this is not the person submitting the error occurs.

To reproduce:

1. Create an assignment. Enable group submission and Turnitin.
2. Create a group with 5 students.
3. Log in as the middle student (alphabetically by surname) and submit a document.
4. Run the send_submissions task
5. Go to the "view all submissions" page where you should see the error.

**Comment by micaherne** [comment]
Just to note, we've checked that the fix for #277 is working fine - this is only happening for student group submissions.

**Comment by micaherne** [comment]
Also, this is on Moodle 3.2.6 (Build: 20171113).

**Comment by dwinn** [comment]
Hi @micaherne,

This has been fixed in the latest release v2018011601. Thanks for the contribution.
