### ISSUE TITLE
Similarity Score and Originality Report do not appear in forum search results

### ISSUE THREAD

**Issue by rayhinton** [turnitin/moodle-plagiarism_turnitin#291]
Running Moodle 3.3.3+ (Build: 20171123). We use the plagiarism plugin (v. 2017112302) and TII Assignment 2 (v. 2017112301).

We primarily use the PP in Moodle Forums and Assignments (i.e. we do not use the TII Assignment 2 activity). One of the ways that our instructors assess performance in forums is to search for a student's name in a forum with the Moodle Forum Advanced Search (mod/forum/search.php). When you view forum search results, you do not see the standard Similarity Score and Originality Report links, that normally appear at the bottom of each forum post. 

In this screenshot, the same forum post is shown in two separate windows. On the left, is the forum post as it appears in search results. On the right, is the same post as it appears in the actual forum. Notice that the post in the search results does not have the TII Similarity Score or Originality Report. Thanks!
![forum-search-and-post](https://user-images.githubusercontent.com/7245513/34909702-2303826a-f874-11e7-9636-7e3aeefcc029.png)

**Comment by danmarsden** [comment]
Ray - I suspect this might be a shortcoming in the moodle core plagiarism api and we might need to modify the moodle core code to support this. Can you please add an issue in the moodle tracker for the plagiarism component?

**Comment by jmcgettrick** [comment]
Thanks @danmarsden

**Comment by rayhinton** [comment]
Thank you for your insight, @danmarsden and @jmcgettrick, much appreciated. January got really busy for me! Anyway, I posted over a the [Moodle Developer forum](https://moodle.org/mod/forum/discuss.php?d=365039), and depending on what they think, I'll make a tracker issue. If any resolution comes about, I'll update here.

**Comment by rayhinton** [comment]
Completing the circle: created a Moodle Tracker issue for this.

https://tracker.moodle.org/browse/MDL-61345
