### ISSUE TITLE
Revealing student identities and grades in blind marking assignments

### ISSUE THREAD

**Issue by davidmhatton** [turnitin/moodle-plagiarism_turnitin#32]
The anonymous marking setting has used to be present in this plugin but has now been removed. Moodle's blind marking is now used to determine whether an assignment is anonymous in Turnitin or not. 

However, there is a slight difference in how Moodle and Turnitin handle the release of student's identities and grades. In Turnitin this happens simultaneously but other restrictions on grades being revealed could be in place in Moodle. Therefore it is possible to end up with a scenario where student's names are visible in Moodle but not in Turnitin.

**Comment by jmcgettrick** [comment]
Closing as known issues have been moved to the wiki.

https://github.com/turnitin/moodle-plagiarism_turnitin/wiki/Known-Issues
