### ISSUE TITLE
Only the submitting student can view the Originality Report in the Turnitin Document Viewer

### ISSUE THREAD

**Issue by davidmhatton** [turnitin/moodle-plagiarism_turnitin#33]
With Group submissions, only the submitting student will be able to view the Originality Report in the Turnitin Document Viewer. However, all members of the group will have any grades awarded through GradeMark applied to them and they will all be able to see the Originality Score in the Moodle Assignment inbox.

**Comment by jmcgettrick** [comment]
Closing as known issues have been moved to the wiki.

https://github.com/turnitin/moodle-plagiarism_turnitin/wiki/Known-Issues
