### ISSUE TITLE
Latest release issue on queue cron

### ISSUE THREAD

**Issue by Syxton** [turnitin/moodle-plagiarism_turnitin#337]
Execute scheduled task: Send Queued Files from the Turnitin Plagiarism Plugin (plagiarism_turnitin\task\send_submissions)
... started 10:14:00. Current memory use 8.3MB.

- Coding problem: $PAGE->context was not set. You may have forgotten to call require_login() or $PAGE->set_context(). The page may not display correctly as a result
- line 493 of \lib\pagelib.php: call to debugging()
- line 820 of \lib\pagelib.php: call to moodle_page->magic_get_context()
- line 1432 of \lib\weblib.php: call to moodle_page->__get()
- line 5865 of \lib\moodlelib.php: call to format_string()
- line 94 of \message\output\email\message_output_email.php: call to email_to_user()
- line 150 of \lib\classes\message\manager.php: call to message_output_email->send_message()
- line 112 of \lib\classes\message\manager.php: call to core\message\manager::send_message_to_processors()
- line 296 of \lib\messagelib.php: call to core\message\manager::send_message()
- line 60 of \plagiarism\turnitin\classes\digitalreceipt\pp_receipt_message.php: call to message_send()
- line 3014 of \plagiarism\turnitin\lib.php: call to pp_receipt_message->send_message()
- line 42 of \plagiarism\turnitin\classes\task\send_submissions.php: call to plagiarism_turnitin_send_queued_submissions()
- line 105 of \lib\cronlib.php: call to plagiarism_turnitin\task\send_submissions->execute()
- line 297 of \lib\cronlib.php: call to cron_run_inner_scheduled_task()
- line 91 of \admin\tool\task\schedule_task.php: call to cron_run_single_task()

**Comment by dwinn** [comment]
Hi @Syxton,

This is not related to the latest release. I have seen this before and it happens when you have the plugin set up to send digital receipts by email but don't have SMTP configured in Moodle to send them.

**Comment by Syxton** [comment]
ok, closing

**Comment by dwinn** [comment]
For reference, you can configure these settings in:

 Site administration / ▶︎ Plugins / ▶︎ Message outputs / ▶︎ Default message outputs
