### ISSUE TITLE
Turnitin class/course length is currently restricted to 7 years

### ISSUE THREAD

**Issue by davidmhatton** [turnitin/moodle-plagiarism_turnitin#34]
The length of a class/course in Turnitin is currently restricted to 7 years. This isn't specific to Moodle and is an issue that is being reviewed, please contact Product Support if this causes any problems or you have any questions.

**Comment by jmcgettrick** [comment]
Closing as known issues have been moved to the wiki.

https://github.com/turnitin/moodle-plagiarism_turnitin/wiki/Known-Issues
