### ISSUE TITLE
Moodle assignment type - only one file sent to Turnitin

### ISSUE THREAD

**Issue by andrewrowatt-masseyuni** [turnitin/moodle-plagiarism_turnitin#341]
Hi All,

We have recently installed the latest version of the Turnitin plugin (2018062601).  

A problem has emerged for assignments where the student can submit multiple files:  only *one* of the files is being sent to Turnitin.   Other files do not have a Turnitin status (queued or ID etc).  

If the student adds another file to the submission the previous file sent to Turnitin is resent while the new file does not get sent.

This process was working up until the upgrade.

Help!

Thanks,
    Andrew

**Comment by andrewrowatt-masseyuni** [comment]
![teacher view - 2018-07-18_12-46-00](https://user-images.githubusercontent.com/5333879/42853414-5e99728c-8a8a-11e8-90f2-47a237abdbf5.png)
![student view - 2018-07-18_12-45-20](https://user-images.githubusercontent.com/5333879/42853415-5ec5dc32-8a8a-11e8-8236-f54fe195d917.png)

**Comment by rayhinton** [comment]
I am experiencing the same thing. Running Moodle 3.4.4+ (Build: 20180720), with mod_turnitintooltwo 2018052301 and plagiarism_turnitin 2018062601. 

I wonder, is this somehow related to [Resubmissions now overwrite the previous submission](https://github.com/turnitin/moodle-plagiarism_turnitin/blob/master/CHANGELOG.md#resubmissions-now-overwrite-the-previous-submission)?

As another data point, I looked at the same assignment from an earlier version of the same course, and submissions with multiple files still show all of the TII scores. I looked in the database, and I do not see any TII scores for files that are missing them. This is all to say, this is not a problem where the file is submitted and properly processed by TII, but the score is never displayed in Moodle (like in #291). The file is never processed by TII.

**Comment by rayhinton** [comment]
@andrewrowatt-masseyuni Update from Turnitin Support: 
>The assignment workflow you are describing is not available within PP.  You will need to use TT in order to successfully a multiple submission assignment.

That sounds like a feature has changed from previous versions of the plagiarism plugin. Could the developers comment on this? I am confused! 😛

**Comment by Lottie2605** [comment]
@andrewrowatt-masseyuni @rayhinton 
Hi Andrew and Ray, 
This has been identified as our engineers as a bug and we are currently working on a fix to this issue to be included in a future release of the plug-in. 
I apologise for any inconvenience this is causing and can assure you that this is currently in the hands of our engineers. 

Charlotte Spinks 
Turnitin Product Support

**Comment by rayhinton** [comment]
Aha, that sounds much better! I look forward to the updated version of the plugin.

**Comment by dwinn** [comment]
Hi @andrewrowatt-masseyuni and @rayhinton 

This has been fixed in the latest release v2018082802. Please note you will also have to update Moodle Direct V2 to v2018082801 at the same time as the release is dependent on it.
