### ISSUE TITLE
Email address changes will not be reflected in Turnitin

### ISSUE THREAD

**Issue by davidmhatton** [turnitin/moodle-plagiarism_turnitin#35]
If a user's email address is changed in Moodle, this will not reflect in Turnitin. If the user is unlinked and then the email address is changed a new Turnitin user account will be created.

**Comment by jmcgettrick** [comment]
Closing as known issues have been moved to the wiki.

https://github.com/turnitin/moodle-plagiarism_turnitin/wiki/Known-Issues
