### ISSUE TITLE
CRITICAL BUG: jquery turnitintooltwo file incorrectly referenced

### ISSUE THREAD

**Issue by rolandsherwood2** [turnitin/moodle-plagiarism_turnitin#384]
Please update line 554 of /turnitin/lib.php so that it references the correctly titled javascript file located under /turnitintooltwo/jquery (in version 2018102601) - without which new users are not able to accept Turnitin's EULA. Line 554 should now reference turnitintooltwo-2018102601.min.js NOT turnitintooltwo-2018082301.min.js.

**Comment by dwinn** [comment]
Hi @rolandsherwood2,

Thank you for the bug report. This is an oversight we made when releasing V2 on Friday. We are currently preparing a PP release with the fix - which should be available later today.

**Comment by dwinn** [comment]
We have just released v2018102901 with this fix, please update PP to this version.
