### ISSUE TITLE
Privacy implementation doesn't work correctly

### ISSUE THREAD

**Issue by micaherne** [turnitin/moodle-plagiarism_turnitin#394]
There are a couple of issues in the privacy implementation that cause it not to work properly.

First, the get_contexts_for_userid() method isn't joining the course modules table to the turnitin files table correctly, so it's returning a list of contexts unrelated to the given user. Worryingly, there's a unit test for this that seems to have shown that the implementation is broken, that has been hacked to pass with the buggy implementation.

Second, the delete_plagiarism_for_user() method doesn't take account of the context given and deletes all records for the user.

**Comment by dwinn** [comment]
Hi @micaherne,

Thank you for the bug report and the pull requests. I agree it is not good if the unit test is passing when it shouldn't be. We will look into testing these fixes you've made and make a release in the near future.

**Comment by jmcgettrick** [comment]
I've tested and merged the linked PRs.
