### ISSUE TITLE
_cron() function will be deprecated in 3.7

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-plagiarism_turnitin#415]
Hey guys - just an FYI - the _cron() function is going to be deprecated in 3.7 - plagiarism plugins should implement their own local tasks.
more info:
https://tracker.moodle.org/browse/MDL-65051

**Comment by dwinn** [comment]
Hi Dan, thanks for the heads up. I think we are already covered for this plugin as we made the switch to scheduled tasks around 3.1 back when the other plagiarism cron tasks were deprecated.

**Comment by danmarsden** [comment]
looks like you have a mix of normal tasks and the old "cron" function in your lib.php class. :-)

**Comment by dwinn** [comment]
Yeah I see what you mean. It looks like a leftover from when we supported really old versions of Moodle which didn't have the tasks. Our update report scores task calls the `cron` method, we could refactor this to not do so and then remove the cron method. I'll make a ticket on our end.

**Comment by jmcgettrick** [comment]
Thanks Dan, we'll have this removed from our next release: #443

**Comment by jmcgettrick** [comment]
Closing as this was released.
