### ISSUE TITLE
Group separation not honored in Feedback studio

### ISSUE THREAD

**Issue by moodleulpgc** [turnitin/moodle-plagiarism_turnitin#418]
Hi:
Teachers may access to several reports from feedback studio header. There is a menu there allowing to access to all reports for files submitted on the assign instance.

Moodle has a group feature. When in "Separate Groups", a teacher without "accessallgroups" capability may see only the submissions of students than happens to be members of the same group as the teacher. 

When an assign instance is configured in SEPARATE GROUPS, an user with teacher role (nor editingteacher) and without "accessallgroups" capability see in moodle only the submissions of their students (the same group) BUT, when the teacher clicks on the % to open the report on Feedback Studiio, the menu theer in the header allow to access ALL submissions by all students in OTHER groups.

This is a violation of privacy, it may be a showstopper in our University.

**Comment by jmcgettrick** [comment]
Hi ,we try and support this as best we can in the Plagiarism Plugin but unfortunately we are limited by the fact that group functionality is not available in Turnitin Feedback Studio.
