### ISSUE TITLE
cron update task processes the same files each time

### ISSUE THREAD

**Issue by Syxton** [turnitin/moodle-plagiarism_turnitin#420]
We are running Moodle 3.5. We have the most recent Turnitin release for the plagiarism plugin. When we run the "Update Report Scores for Turnitin" scheduled task, we receive "File updated: xxxxxx" 128 times. However, the file numbers are the same each time. They aren't in the same order, but they are the exact same 128 numbers.

**Comment by Syxton** [comment]
[same numbers each time.xlsx](https://github.com/turnitin/moodle-plagiarism_turnitin/files/2996403/same.numbers.each.time.xlsx)

[export.txt](https://github.com/turnitin/moodle-plagiarism_turnitin/files/2996405/export.txt)

The .xlsx file includes the numbers given in two sequential runs of the update task.  I then sorted the columns and found that they were the same numbers each time, just in a different order.  The export is the corresponding rows in the plaigarism_files table.

**Comment by Syxton** [comment]
I don't fully understand why these files are still being processed, however I do know that these date from 2015-today.  So it seems that little by little these files were being "reprocessed" along with new files, but now the build up is so great that the only files being processed are these files that should not be.

**Comment by Syxton** [comment]
![example](https://user-images.githubusercontent.com/989354/54823316-d504df00-4c7d-11e9-8bcb-c03a99cb679e.png)
This is one of the example files viewed in the course.  Nothing special stands out as to why this is failing.  This is id: 52557 from the files listed above

**Comment by CharlotteSpinks** [comment]
Hi @Syxton 
Are you able to please reach out to our support team at tiisupport@turnitin.com to report this issue, so we are able to carry out a thorough investigation into this issue you you. 
Thanks
Charlotte

**Comment by Syxton** [comment]
@CharlotteSpinks Turnitin Help Desk Case #00844041 - 81460

**Comment by jmcgettrick** [comment]
Closing as the corresponding Turnitin support case has been closed
