### ISSUE TITLE
Extraneous notifications while creating Forum posts

### ISSUE THREAD

**Issue by rayhinton** [turnitin/moodle-plagiarism_turnitin#421]
Hello Turnitin folks,

I was very excited to see this note in the recent CHANGELOG, since I thought it would solve a problem I have reported before.

[Forum users can use Turnitin without seeing extraneous notifications](https://github.com/turnitin/moodle-plagiarism_turnitin/blob/master/CHANGELOG.md#forum-users-can-use-turnitin-without-seeing-extraneous-notifications)

However, I still seem to get the message, so I will report this in case either: it is a separate error, or, the implemented fix is not working as intended.

Moodle 3.5.5+ (Build: 20190322)
Turnitin Assignment 2, mod_turnitintooltwo, 2019012401
Turnitin plagiarism plugin, plagiarism_turnitin, 2019031301

**Observed Behavior:** when a student writes a forum post to a forum where they previously made a submission (i.e. they are writing their >=2nd post), they are shown a message that says:

>You have already submitted a paper to this assignment and a Similarity Report was generated for your submission. If you choose to resubmit your paper, your earlier submission will be replaced and a new report will be generated. After 3 resubmissions, you will need to wait 24 hours after a resubmission to see a new Similarity Report.

**Expected behavior:** Forums are places where students tend to make many posts. Therefore, it is confusing to show them a message that says something about "already submitted" and "resubmit your paper". Further, the message uses the word "assignment", which does not seem correct in the context of writing a forum post. I would expect that no such message would be shown to users while they are posting.

Here are some things I thought of:
- Theme: the behavior is the same in our custom theme, and Clean theme
- we have been doing testing in a forum that already existed before the patch was applied. Perhaps this behavior would not exist if I created a brand new forum?
- I only recently applied this version upgrade to our Moodle environment and the plugins. For full disclosure, I have not recently purged any caches, and I am not sure if that would affect this behavior.

Anyway, I thought I would check with you folks before I pursued those other testing options. Please let me know if I can help clarify or describe this further.

![image](https://user-images.githubusercontent.com/7245513/55112200-632ff980-50b2-11e9-8880-7bf6c4b1cb2c.png)

**Comment by rayhinton** [comment]
In the meantime, we are planning on modifying the language string for that message (Site administration > Language > Language customization, and find `reportgenspeed_resubmission`).

**Comment by dwinn** [comment]
Hi @rayhinton,

Thank you for making us aware that this is still an issue. We have looked into this and I apologise, this feature was planned for a future release and was mistakenly included in the release notes. We have removed this from the release notes on help.turnitin.com and will continue to enhance this in future.

David.

**Comment by rayhinton** [comment]
Thanks @dwinn! That's good to know. I thought I misunderstood the CHANGELOG or had something set up wrong. I am glad to hear that this is in your queue to fix.

**Comment by dwinn** [comment]
Hi @rayhinton,

I can now confirm that this has been released in v2019050201.

**Comment by rayhinton** [comment]
That's great, thank you!
