### ISSUE TITLE
cannot install on Moodle 3.6.2+ (Build: 20190201)

### ISSUE THREAD

**Issue by webers-technikum-wien** [turnitin/moodle-plagiarism_turnitin#422]
I downloaded the latest version (3.1+ (2019031301)) from the Moodle plugin directory, however, I am not able to install it at all.

As soon as I put the "turnitin" folder into my Moodle's "plagiarism" subfolder, the site only returns http error 500 when trying to access it.

It is so broken that I cannot even provide any additional error codes, since it completely breaks my site...

**Comment by dwinn** [comment]
Hi @webers-technikum-wien,

Which version did you upgrade from?

Are you able to turn debugging on and then place the Turnitin folder into the directory? Sometimes that gives more information as to what the 500 error is.

David.

**Comment by webers-technikum-wien** [comment]
i did not upgrade at all, i did a fresh install of the plugin

indeed, debugging gave me this:

> Warning: require_once(/var/www/moodle/mod/turnitintooltwo/lib.php): failed to open stream: No such file or directory in /var/www/moodle/plagiarism/turnitin/lib.php on line 73
> 
> Fatal error: require_once(): Failed opening required '/var/www/moodle/mod/turnitintooltwo/lib.php' (include_path='/var/www/moodle/lib/pear:.:/usr/share/php') in /var/www/moodle/plagiarism/turnitin/lib.php on line 73

so obviously, I somehow ended up installing the wrong version of turnitintool

so i uninstalled turnitintool and installed the latest version of turnitintooltwo

then i installed the turnitin plagiarism plugin again - while installing i got another 500 error, but i was not able to replicate it, and on 2nd try it worked.

even though it was clearly my fault I would advise implementing some error checking into this plugin, so that it does not even attempt to install when turnitintooltwo is not installed

**Comment by dwinn** [comment]
Hi @webers-technikum-wien,

Thanks for the update, I am glad you managed to get the plugin installed. We are currently working on a version of the Plagiarism Plugin which does not require installation of Moodle Direct V2 (turnitintooltwo) which will prevent this kind of thing from happening.
