### ISSUE TITLE
Issues found in the latest bulk turnitin update for Moodle v3.6

### ISSUE THREAD

**Issue by sebasgraciavalderrama** [turnitin/moodle-plagiarism_turnitin#437]
Hey Turnitin team,
My name is Sebastian and I am a developer for Blackboard – Open LMS team.
I found some issues in the latest community bulk update for Moodle v3.6

These are the version number of the components updated:
_plagiarism_turnitin-2-2019050201_
_mod_turnitintooltwo-2-2019050101_
_block_turnitin-1-2018121801_

In the update process I encountered the following errors:

In the file **/moodle/plagiarism/turnitin/db/upgrade.php**

**1.**  Missing savepoint sentence
_Possible workaround:_
Add the following line of code inside all _if($oldversion < xxxzzzyyy)_ blocks:
`upgrade_plugin_savepoint(true, xxxzzzyyy, ‘plagiarism’, ‘turnitin’);`
**2.**  Wrong order in versions: 2017013101 and 2017012601  in the file _/moodle/plagiarism/turnitin/db/upgrade.php_ 
**3.** In the path _/moodle/plagiarism/turnitin/tests/behat/_ the following behat tests are failing: 
• eula.feaure
• assignment_multiple_files.feature
• installed.feature
• assignment.feature   
• workshop.feature

In the step: And I navigate to “Plugins > Plagiarism > Turnitin” error says: “Not found on the page not found (Behat\Mink\Exception\ElementNotFoundException)”. In addition to this, the feature of the tests is being used in other tests, changing it fixes this.

• rubric.feature is empty

**4.**  Error while trying to create tables ‘plagiarism_turnitin_users’ and ‘plagiarism_turnitin_courses’
_Possible workaround:_
In the creation of the tables, set the field ‘_notnull_’ to ‘**true**’. Do this from upgrade.php file and not install.xml file, unless further changes need to be made.

**5.** In the file _/moodle/plagiarism/turnitin/classes/turnitin_user_class_test.php_ and _/moodle/plagiarism/turnitin/generator/lib.php_
The name of the **class test_lib** is already being used
_Possible workaround:_
Change the name of the class.

If you have any questions or concerns please feel free to reach me at sebastian.gracia@blackboard.com :)

**Comment by aspark21** [comment]
+1 on point - that leads to a PHP fatal error when we run our PHPUnit tests

**Comment by mikehas** [comment]
+2 on point 5. This is breaking our current build process.

**Comment by CharlotteSpinks** [comment]
Hi @sebasgraciavalderrama, thank you for your detail around these issues, we have managed to resolve point 1, 2 and 5, and are currently working on point 3. These changes will be out in the near future. 

With regards to point 4, are you able to provide further detail on this? We have testing multiple times on mysql and MSSQL, and are not able to recreate this error. Could you please provide steps to recreate this?

**Comment by mikehas** [comment]
@CharlotteSpinks I'm interested in point 5, making sure the php unit tests pass. I have a ticket open with Turnitin. Has this fix been pulled into the master branch yet?

**Comment by CharlotteSpinks** [comment]
Hi @mikehas the fix is not yet available on master, but we are planning to do a release within the next week so you will have this soon.
@sebasgraciavalderrama Thanks for the update.

**Comment by CharlotteSpinks** [comment]
Hi @mikehas, the PP release has now gone out, and you will be able to upgrade your plugin to include these fixes. 
Thanks.

**Comment by sebasgraciavalderrama** [comment]
Hey @CharlotteSpinks do you know when will it be ready from https://moodle.org/plugins/ ?

**Comment by sebasgraciavalderrama** [comment]
@CharlotteSpinks Thanks, I am doing the update process, I'll let you know if anything comes up. In the meantime, may I suggest you guys implementing the user list provider. Take a look into the following information:

- [Retrieving the users in a context](https://docs.moodle.org/dev/Privacy_API#Retrieving_the_users_in_a_context)

- [Delete personal information for several users in a specific context](https://docs.moodle.org/dev/Privacy_API#Delete_personal_information_for_several_users_in_a_specific_context)
 
Have a great day.
