### ISSUE TITLE
plagiarism_turnitin_users missing from privacy class causing unit test failures.

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-plagiarism_turnitin#438]
I'm seeing Unit test errors due to the new plagiarism_users table being missing from the privacy api class:

1) provider_testcase::test_table_coverage
The following tables with user fields must be covered with metadata providers: 
  - plagiarism_turnitin_users (userid)

/var/www/html/privacy/tests/provider_test.php:315
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

**Comment by DrCuriosity** [comment]
I'm running into this problem too, on another upgrade project.

A `$collection->add_database_table()` for plagiarism_turnitin_users would handle the coverage part.

Unfortunately it would need to have some `privacy:metadata:plagiarism_turnitin_users:` strings localised in all available languages, and I'm not equipped to do sufficient translation to contribute a PR for it, I'm afraid.

**Comment by yao9394** [comment]
Hi there,
Could anyone please review this PR #467 ? 
Thank you

John Yao

**Comment by jmcgettrick** [comment]
Closing issue as PR has been merged. Thanks all.

**Comment by yao9394** [comment]
Hi @jmcgettrick 

May I know how long would this fix be merged into master? 

Thanks
