### ISSUE TITLE
Log enhancement: "Aborted Cron call because of active task mode"

### ISSUE THREAD

**Issue by zaddok** [turnitin/moodle-plagiarism_turnitin#440]
Our Moodle cron task is currently returning the following:

```
Processing cron function for plagiarism_plugin_turnitin...... started 15:38:48. Current memory use 28.8MB.
[Turnitin Plagiarism Plugin] Aborted Cron call because of active task mode
... used 0 dbqueries
... used 0.0083880424499512 seconds
```

The text of this log message doesn't reveal anything useful. What is "active task mode"? Is it bad that this is occurring? Should something be done about it?  Recommend the text of this log message is improved.

_By the way, could this be the cause for turniting not running for all of our moodle assignments? (Some assignments don't appear in the turnitin website, and consequently no assignments have been uploaded)_

**Comment by jmcgettrick** [comment]
Hi @zaddok - we're actually removing the message in #443. 

It was meant to show that the cron method shouldn't be used as it should all be done by scheduled tasks. I can see that it comes across as a bad thing but the functionality called by the method would be getting called anyway, plus the cron method is being deprecated.

**Comment by jmcgettrick** [comment]
Closing as #443 has been merged and released
