### ISSUE TITLE
mod_turnitintwo and plagiarism_turnitin declare same class

### ISSUE THREAD

**Issue by amandadoughty** [turnitin/moodle-plagiarism_turnitin#442]
PHP Fatal error: Cannot declare class test_lib, because the name is already in use in .../moodle/plagiarism/turnitin/tests/generator/lib.php on line 80

**Comment by jmcgettrick** [comment]
Hey @amandadoughty this has been fixed in #446

**Comment by micaherne** [comment]
It would be good to turn these classes into actual generators or remove them from generator/lib.php too.

**Comment by mudrd8mz** [comment]
We've hit this as well, thanks for fixing this.

**Comment by CharlotteSpinks** [comment]
Fixed in new release. Version 2019060601.
