### ISSUE TITLE
Database upgrades: issues with "smart" quotes

### ISSUE THREAD

**Issue by DrCuriosity** [turnitin/moodle-plagiarism_turnitin#452]
A recent change to `upgrade.php` was made using "smart" quote characters, converting single quotes into left-single-quote/right-single-quote characters on either side of the string. PHP is seeing `‘turnitin’` and treating it as an undefined constant, effectively turning it into a `"‘turnitin’"` string literal.

I discovered this when it broke my upgrade process, as the plugin manager is now looking for a `‘plagiarism’_‘turnitin’` module, and not finding that on disk.

**Comment by dwinn** [comment]
Hi @DrCuriosity,

Thank you for the report. We are looking into this and will change these to normal quote characters. We had no problems upgrading the plugin when we tested this but from what I can see it would only affect people upgrading from versions before 2016091402 as the upgrade won't get into these code blocks on newer versions.

Would you be able to confirm which version you are attempting to upgrade from?

David.

**Comment by DrCuriosity** [comment]
Thanks! I'm upgrading a client's old Moodle 3.1 site. I don't have an exact version on the plugin, but can get that for you tomorrow (in ~10 hours) if needed. I suspect it's a mid- to late-2015 model. Perhaps not the most common of cases, yet I've tripped it nonetheless :-)

Looking at commit 2600320ca542bad5906158d0e60cab732ef18934, it looks like the `2016011101`, `2016011104` and `2016091402` save points are those affected.

**Comment by dwinn** [comment]
Yeah this is most likely what has happened (upgrading from very old version), and how we've missed it in testing. We will get this fixed. We've made fix #453 for it but it will require a release to go out for everyone.

David.

**Comment by dwinn** [comment]
Hi @DrCuriosity,

This has now been fixed in release v2019062501.

**Comment by DrCuriosity** [comment]
Excellent, thank you very much for the quick turnaround!
