### ISSUE TITLE
get_pseudo_lastname() function logic incorrect

### ISSUE THREAD

**Issue by pauldamiani** [turnitin/moodle-plagiarism_turnitin#461]
Hi,

I've come across an issue where the function that generates the pseudo last name will crash out if the plugin is set to use a custom profile field which has not been assigned to the user yet.
It will never try to insert the record into the user_info_data as due to the logic $userinfoob->data will always have a value.
Also the variable $userinfo needs to be changed to $userinfoob otherwise the new UID will never be updated.

I have made a pull request with the fixes here: https://github.com/turnitin/moodle-plagiarism_turnitin/pull/460

**Comment by dwinn** [comment]
Hi @pauldamiani,

Thanks for highlighting this issue and making a pull request. We will merge and test this.
