### ISSUE TITLE
 "continue" targeting switch is equivalent to "break"

### ISSUE THREAD

**Issue by christos312** [turnitin/moodle-plagiarism_turnitin#465]
Hello, we are getting the following error after upgrading Moodle to 3.7 and the plagiarism_turnitin plugin to version 2019062501

```
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /moodle/plagiarism/turnitin/lib.php on line 2912
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in moodle/plagiarism/turnitin/lib.php on line 2925
```

**Comment by dwinn** [comment]
Hi @christos312,

Thanks for the report, we will get this looked at.

**Comment by christos312** [comment]
@dwinn any update on this? Our logs is full of this Warning.

This is also happening while running the cron over CLI, while running automated backups over CLI and while we are restoring courses into Moodle.

**Comment by dwinn** [comment]
@christos312,

This has been fixed in our develop branch and will be released in the next version.

If you're comfortable making a change you could apply the patch here https://github.com/turnitin/moodle-plagiarism_turnitin/pull/473

**Comment by christos312** [comment]
@dwinn thank you, I will keep an eye for the update. I will close the issue :)
