### ISSUE TITLE
Submissions through the mobile app break due to (no) EULA.

### ISSUE THREAD

**Issue by thepurpleblob** [turnitin/moodle-plagiarism_turnitin#475]
It's possible to submit Assignments to Turnitin via the plagiarism plugin and the Mobile App.

However, the javascript that's injected to ask students to accept the EULA doesn't work. As far as students are concerned the Turnitin submission just doesn't work. Worse, they get the message that the EULA hasn't been signed but there's not even a working link to sign it. 

This is a bit of a disaster. First time submissions through the app simply do not work.

**Comment by rayhinton** [comment]
Thank you for reporting this, it helped me figure out what was going on while I was investigating #499. Here's hoping we get a little light shed on these issues. 😄

**Comment by maheshkumaraku** [comment]
I have been facing the same issue, is there any work on this done?

**Comment by maheshkumaraku** [comment]
This literally makes Turnitin unusable in the Moodle App - any progress on this?

**Comment by thepurpleblob** [comment]
We disabled Assignments through the app (which you can do). @maheshkumaraku, as you say, it completely breaks Assignments with Turnitin enabled.

**Comment by maheshkumaraku** [comment]
I know, but it would have been a great thing if Turnitin worked with Assignment in app. @thepurpleblob

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
