### ISSUE TITLE
Turnitin submissions not visible

### ISSUE THREAD

**Issue by joey-murison** [turnitin/moodle-plagiarism_turnitin#487]
We (with our partners at Coventry University) have identified a bug which occurs and causes files that were successfully submitted to revert to a resubmit status. This then causes significant issue moving forward in that the submission is deemed already submitted (due to some entries in the DB tables) but queued for resubmission also (according to other tables in the DB). The system fails to deal with this issue.

We have completed some extensive investigations and believe the cause to be as follows.

We think we have found the bug that's causing this by carrying out the following process flow:

1. When TII is unable to update a similiarityscore for a submission, while running the update_reports cron (unable to update it at a random point in time, but could have been able to update it before as the update_reports cron task runs though all successful submissions while their duedate is still in the future) it updates the submission with:
$plagiarismfile->statuscode = 'error';
$plagiarismfile->errorcode = 13;

2. When the submissions are displayed in the grading report https://cumoodle.coventry.ac.uk/mod/assign/vi ... id=2407775&action=grading , the submissions with statuscode == 'error' and errorcode = 13 are displayed as successful ( function get_links() in lib.php, line 912)

3. When a tutor adds the feedback (with a grade), the 'update_submission' function is called which updates the submission with:
$plagiarismfile->errorcode = null;
$plagiarismfile->errormsg = null;

4. When the submissions are displayed, the submissions with statuscode == 'error' (without errorcode = 13) are displayed as failed ( function get_links() in lib.php, line 1076)

**Comment by dwinn** [comment]
Hi @joey-murison,

Thank you for the report. I have been able to reproduce this problem and can confirm it is a bug. We will get this fixed.

**Comment by kmoouni** [comment]
Excellent - any word on when this is planned  for inclusion in a release?

**Comment by jmcgettrick** [comment]
We're hoping to do a release soon, within a month anyway

**Comment by dwinn** [comment]
Hi @kmoouni,

This has been fixed and released in v2019121701. Please update the plugin when you are able to.
