### ISSUE TITLE
SoapClass Not Found - Moodle 3.6.8

### ISSUE THREAD

**Issue by demsley** [turnitin/moodle-plagiarism_turnitin#498]
I cannot seem to install this on Moodle 3.6 as I get the error as below:

![image](https://user-images.githubusercontent.com/5968088/73454513-284bc180-4366-11ea-9138-4089380da8c0.png)

**Comment by jmcgettrick** [comment]
You'll need to enable the php_soap.dll extension in your php.ini

**Comment by demsley** [comment]
> 
> 
> You'll need to enable the php_soap.dll extension in your php.ini
Spot on, thank you jmcgettrick.
