### ISSUE TITLE
Users not prompted to accept EULA when using Forum inline editing feature

### ISSUE THREAD

**Issue by rayhinton** [turnitin/moodle-plagiarism_turnitin#499]
Hello Turnitin,

**Observed behavior:** if a user writes a post with the new Moodle Forum inline editing feature, then they are never shown the TII EULA during the writing process.

**Expectation:** new users should be prompted to accept the Turnitin End User License Agreement when they are making their first forum post.

**Consequences:** it is more likely that a user can write multiple forum posts before realizing they need to accept the TII EULA, which means that their initial posts will not be processed and receive similarity scores.

**Proposed solution:** incorporate EULA prompt into the inline editor.

**Details:**

Moodle 3.7.3+ (Build: 20200103)
Turnitin plagiarisim plugin version 3.1+, 2019121701
Boost theme (and custom Boost-based themes)

Moodle version 3.7 introduced the Forum inline editing feature (I've also been calling it "Quick post" or "Quick reply"). Please see:

https://docs.moodle.org/37/en/Using_Forum#Replying_to_discussions
https://docs.moodle.org/37/en/New_features

When new users are starting their first action in an activity where the Turnitin Plagiarism plugin is enabled, they are usually prompted to accept the TII EULA. However, with the Forum inline editor, the experience is different. The EULA prompt is not shown to users if they are using the inline editor.

Of course, it is still shown to people in the usual way if they click the "Advanced" link to view all the posting options. Further, they can also accept the EULA by going to one of their completed posts, and finding the prompt there.

So, there is nothing preventing the user from accepting the EULA *eventually*. However, the path to accepting the prompt feels substantially different with the inline editor. Before, users were shown the EULA prompt very explicitly, before they could even start typing anything in their first forum post. Now, they need to seek out the EULA prompt.

Because of this, we have received a significant increase in users who are experiencing confusion with accepting the EULA. We are doing our best to guide them through it, and indeed give them instructions before they encounter it.

This is a problem because users are more likely to make multiple posts before realizing that they have not accepted the TII EULA. Since there is not a convenient way to resubmit posts for Turnitin processing when this happens, this means that a user could end up having several posts that never get processed by Turnitin.

Can the EULA prompt be incorporated into the inline editor? Conceptually, that seems like the most straightforward solution. I attached a couple examples I mocked up (apologies for my poor editing skills).

Of course, I imagine that this kind of issue could possibly require changes in the Moodle Forum module. I would be happy to start a Moodle Tracker issue, if that is the case.

As a bonus, this could possibly solve issue 475: https://github.com/turnitin/moodle-plagiarism_turnitin/issues/475.

Please let me know if I can provide any more information.

![quick post with EULA mock up](https://user-images.githubusercontent.com/7245513/73573903-7209da00-4442-11ea-8e3b-6cd0287371ef.jpeg)
![quick reply with EULA mock up](https://user-images.githubusercontent.com/7245513/73573904-7209da00-4442-11ea-8d93-264a6d1fbbfd.jpg)

**Comment by rlorenzo** [comment]
Just reporting that we ran into this issue when we upgraded from Moodle 3.5 to 3.9 with the new forum system. Hope to see this resolved sometime soon.

**Comment by CharlotteSpinks** [comment]
Thanks for the report, I'll look into this.

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.

**Comment by TB529** [comment]
Hi All, just come across this issue in 4.3 and it seems there is no resolve and we are to force the user to accept the EULA via a separate assignment. We're on the latest version of TII, so disappointed that this is still an issue two years after this initial post. Anyone else still having this issue and being advised the same?
