### ISSUE TITLE
Lang string does not exist plagiarism_turnitin/[[classcreationerror]]

### ISSUE THREAD

**Issue by agrowe** [turnitin/moodle-plagiarism_turnitin#508]
Version: v2019121701

Invalid get_string() identifier: 'classcreationerror' or component 'plagiarism_turnitin'. Perhaps you are missing $string['classcreationerror'] = ''; in /var/www/staging-taylorscollege-lms.au.studygroup.com/plagiarism/turnitin/lang/en/plagiarism_turnitin.php?

There is a lang string with "pp_" at the beginning but not this exact match.

**Comment by CharlotteSpinks** [comment]
Hi @agrowe Thanks for letting us know, this has been updated and will be merged soon.
