### ISSUE TITLE
Deprecation warnings in Moodle 3.9

### ISSUE THREAD

**Issue by rlorenzo** [turnitin/moodle-plagiarism_turnitin#509]
When running the latest Moodle 3.9 code we are seeing these deprecation warnings:

The setting plagiarism:turnitin_use is deprecated. Use plagiarism_turnitin:enabled instead
line 204 of /lib/plagiarismlib.php: call to debugging()
line 121 of /lib/plagiarismlib.php: call to plagiarism_load_available_plugins()
line 192 of /mod/assign/mod_form.php: call to plagiarism_get_form_elements_module()
line 218 of /lib/formslib.php: call to mod_assign_mod_form->definition()
line 130 of /course/moodleform_mod.php: call to moodleform->__construct()
line 141 of /course/modedit.php: call to moodleform_mod->__construct()

plagiarism_plugin::get_form_elements_module() is deprecated. Use plagiarism_turnitin_coursemodule_standard_elements() instead
line 131 of /lib/plagiarismlib.php: call to debugging()
line 192 of /mod/assign/mod_form.php: call to plagiarism_get_form_elements_module()
line 218 of /lib/formslib.php: call to mod_assign_mod_form->definition()
line 130 of /course/moodleform_mod.php: call to moodleform->__construct()
line 141 of /course/modedit.php: call to moodleform_mod->__construct()

See [MDL-67872](https://tracker.moodle.org/browse/MDL-67872) - deprecate and fix plagiarismlib use of config vars

**Comment by danmarsden** [comment]
this partly duplicates #448  :-)

**Comment by rlorenzo** [comment]
Closing since this is covered in another ticket.
