### ISSUE TITLE
Moodle 3.9 behat failure

### ISSUE THREAD

**Issue by aspark21** [turnitin/moodle-plagiarism_turnitin#518]
Moodle 3.9 
plagiarism_plugin v2019121701

022 Scenario: All of the selected roles can award badges # /var/www/html/badges/tests/behat/award_badge.feature:313
      And I trigger cron                                 # /var/www/html/badges/tests/behat/award_badge.feature:379
        Other backtraces found:
        line 41 of /plagiarism/turnitin/classes/turnitin_comms.class.php: call to behat_error_handler()
        line 2072 of /plagiarism/turnitin/lib.php: call to turnitin_comms-&gt;__construct()
        line 1981 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin-&gt;check_local_submission_state()
        line 2776 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin-&gt;cron_update_scores()
        line 44 of /plagiarism/turnitin/classes/task/update_reports.php: call to plagiarism_turnitin_update_reports()
        line 248 of /lib/cronlib.php: call to plagiarism_turnitin()
        line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
        line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
        line 81 of /admin/cron.php: call to cron_run()
        line 41 of /plagiarism/turnitin/classes/turnitin_comms.class.php: call to behat_error_handler()
        line 431 of /plagiarism/turnitin/lib.php: call to turnitin_comms-&gt;__construct()
        line 2789 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin-&gt;test_turnitin_connection()
        line 42 of /plagiarism/turnitin/classes/task/send_submissions.php: call to plagiarism_turnitin_send_queued_submissions()
        line 248 of /lib/cronlib.php: call to plagiarism_turnitin()
        line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
        line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
        line 81 of /admin/cron.php: call to cron_run() (Exception)

**Comment by CharlotteSpinks** [comment]
Hey @aspark21 This is now fixed in v2020070801.
