### ISSUE TITLE
Error with submissions: XML Response could not be parsed

### ISSUE THREAD

**Issue by MYGawish** [turnitin/moodle-plagiarism_turnitin#519]
Integration of turnitin plagiarism plugin with Moodle.
Although, I have installed and tested the Turnitin Moodle Direct V2 and Turnitin Plagiarism plugins successfully with the message "Moodle has successfully connected to Turnitin". There is an error which prevents any request to be carried out in Turnitin.

I face this error with submissions of **Moodle assignment** activity only. Turnitin assignment activity is working well.

The following is an example of the error:
Fault Code: responsexmlerror | File: ...\plagiarism\turnitin\vendor\Integrations\phpsdk-package\src\Response.php | Line: 45 | Message: XML Response could not be parsed | Code: 0
2020-06-21 13:40:17 +0200 (REQUEST) - User 4825 (1103458571) joined to class (25277010)
2020-06-21 13:40:19 +0200 (REQUEST) - Turnitin Assignment updated - id: 93494332
2020-06-21 13:40:20 +0200 (API_ERROR) - There was an error trying to create the submission in Turnitin

Thanks in advance

**Comment by MYGawish** [comment]
Solved!

**Comment by jmcgettrick** [comment]
Hey @MYGawish - good to hear. What was the issue?
