### ISSUE TITLE
3.9 unit test failures with plagiarism_turnitin_coursemodule_standard_elements when bigbluebutton installed.

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-plagiarism_turnitin#522]
Guess you can't rely on $formwrapper->get_current()->modulename always existing?

might be nice to handle that a bit nicer on the Turnitin side?

1) mod_bigbluebuttonbn_lib_testcase::test_bigbluebuttonbn_reset_course_form_definition
Undefined property: stdClass::$modulename

/var/www/html/plagiarism/turnitin/lib.php:2843
/var/www/html/course/moodleform_mod.php:894
/var/www/html/course/moodleform_mod.php:778
/var/www/html/mod/bigbluebuttonbn/mod_form.php:95
/var/www/html/lib/formslib.php:214
/var/www/html/course/moodleform_mod.php:130
/var/www/html/mod/bigbluebuttonbn/tests/lib_test.php:223
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit --colors "mod_bigbluebuttonbn_lib_testcase" mod/bigbluebuttonbn/tests/lib_test.php

**Comment by CharlotteSpinks** [comment]
Hey @danmarsden This is now fixed in v2020070801.
