### ISSUE TITLE
a bug - show to ‘Turnitin plagiarism plugin settings’ in assignment activity

### ISSUE THREAD

**Issue by yezi08** [turnitin/moodle-plagiarism_turnitin#527]
I just upgraded the Turnitin plugin plagiarism_turnitin 2020070801 on your Moodle system (Moodle 3.7.5) last week. And we found a terrible bug. In the setting of assignment activity, the ‘Turnitin plagiarism plugin settings’ section appears twice, as shown in the screen shot below. Moreover, teachers need to enable Turnitin in BOTH sections to successfully enable Turnitin. It is really confusing to teachers. Could you solve it as soon as possible, please?

<img width="927" alt="turnitin" src="https://user-images.githubusercontent.com/12838887/87914535-5dc6a180-caa3-11ea-9a66-0f78131578c6.png">

**Comment by jmcgettrick** [comment]
Thanks for reporting @yezi08 - see #528

**Comment by thepurpleblob** [comment]
Just a "me too". We're seeing the same thing

**Comment by thepurpleblob** [comment]
Worse - only the lower tab actually seems to work.

**Comment by thepurpleblob** [comment]
I'm assuming his isn't news to you but you seem to have tried to move the settings into function plagiarism_turnitin_coursemodule_standard_elements

However, Assignment is still calling the 'old' method for adding plagiarism settings. Turnitin is doing both of them :(

**Comment by jmcgettrick** [comment]
Thanks @thepurpleblob - yes we're going to release a patch to fix it to only show once.

**Comment by thepurpleblob** [comment]
It seems to be the $CFG->branch > 39 check that's causing the problem on my site. I'm not sure what that does? Anyway, taking out that check and it works

**Comment by CharlotteSpinks** [comment]
Hi @yezi08 @thepurpleblob This is resolved in the latest release.

**Comment by thepurpleblob** [comment]
@CharlotteSpinks if you mean the code that's currently here in Github then I beg to differ. 

It doesn't work on 3.8 (and probably 3.7) because the $CFG->branch check is wrong.

**Comment by CharlotteSpinks** [comment]
Hey @thepurpleblob Are you referring to an earlier commit? I have removed the branch check in #531 and this code is now live.

**Comment by thepurpleblob** [comment]
@CharlotteSpinks sorry - missed your update. I see now
