### ISSUE TITLE
font-awesome.php output is shown in Moodle cron out

### ISSUE THREAD

**Issue by hitteshahuja** [turnitin/moodle-plagiarism_turnitin#54]
If you look at the following pastie url you will see that in between processing forum posts for some odd reason it ouputs the css for font-awesome defined in https://github.com/turnitin/moodle-plagiarism_turnitin/commit/a30e7f845d45406f1b1bdba2cd3a0011bfd27c34 

http://pastie.org/10625705

**Comment by jmcgettrick** [comment]
Hi Hittesh, we've seen the same issue as yourself a couple of times recently and we've seen it cause a couple of small visual quirks on one assignment page. Therefore, we're going to remove font awesome from this plugin so this should only be an issue until the next release.

**Comment by hitteshahuja** [comment]
That's great. Thank you for your response.

**Comment by dwinn** [comment]
Hi @hitteshahuja, This has now been fixed and released.

**Comment by hitteshahuja** [comment]
Brill ! Thanks
