### ISSUE TITLE
Stuck on 'Status Queued'

### ISSUE THREAD

**Issue by bryson-stansfield** [turnitin/moodle-plagiarism_turnitin#540]
After upgrading to 3.9 we have been unable to get submissions made through the normal Moodle assignment to return an originality score. Papers submitted through a TurnitIn Assignment V2 activity work and return an originality score. When running the 'Send Queued files from the turnitin plagarisim plugin' scheduled task manually I get a "Cannot obtain task lock" error. I've provided api logs and activity logs through to support but have not had a resolution in 3 weeks. Any one out there experienced something similar and able to point me in the right direction?

**Comment by thepurpleblob** [comment]
Have you checked your scheduled task logs? Does the \plagiarism_turnitin\task\send_submissions task *ever* run? If not, can you kill your cron and run it manually?
