### ISSUE TITLE
Deprecated use of conditional expressions

### ISSUE THREAD

**Issue by deraadt** [turnitin/moodle-plagiarism_turnitin#543]
We were forced to upgrade to PHP 7.4.x as TurnItIn was failing to deal with non-latin characters with earlier PHP versions.

We are now seeing a deprecation warning in cron logs when a submission is being sent to TurnItIn.

`Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in C:\inetpub\wwwroot\moodle\plagiarism\turnitin\vendor\Integrations\phpsdk-package\src\Soap.php on line 284`

The submission succeeds despite this.

**Comment by jmcgettrick** [comment]
This fix is now released
