### ISSUE TITLE
Error when students try to see rubric

### ISSUE THREAD

**Issue by thepurpleblob** [turnitin/moodle-plagiarism_turnitin#558]
Following error is shown....

Exception - Argument 2 passed to has_capability() must be an instance of context, null given, called in [dirroot]/plagiarism/turnitin/ajax.php on line 162
More information about this error
×
Debug info:
Error code: generalexceptionmessage
×
Stack trace:
* line 427 of /lib/accesslib.php: TypeError thrown
* line 162 of /plagiarism/turnitin/ajax.php: call to has_capability()

Undefined variable: cm in /var/www/html/moodle/plagiarism/turnitin/ajax.php on line 160

Notice: Trying to get property of non-object in /var/www/html/moodle/plagiarism/turnitin/ajax.php on line 160
Notice: Undefined variable: cm in /var/www/html/moodle/plagiarism/turnitin/ajax.php on line 161
Notice: Trying to get property of non-object in /var/www/html/moodle/plagiarism/turnitin/ajax.php on line 161
Notice: Undefined variable: cm in /var/www/html/moodle/plagiarism/turnitin/ajax.php on line 162
Notice: Trying to get property of non-object in /var/www/html/moodle/plagiarism/turnitin/ajax.php on line 162
Notice: Undefined variable: context in /var/www/html/moodle/plagiarism/turnitin/ajax.php on line 162

**Comment by jbriggscmet** [comment]
We're getting the same error:

```
Exception - Argument 2 passed to has_capability() must be an instance of context, null given, called in [dirroot]/plagiarism/turnitin/ajax.php on line 163
```

This works on our live site, so appears to be a regression.

* Moodle version: 3.9.3 (20201109)
* `plagiarism_turnitin` plugin version: 2020072201
* `mod_turnitintooltwo` plugin version: 2020072201

**Comment by CharlotteSpinks** [comment]
Hi @jbriggscmet we appear to have fixed this here https://github.com/turnitin/moodle-plagiarism_turnitin/pull/554

**Comment by jbriggscmet** [comment]
Hi @CharlotteSpinks we've retested this issue in our test environment and it is now working as expected when using plugin version `2020113001`. It looks like the Moodle CLI upgrade scripts did not clear the Moodle caches correctly, and an outdated version of the TurnItIn JavaScript files were being served to users.

**Comment by CharlotteSpinks** [comment]
@jbriggscmet That's great, thank you for letting us know 😄
