### ISSUE TITLE
upgrade on mssql fail

### ISSUE THREAD

**Issue by jwloubser** [turnitin/moodle-plagiarism_turnitin#563]
php 7.3.11 pecl mssql drv 5.8.1 (Apache rhel7) MSSQL 
3.9.3 (BUILD: 20201109) (2020061503)

$plugin->version = 2020112601;
$plugin->release = "3.5+";
$plugin->requires = 2018051700;
$plugin->component = 'plagiarism_turnitin';
$plugin->maturity  = MATURITY_STABLE;
$plugin->cron = 0;

type y (means yes) or n (means no)
: y
-->plagiarism_turnitin
Default exception handler: column "plagiarism_turnitin_config-&gt;config_hash" cannot be modified. Dependency found with index "mdl_plagturnconf_con_uix (config_hash)" Debug: 
Error code: ddldependencyerror
* line 734 of /lib/ddl/database_manager.php: ddl_dependency_exception thrown
* line 591 of /lib/ddl/database_manager.php: call to database_manager->check_field_dependencies()
* line 609 of /lib/ddl/database_manager.php: call to database_manager->change_field_type()
* line 467 of /plagiarism/turnitin/db/upgrade.php: call to database_manager->change_field_precision()
* line 692 of /lib/upgradelib.php: call to xmldb_plagiarism_turnitin_upgrade()
* line 1917 of /lib/upgradelib.php: call to upgrade_plugins()
* line 193 of /admin/cli/upgrade.php: call to upgrade_noncore()

!!! column "plagiarism_turnitin_config-&gt;config_hash" cannot be modified. Dependency found with index "mdl_plagturnconf_con_uix (config_hash)" !!!
!! 
Error code: ddldependencyerror !!
!! Stack trace: * line 734 of /lib/ddl/database_manager.php: ddl_dependency_exception thrown
* line 591 of /lib/ddl/database_manager.php: call to database_manager-&gt;check_field_dependencies()
* line 609 of /lib/ddl/database_manager.php: call to database_manager-&gt;change_field_type()
* line 467 of /plagiarism/turnitin/db/upgrade.php: call to database_manager-&gt;change_field_precision()
* line 692 of /lib/upgradelib.php: call to xmldb_plagiarism_turnitin_upgrade()
* line 1917 of /lib/upgradelib.php: call to upgrade_plugins()
* line 193 of /admin/cli/upgrade.php: call to upgrade_noncore()

**Comment by jspicard** [comment]
Also experiencing same error on MySQL on same column and index.

Moodle Version: 3.9.3+ (Build: 20201113)
MariaDB: 10.5.8
PHP: 7.3.24
plagiarism_turnitin: 2020112601

**Comment by jmcgettrick** [comment]
https://github.com/turnitin/moodle-plagiarism_turnitin/pull/564

**Comment by jmcgettrick** [comment]
https://github.com/turnitin/moodle-plagiarism_turnitin/releases/tag/v2020113001
