### ISSUE TITLE
(re)implement "Log in to TII as teacher" link

### ISSUE THREAD

**Issue by pauln** [turnitin/moodle-plagiarism_turnitin#57]
The "Log in to TII as teacher" link which Dan Marsden's version of the plagiarism plugin (for the old TII API) adds to the assignment submissions list is/was very useful - is it possible to have this version of the plugin offer a similar link?

**Comment by jmcgettrick** [comment]
Hi Paul, I'm afraid not. We didn't implement it when we took the plugin over as it was deemed a potential security risk.

**Comment by pauln** [comment]
Hi John,
It's a shame to lose such a useful piece of functionality.
If that particular implementation was deemed to be a potential security risk, are there any plans for any other form of single sign-on between the LMS and TII?  If it's the entire concept of SSO between LMS and TII that's the issue, could it be implemented as optional functionality, disabled by default and with a warning which the LMS administrator needs to accept before enabling?

**Comment by cwestgarth** [comment]
Hey @pauln , 
Unfortunately we will not be re-introducing the login link which the Dan Marsden plugin introduced. Having said that, Turnitin are in very early stages of investigating SSO. Please do let me know if you have any further questions.

Thank you 
Caroline Westgarth
