### ISSUE TITLE
Quiz Essay question type should support scanning file attachments

### ISSUE THREAD

**Issue by aspark21** [turnitin/moodle-plagiarism_turnitin#575]
At the moment, the text of the response is scanned but file attachments are not. The filename gets appended to the text but it's not possible for the attachments to get properly scanned. This is a feature implemented by Dan Marsden which TII doesn't seem to support. I would expect separate reports for each attachment & the text area.

https://tracker.moodle.org/browse/MDL-32226?focusedCommentId=841751&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-841751

**Comment by danmarsden** [comment]
fyi - looks like you'll need to add something like
```
 $files = $qa->get_last_qt_files('attachments', $context->id);
foreach ($files as $file) {
   // Queue file for sending to Turnitin
}
```
Somewhere in this block.
https://github.com/turnitin/moodle-plagiarism_turnitin/blob/cf3952c67833d3af76133fe3038497c03b765b0c/lib.php#L2571

and then check that the get_links stuff returns the results of those files in the UI

**Comment by aspark21** [comment]
@jmcgettrick We're in need of this at relatively short notice for the upcoming exam period, too short to consider lobbying Turnitin HQ to put this into it's roadmap so we are looking to develop it for ourselves & submit MR.

I think our devs might want to have a chat with you at some point to make sure it's all done properly though.

**Comment by jmcgettrick** [comment]
Hi @aspark21 that would be great, we stopped working on the feature while waiting for it to be released in Moodle. Feel free for them to get in touch, they can get me on here or via the Moodle thread on telegram.

**Comment by jmcgettrick** [comment]
I should add, we will be picking up the feature to finish off soon!

**Comment by jmcgettrick** [comment]
Thanks @danmarsden - First pass: https://github.com/turnitin/moodle-plagiarism_turnitin/pull/579

**Comment by aspark21** [comment]
Included in v2021060801

Thanks John!
