### ISSUE TITLE
Wrong version number in version.php

### ISSUE THREAD

**Issue by micaherne** [turnitin/moodle-plagiarism_turnitin#58]
v2015040111 seems to have been released with the same version number in version.php as the previous version (2015040110). Could this be changed? Presumably it doesn't cause any functional issues, but it makes it difficult to determine what version you have installed, and also means that the latest version is showing the wrong version number in the Moodle plugin directory.

**Comment by jmcgettrick** [comment]
Hi Michael, thanks for that. I've updated it in master with https://github.com/turnitin/moodle-plagiarism_turnitin/commit/4c1426c3b6e4744a7494b71bbc6f302732a393fa.

**Comment by micaherne** [comment]
Thanks, John. Will the Moodle plugin directory be updated too?

**Comment by jmcgettrick** [comment]
I've updated that now, just so you know we're planning releasing a new version next week.
