### ISSUE TITLE
quiz handling generates a queue item per question, not just for essay questions.

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-plagiarism_turnitin#589]
When handling a quiz the event_handler function finds every question in the quiz and adds it to the queue for processing - when you have a large quiz (100 questions) this generates 100 items in the queue which massively slows down the backlog.

ideally in here:
https://github.com/turnitin/moodle-plagiarism_turnitin/blob/master/lib.php#L2565

there should be a call to: $qa->get_question()->get_type_name() and check to see if it's an essay question before adding it to the queue for processing.

**Comment by danmarsden** [comment]
I'd also suggest it might be worthwhile doing a character count on qa->get_response_summary and just ignoring it if it's under a certain count like 100 characters. (it could even be empty)

**Comment by andrewrowatt-masseyuni** [comment]
@danmarsden confirming this is a real issue for us as well - three quizzes last week generated nearly 30,000 submissions, with many complaints about delays with assignment reports soon after.  I have also raised with Turnitin Support (Case: 01831537) and asked our Account Manager to escalate.   Anything you can suggest would be appreciated - including how to increase submission throughput from Moodle to Turnitin. FYI @alexmorrisnz.

**Comment by danmarsden** [comment]
Hi @andrewrowatt-masseyuni -
Ideally under line 2565 there needs to be something like:
if ($qa->get_question()->get_type_name() == 'essay') {

Hopefully Alex can help get this into your site until Turnitin address this themselves.

**Comment by andrewrowatt-masseyuni** [comment]
Some progress @danmarsden!  Thank you for raising this issue here.

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
