### ISSUE TITLE
"pending" result after upgrade

### ISSUE THREAD

**Issue by verzog** [turnitin/moodle-plagiarism_turnitin#6]
Hi, not sure what the issue is.
Did the upgrade yesterday, Turnitin connection says "Connected to Turnitin" but no scores have been returned for the Turnitin integration since yesterday. All statuses say "Pending". and no assignments are making it to Turnitin.

We are using Moodle 2.7.8
We have installed the latest version of Moodle Direct V2 from moodle.org (2015040110)
Using the Assignment Plugin (Dan Marsden style)

The only Tii related error message is below:

\2015/10/09 14:01:07 [error] 6371#0: *15015122 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 203.35.135.171, server: learn.endeavour.edu.au, request: "GET /plagiarism/turnitin/fonts/tii-icon-webfont.eot)%20format(%22embedded-opentype%22),%20url(https://learn.endeavour.edu.au/plagiarism/turnitin/fonts/tii-icon-webfont.woff)%20format(%22woff%22),%20url(https://learn.endeavour.edu.au/plagiarism/turnitin/fonts/tii-icon-webfont.ttf)%20format(%22truetype%22),%20url(https://learn.endeavour.edu.au/plagiarism/turnitin/fonts/tii-icon-webfont.svg)%20format(%22svg%22 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "learn.endeavour.edu.au", referrer: "https://learn.endeavour.edu.au/"

Are you able to point me in a direction?

Regards,
Vernon

**Comment by amclarty** [comment]
Hi Vernon,

In v2015040109 of the plugin submissions are processed via the cron:

> Submissions workflow changed to exclusively use Moodle's cron. Functionally to instantly send files to Turnitin via AJAX removed.

See here for more information about changes: https://github.com/turnitin/moodle-plagiarism_turnitin/blob/master/CHANGELOG.md

Submissions go into the pending state on the initial subit. When the cron runs the submissions are sent to Turnitin. If successful, papers should have an id.

Can you run your cron manually (or wait until your cron runs) and let us know if your submissions are processed?

Thanks,

Alex.

**Comment by verzog** [comment]
Cheers ALex,
 This comes from the cron.
We are running cron but it’s showing the following error:
This module could not be created on Turnitin, please consult your API logs for further information
This module could not be created on Turnitin, please consult your API logs for further information
 
But then
Processing cron function for plagiarism_plugin_turnitin...... started 16:28:49. Current memory use 14.8MB.
File updated: 120314
File updated: 126571
File updated: 126913
File updated: 126362
File updated: 126646
File updated: 125030
File updated: 125191
File updated: 127446
... used 6616 dbqueries
... used 6.4357550144196 seconds
Scheduled task complete: Background processing for plagiarism plugins

Does that help?

Regards,
Vernon

**Comment by verzog** [comment]
I'm also thinking the error is occurring much earlier in the process as the "Pending" result appears immediately before the cron has had a chance to run.

**Comment by mkpelletier** [comment]
This is not the most up to date version of the plugin.  Have you considered updating?  We are using the plagiarism plugin on Moodle 2.8 and it works correctly.  The move to using cron has fixed numerous other problems.

Best Regards,

Mathieu

**Comment by verzog** [comment]
Hi Mathieu,
The version number shows 2015040110 here on github.. Think thats the same?
V

**Comment by mkpelletier** [comment]
Hello Verzog,

Yes that is the correct version, but below I saw Alex’s response: "In v2015040109 of the plugin submissions are processed via the cron.”  I now see you mentioned 2015040110 in your OP.  Sorry about that :)!

**Comment by verzog** [comment]
All good bud :)

**Comment by amclarty** [comment]
Hi Vernon,

Seems like your activity is not being created in Turnitin. Can you check your API logs after running the cron (you may need to enable logging first)? It's likely there will be an error message that'll point us in the right direction.

If this doesn't help or there is no error, I'd go ahead and raise a support ticket (https://turnitin.com/help/helpdesk.asp). Once we have your account details and other information we can investigate this for you.

Hope this helps!

All the best,

Alex.

**Comment by verzog** [comment]
Hi Alex,
I've raised a support ticket but haven't had a response since Friday night.
SO far I have:
No scores on either LMS or Turnitin.com
Turnitin tool two - Creates assignment on turnitin, does receive assignment from LMS but no scores generated. Uploading directly to the Turnitin website for that assignment/class also generates no scores.

Creating a New assignment on Turnitin does generate assignment and does generate score.

I cant attach any files to this post for some reason but have included a couple of samples below.

Could you please cast you eye over them and tell me if anything stands out?

Regards,
Vernon












------------------------------------------------------------ 2015-10-11 10:43:34 +1100 - INFO --> ------------------------------------------------------------ <?xml version="1.0" encoding="UTF-8"?> <SOAP-ENV:Envelope xmlns:SOAPENV="http://schemas.xmlsoap.org/soap/envelope/">   <SOAP-ENV:Header>     <tns:imsx_syncResponseHeaderInfo xmlns:tns="http://www.imsglobal.org/services/lis/mms2p0/wsdl11/sync/imsmms_v2 p0">       <tns:imsx_version>V1.0</tns:imsx_version>       <tns:imsx_messageIdentifier>B9F24988-6FA8-11E5-A2DEAAB49B27A949</tns:imsx_messageIdentifier>       <tns:imsx_statusInfo>         <tns:imsx_codeMajor>failure</tns:imsx_codeMajor>         <tns:imsx_severity>error</tns:imsx_severity>         <tns:imsx_messageRefIdentifier>67cd780c-373c-4909-86d5239700e585be</tns:imsx_messageRefIdentifier>         <tns:imsx_description>user_role - User already enrolled on this Class CourseSection  </tns:imsx_description>         <tns:imsx_codeMinor>           <tns:imsx_codeMinorField>             <tns:imsx_codeMinorFieldName>TargetEndSystem</tns:imsx_codeMinorFieldName>             <tns:imsx_codeMinorFieldValue>invaliddata</tns:imsx_codeMinorFieldValue>           </tns:imsx_codeMinorField>         </tns:imsx_codeMinor>       </tns:imsx_statusInfo>     </tns:imsx_syncResponseHeaderInfo>   </SOAP-ENV:Header>   <SOAP-ENV:Body>     <tns:createByProxyMembershipResponse xmlns:tns="http://www.imsglobal.org/services/lis/mms2p0/wsdl11/sync/imsmms_v2 p0"/>   </SOAP-ENV:Body> </SOAP-ENV:Envelope>  
------------------------------------------------------------ 




------------------------------------------------------------
2015-10-11 10:34:00 +1100 - INFO -->
------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Header>
    <tns:imsx_syncResponseHeaderInfo xmlns:tns="http://www.imsglobal.org/services/lis/cmsv1p0/wsdl11/sync/imscms_v1p0">
      <tns:imsx_version>V1.0</tns:imsx_version>
      <tns:imsx_messageIdentifier>63DB7462-6FA7-11E5-AD04-BF9F6219B709</tns:imsx_messageIdentifier>
      <tns:imsx_statusInfo>
        <tns:imsx_codeMajor>success</tns:imsx_codeMajor>
        <tns:imsx_severity>warning</tns:imsx_severity>
        <tns:imsx_messageRefIdentifier>45c7c6ae-84d6-4315-9c78-6c44d1804408</tns:imsx_messageRefIdentifier>
        <tns:imsx_description>No Classes were found for this account and API product.</tns:imsx_description>
        <tns:imsx_codeMinor>
          <tns:imsx_codeMinorField>
            <tns:imsx_codeMinorFieldName>TargetEndSystem</tns:imsx_codeMinorFieldName>
            <tns:imsx_codeMinorFieldValue>nosourcedids</tns:imsx_codeMinorFieldValue>
          </tns:imsx_codeMinorField>
        </tns:imsx_codeMinor>
      </tns:imsx_statusInfo>
    </tns:imsx_syncResponseHeaderInfo>
  </SOAP-ENV:Header>
  <SOAP-ENV:Body>
    <tns:discoverCourseSectionIdsResponse xmlns:tns="http://www.imsglobal.org/services/lis/cmsv1p0/wsdl11/sync/imscms_v1p0"/>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

------------------------------------------------------------

**Comment by cwestgarth** [comment]
Hi @verzog,
Do you have the case number? I will look into this for you. 
Thanks

**Comment by verzog** [comment]
Really appreciate it Caroline..#00459796
Your peeps got back to me today.. I then got a nice but rather stressed American helpdesk guy who said that someone in the UK would be looking at it tonight.

The TT2 assignments WERE generating a score when uploaded via the Tii website(and returns to the LMS).. I missed the default setting on the site.

The rest of the details are in the case.

Thanks again,
Vernon

**Comment by cwestgarth** [comment]
Hi @verzog, 
Thanks for this and no problem :). I have spoken to the UK support team with regards to your case. Please bear with us while we look into this for you, we'll be in touch via email. 

Thanks
Caroline Westgarth

**Comment by verzog** [comment]
Hi all and thanks for your help so far.
I've given up on trying to fix the plugin - Have duplicated the issue on 4 of our LMS's now (3 dev versions).

I've successfully rolled back three of them to an earlier version (2015040106) and will do it to the live version tomorrow.

The only remaining hiccup is that any assignment affected during this period (including all the files stuck at pending) have no originality score displayed. The id's are displaying and the Grademark link takes you through to the assessment where you can access the Originality Score. Can anyone tell me which table this information lives in?
Thanks again,
Vernon

**Comment by jmcgettrick** [comment]
In a post further up you mention that the cron was returning:
"This module could not be created on Turnitin, please consult your API logs for further information"
Do you still have those logs available? That says to me that the submissions haven't been sent because the assignment couldn't be created, the logs should tell us why that is the case.

**Comment by verzog** [comment]
Hi John,
I couldn't add them to my Github post due to size?? but:
http://media.endeavour.edu.au/temp/apilog_2015-10-10.txt  
http://media.endeavour.edu.au/temp/apilog_2015-10-09.txt  

Cheers,
Vernon

**Comment by jmcgettrick** [comment]
Hi Vernon,
I've had a look at your logs and it seems that your submissions were still pending because the class in Turnitin has been deleted. If you look through the logs you'll be able to see quite a few instances of "Class CourseSection not found." for the same class id.
Cheers,
John
