### ISSUE TITLE
Does not update 'grader' field in 'mdl_assignment_grades' record. 

### ISSUE THREAD

**Issue by thepurpleblob** [turnitin/moodle-plagiarism_turnitin#602]
We noticed this because we have a custom report that shows the grader. Often, if Turnitin has been used for grading there is no grader recorded.

This is one way to reproduce this but I'm quite sure that the assignment_grades records can be produced by Assignment in a number of other scenarious

- set up a test Moodle Assignment with blind marking, Turnitin and Marking Workflow
- add a few students
- Work out the correct assignment id and check the mdl_assignment_grades table for this assignment. It should be empty
- In the assignment submissions page, select all the assignments and change the marking workflow to "in marking" (can be anything but not released)
- check the table now. There should be entries for each student with grade=-1 and marker=-1
- log in as one or two test students and submit something
- wait for TII to process it
- as a Teacher go into Feedback Studio and give them a grade
- Wait for the grades to update in Moodle (refresh the submission screen)
- Check the table. For the graded items the grade has been updated but not the grader (still -1)

Analysis. 
The plagiarism plugin code checks if there is already an entry for this grade when updating. If there is it *only* updates the grade and not the grader. It only writes the grader id if there is no entry at all. It should also update the record with the id of the grader.

**Comment by dwinn** [comment]
Hi @thepurpleblob This has been fixed in version 2022032301 today.
