### ISSUE TITLE
Move from cron to new scheduled tasks system

### ISSUE THREAD

**Issue by micaherne** [turnitin/moodle-plagiarism_turnitin#62]
It would be good if this plugin could support the new scheduled tasks system that was introduced in Moodle 2.7 (https://docs.moodle.org/30/en/Scheduled_tasks), which supersedes the legacy cron system.

**Comment by micaherne** [comment]
Sorry, I've just discovered that there is a core Moodle task \core\task\plagiarism_cron_task that calls the cron() method for each plugin so this isn't correct.

**Comment by danmarsden** [comment]
yeah - I've seen the same issue as I've switched the URKUND plugin over to use scheduled tasks too - I see your patch to fix in core, I'll review and get that pushed through later this week! - thanks.

**Comment by sk-unikent** [comment]
I believe it does still use the Event 1 system which does, in turn, use the old queuing system.
(see db/events.php)

**Comment by danmarsden** [comment]
@sk-unikent you might want to report a separate issue for that (if one doesn't already exist) - I've just migrated all the URKUND code from the legacy events structure to the new events 2 api too.
