### ISSUE TITLE
vendor/nategood/httpful not compatible with PHP 7.4

### ISSUE THREAD

**Issue by sharpchi** [turnitin/moodle-plagiarism_turnitin#621]
This component, which I believe you use for testing, uses code that no longer works in PHP 7.4+
This is my output from phpdd
/plagiarism/turnitin/vendor/nategood/httpful/tests/Httpful/HttpfulTest.php:279 | removed | Function each() is removed.  Consider replace with foreach()
/plagiarism/turnitin/vendor/nategood/httpful/tests/Httpful/HttpfulTest.php:282 | removed | Function each() is removed.  Consider replace with foreach() 
/plagiarism/turnitin/vendor/nategood/httpful/tests/Httpful/HttpfulTest.php:285 | removed | Function each() is removed.  Consider replace with foreach()

There is an updated version of httpful which is compatible with PHP 7.4+. This might fix the other errors people are getting when they're running Behat tests on your code.

**Comment by ixiongtii** [comment]
There is an open ticket for this and is under review.

**Comment by ixiongtii** [comment]
There is an open ticket for this and is under review.

**Comment by jack-tii** [comment]
This was fixed by #668
