### ISSUE TITLE
user creation failed error

### ISSUE THREAD

**Issue by registerme1963** [turnitin/moodle-plagiarism_turnitin#631]
Suddenly my students are getting this error during forum posting. However, their replies are posted but not submitted to turnitin.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/45921124/185282510-91f5585b-1ccd-4694-862c-88bd88a7d95c.png)

I never faced this error earlier. 
Server setting:
OS; Ubuntu 20.04
PHP : 7.4.3
Mariadb: 10.3.34-MariaDB-0ubuntu0.20.04.1
Moodle: v4.0.1

Turnitin settings:
All checks are enabled
When should the file be submitted to Turnitin?: Submit files when student sends for marking
Report Generation Speed: Generate reports immediately (students can resubmit until due date): After 3 submissions...after 24 hours

The activity log:
[Aug17_activityLog.txt](https://github.com/turnitin/moodle-plagiarism_turnitin/files/9367298/Aug17_activityLog.txt)

Should I do any changes in the plugin settings?
regards

**Comment by jack-tii** [comment]
Thanks for the report. I am closing this at this time as we don't support Moodle 4.0. If this is still a problem in Moodle 4.1+ please open another issue.
