### ISSUE TITLE
Errors with plugin in Moodle 4.0

### ISSUE THREAD

**Issue by haietza** [turnitin/moodle-plagiarism_turnitin#640]
We're running Moodle 4.0.4+ (Build: 20221007) with version 2022092101 of the plagiarism plugin and are not able to get any results back on either a forum or assignment. Seeing two errors from the forum:

Default exception handler: Coding error detected, it must be fixed by a programmer: The 'pathnamehashes' value must be set in other and must be an array. Debug: 
Error code: codingerror
* line 74 of /lib/classes/event/assessable_uploaded.php: coding_exception thrown
* line 121 of /mod/forum/classes/event/assessable_uploaded.php: call to core\\event\\assessable_uploaded->validate_data()
* line 272 of /lib/classes/event/base.php: call to mod_forum\\event\\assessable_uploaded->validate_data()
* line 140 of /plagiarism/turnitin/classes/turnitin_submission.class.php: call to core\\event\\base::create()
* line 257 of /plagiarism/turnitin/ajax.php: call to turnitin_submission->recreate_submission_event()

PHP Notice:  Trying to get property 'id' of non-object in /var/www/html/plagiarism/turnitin/classes/turnitin_submission.class.php on line 131

Forum posts keep showing the Resubmit to Turnitin button, but clicking does not resolve the issue.

The assignment instance, when running the scheduled cron task to submit queued files, this error was displayed:

This module could not be created on Turnitin, please consult your API logs for further information

This Moodle instance is a development instance hosted on AWS, but it is using our production credentials.

Please advise.

**Comment by jack-tii** [comment]
Closing at this time as Moodle 4.0 is no longer supported. If this is still an issue in newer versions, please open another issue.
