### ISSUE TITLE
Moodle 4.1: Setting link not displaying on plugin overview to configurate

### ISSUE THREAD

**Issue by mglaredo** [turnitin/moodle-plagiarism_turnitin#641]
**Turnitin plagiarism 3.5+ version 2022032301** installed on Moodle 4.1

Navigating into Site Administration > Plugin overview 

We have no "Settings" link to plagiarism/turnitin/settings.php and if we write that URL, fails.

Thanks in advance

**Comment by jack-tii** [comment]
The settings link is visible in our latest release
