### ISSUE TITLE
plagiarism_turnitin_quiz_testcase::test_update_mark does not generate correct identifier hash

### ISSUE THREAD

**Issue by cameron1729** [turnitin/moodle-plagiarism_turnitin#664]
This code:

```
$identifier = sha1($answer);
$tiiquiz->update_mark($attempt->id, $identifier, $user->id, 75, $quiz->grade);
```

Produces a hash which will never be matched by this code (from classes/modules/turnitin_quiz.class.php):

```
// Check if this is the slot the mark is for by matching content.
if (sha1($answer.$slot) == $identifier) {
```

https://github.com/turnitin/moodle-plagiarism_turnitin/pull/648 modified the code for turnitin_quiz.class.php without updating the corresponding test.

**Comment by carl-hostrander** [comment]
this has previously been merged to develop.
