### ISSUE TITLE
Student read marker not changing

### ISSUE THREAD

**Issue by micaherne** [turnitin/moodle-plagiarism_turnitin#68]
I've been testing version 2015040111 and am not able to get the student read status to change. I have:

1. Created an assignment
2. Logged in as a student and submitted to the assignment
3. Run the cron job a few times to get the submission sent to TII and the originality score returned
4. Logged in as the student and viewed the originality report (on closing it I waited until the parent page had been refreshed by Javascript)
5. Refreshed the "view all submissions" page as staff
6. Run the cron job again

When I go into the view all submissions page now I would expect not to see the message "The student has not viewed this paper" but it is stil there.

In the database, the records in plagiarism_turnitin_files for the submission has the value "0".

**Comment by dwinn** [comment]
Hi Micaherne,

I have just tried this myself and I am not seeing any problems. The status changes to read once a submission has been graded and after the student has viewed GradeMark for more than 30 seconds.

**Comment by micaherne** [comment]
Thanks for getting back to me. I didn't realise that the student had to view the page for 30 seconds or more so will retest it.

**Comment by jmcgettrick** [comment]
Hi @micaherne, was this ok?

**Comment by micaherne** [comment]
Hi @jmcgettrick, we tried to make it work by waiting for 30 seconds but didn't see it working. It wasn't a particularly thorough test though, so I'll try it again when I get a chance.
