### ISSUE TITLE
4.3 exception

### ISSUE THREAD

**Issue by aspark21** [turnitin/moodle-plagiarism_turnitin#685]
https://moodledev.io/docs/4.3/devupdate#append-a-suffix-to-the-completion-rules

Site level activity completion defaults page errors out as a result of this

**Comment by haietza** [comment]
Any word on getting the patch implemented in the master branch? We're updating to 4.3 in May and this plugin bug completely breaks course completion.

**Comment by acquaalta** [comment]
Hi @jack-tii,
Does this issue was closed and completed because you fixed the issue in the code?
It still exist in:
Moodle version: 4.3.2
PHP version: 8.2.13
Plugin version:  plagiarism_turnitinsim v1.2 (2023062901)
