### ISSUE TITLE
blank modal dialog box

### ISSUE THREAD

**Issue by grantcolin** [turnitin/moodle-plagiarism_turnitin#695]
moodle version 4.3.2 and php 8.3
When I go to an assignment settings and click on:
"Turnitin Plagiarism Plugin Settings=> Launch Rubric Manager", or
"Turnitin Plagiarism Plugin Settings=> Launch QuickMark Manager", or
"Turnitin Plagiarism Plugin Settings=> Launch Peermark Manager",
then in all of these cases only a blank modal dialog box appears. Not even a title. No other log file errors accompany this behavior.
Could you please look into it?

**Comment by jack-tii** [comment]
This sounds like a problem with LTI. We would need more information to debug, could you open a ticket with support?
