### ISSUE TITLE
Fix for modals doesn't work

### ISSUE THREAD

**Issue by sharpchi** [turnitin/moodle-plagiarism_turnitin#701]
Hi, I'm just testing the fix for the modals (https://github.com/turnitin/moodle-plagiarism_turnitin/commit/8cf0d4f8dbad46a36079c5f4b77ea294a1dcf8cc) for peermark and quickmark launch (I'm testing on Moodle 4.1, but I think there's an issue with newer versions too).

This is the error I'm getting
![image](https://github.com/turnitin/moodle-plagiarism_turnitin/assets/3774280/aae71eb5-72eb-4a04-bbaf-fbf197aec6f8)

Essentially, the files are missing.
From the following lines https://github.com/turnitin/moodle-plagiarism_turnitin/blob/8cf0d4f8dbad46a36079c5f4b77ea294a1dcf8cc/lib.php#L582

I'm pretty sure the calls should match the filenames so:

```
$PAGE->requires->js_call_amd('plagiarism_turnitin/eulaLaunch', 'eulaLaunch');
$PAGE->requires->js_call_amd('plagiarism_turnitin/peermarkLaunch', 'peermarkLaunch');
$PAGE->requires->js_call_amd('plagiarism_turnitin/rubric', 'rubric');
```
should be
```
$PAGE->requires->js_call_amd('plagiarism_turnitin/eula', 'eulaLaunch');
$PAGE->requires->js_call_amd('plagiarism_turnitin/peermark', 'peermarkLaunch');
$PAGE->requires->js_call_amd('plagiarism_turnitin/rubric', 'rubric');
```
or the file names should be changed to match the call

**Comment by sharpchi** [comment]
I'm wondering if you're doing a different build process. Using Moodle's Grunt process, files named peermark.js get compiled with a module name of "plagiarism_turnitin/peermark" and a build filename of peermark.min.js. But your build has a module name of "plagiarism_turnitin/peermarkLaunch". So there's an inconsistency with the naming, somehow.

I got it working in M4.1 with this update: https://github.com/ltu-solent/moodle-plagiarism_turnitin/commit/549af63ae7d664fedbba8eca4f723adde42fabc4 where I renamed the amd calls and rebuilt the amd files affected.

But haven't attempted with any other versions of Moodle, so I won't do a pull request.

**Comment by giorgosmic** [comment]
@sharpchi  We are having the same issue we are getting 404 error for the files.

Do you know when there will be a fix?

**Comment by thepurpleblob** [comment]
Same issue. This is serious guys... Turnitin plugin is unusable on Moodle 4.3 and 4.4.

**Comment by thepurpleblob** [comment]
We think we've found that this is an issue with JS caching disabled on test sites. Not 100% why. Presumably because correct naming conventions have not been followed. So, I still don't feel bad about it :)

**Comment by sharpchi** [comment]
I think they have a fix on their develop branch, but they've not merged it in yet.

**Comment by thepurpleblob** [comment]
@sharpchi I put in a support call about this and the response was, _"After consulting our internal known-issues database and discussing with a senior agent, I did not find any reports indicating potential issues with the Turnitin Plugin and Moodle version 4.4."_

...so that was pretty annoying. We've wasted a load of time on this :(.  And it's far from the first time.

**Comment by carl-hostrander** [comment]
This has been release today.
