### ISSUE TITLE
Turnitin Plagarism Plugin issues

### ISSUE THREAD

**Issue by glennarcher-nz** [turnitin/moodle-plagiarism_turnitin#704]
Execute scheduled task: Send Queued Files from the Turnitin Plagiarism Plugin (plagiarism_turnitin\task\send_submissions)
... started 02:25:01. Current memory use 19.5 MB.
... used 26 dbqueries
... used 604.72780704498 seconds
Scheduled task failed: Send Queued Files from the Turnitin Plagiarism Plugin (plagiarism_turnitin\task\send_submissions),DOMDocument::loadXML(): Argument #1 ($source) must not be empty

Students submissions constantly stay queued and scheduled task constantly fails

Any help/fix appreciated

**Comment by jack-tii** [comment]
We have a fix for this that will go out in our next release, scheduled for October.
