### ISSUE TITLE
plagiarism_plugin::cron() will be deprecated in Moodle 3.1

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-plagiarism_turnitin#71]
Hey John/team - FYI - In Moodle 3.1 (not yet released) plagiarism plugins that call the plagiarism_plugin::cron() function will throw a debugging warning stating that the cron function is now deprecated - plugins should move to using the newer "scheduled tasks" process instead. Eventually the function will be removed from a future Moodle release which may prevent your plugin from working unless you have converted to using scheduled tasks.

More information on this change is available in https://tracker.moodle.org/browse/MDL-52702

Developer documentation on scheduled tasks is available here:
https://docs.moodle.org/dev/Task_API

I've converted the URKUND plugin if you want an example - feel free to copy/borrow/re-use the code as usual:
https://github.com/danmarsden/moodle-plagiarism_urkund/blob/master/db/tasks.php
https://github.com/danmarsden/moodle-plagiarism_urkund/tree/master/classes/task

**Comment by jmcgettrick** [comment]
Released. Thanks Dan.
