### ISSUE TITLE
PHP Deprecated:  Creation of dynamic property plagiarism_turnitinsim_task::$tseula is deprecated

### ISSUE THREAD

**Issue by acquaalta** [turnitin/moodle-plagiarism_turnitin#710]
Hi,

Moodle version: 4.3.2
PHP version: 8.2.13

It seems that every couple of minutes the CRON of the Moodle server sends us the following message:
PHP Deprecated:  Creation of dynamic property plagiarism_turnitinsim_task::$tseula is deprecated in [Our path]/moodle/plagiarism/turnitinsim/classes/task.class.php on line 66

Please fix this issue.

**Comment by acquaalta** [comment]
Later today (the day when we installed the plugin and started to use it), at some point the following message started to be added to the previous one mentioned in my original comment tin this thread:

PHP Deprecated:  Creation of dynamic property plagiarism_turnitinsim_submission::$plagiarism_plugin_turnitinsim is deprecated in /usr/share/moodle/plagiarism/turnitinsim/classes/submission.class.php on line 155

**Comment by steveorulez** [comment]
Hello, any fix for this?

We just installed a test server with moodle 4.3 and we have the same issue.
It's easy to fix this just declare all the proprieties of the class or add #[AllowDynamicProperties]

christian
