### ISSUE TITLE
event_handler() wastefully reads files into memory; causes fatal Out of memory errors

### ISSUE THREAD

**Issue by jrchamp** [turnitin/moodle-plagiarism_turnitin#732]
Here's the relevant code block:
https://github.com/turnitin/moodle-plagiarism_turnitin/blob/eaad4d9e8881598e380934936ff54af670f74ae5/lib.php#L2637-L2666

Here's the main problem:
https://github.com/turnitin/moodle-plagiarism_turnitin/blob/eaad4d9e8881598e380934936ff54af670f74ae5/lib.php#L2649

The contents of a file are read into memory and then completely ignored. Looking at the code block, it's clear that the code is using the logic of "If the file read doesn't throw an exception, then I have a file that I can read from". There's a function that does exactly that: `is_readable()`. Or read just a couple bytes and not hundreds of megabytes.

The code block has a number of other inefficiencies/confusing elemets:
1. `$result = $result && true;` is equivalent to `$result = (bool) $result;`, but it should already be a boolean.
2. `$fs = get_file_storage();` does not depend on the loop data, so this line should be outside of the loop.
3. For some reason, the "avoid fake files" check, `if ($file->get_filename() === '.') {`, happens after the get_content() function call.
4. `$result` defaults to `true` and then it seems like if an error occurs, it is forced to `true` again, which completely ignores any changes that may have been made to `$result` as it is processing other files. And the function docblock doesn't explain what true or false mean as a return value, so I can't even know if it's doing the correct thing. Should I assume that true means an error occurred? Do the queue functions return false when there is an error or when it successfully queues files? Whatever the logic, I was unable to determine the scenario where this logic is correct.

I'd be happy to open a pull request if the return values could be explained.

**Comment by usqfowlerj** [comment]
Here is the solution we've been using for some time now.
```
$fs = get_file_storage();
$file = $fs->get_file_by_hash($pathnamehash);

if (!$file) {
...
} else {
    try {
        // UniSQ BEGIN
        $fh = $file->get_content_file_handle();
        fclose($fh);
        // UniSQ END
    } catch (Exception $e) {
        ...
    }
}
```

**Comment by lucaboesch** [comment]
I made a pull request based on your proposed solution, @usqfowlerj.

**Comment by usqfowlerj** [comment]
Leaving this here in case it proves relevant in the future.
A super-diligent alternative, accounting for the possibility that `get_content_file_handle()` may fail to open the file, could be as shown below (untested), however I seem to recall there was no exception that would be thrown by `$file->get_content()` in the case it failed to open a handle, so the behaviour was the same either way with my original alternative.
```php
if (($fh = $file->get_content_file_handle()) === false) {
    throw new \file_exception('storedfilecannotread');
}
fclose($fh);
```
