### ISSUE TITLE
Eula Agreement showing Blank wont Let Student Accept

### ISSUE THREAD

**Issue by DownesAyr** [turnitin/moodle-plagiarism_turnitin#739]
Hello,

Having an issue with all new students who are receiving the EULA agreement. They click the link to accept but the pop up appears blank. I am using Moodle 4.4.2 and plagiarism plugin version 2024072401.

![turnitin_plagiarism_plugin_eula_blank_error](https://github.com/user-attachments/assets/372b44c9-fd8c-4900-a949-40dd217027a4)

With debugging on I also noticed an error line: public_html/plagiarism/turnitin/vendor/Integrations/phpsdk-package/src/Soap.php on line 369

**Comment by jack-tii** [comment]
I don't think this is an issue with the plugin, it could be an issue with your setup that is blocking the LTI request from coming through. Could you open a ticket with support?
