### ISSUE TITLE
Integrate error reporting into Tii PP error tab

### ISSUE THREAD

**Issue by mkpelletier** [turnitin/moodle-plagiarism_turnitin#76]
Hello John,

Let me start by saying that the quality of the Turnitin Moodle integrations have improved by leaps and bounds since you came on board.  Excellent work!  You have also been a great help with any error reported either through github or the Moodle forums.

With respect to errors, though you have been helpful, the tech support at Turnitin have been anything but.  I get canned responses from tech staff who neglect to read the email, even though I already provided the required detail.  I have pretty much given up on using Tii tech support for this reason.

In looking for a solution, is there a chance we could included a "baked in" error reporting mechanism?  That is on the errors tab in Turnitin PP, perhaps we could include an option to report a given assignment submission error to Turnitin from the errors page, I suggest this would include the following (with all the obvious end user approval confirmations):

1.The URL to your institution's LMS*
2. Turnitin Account ID (a numeric value). 
3. LMS Version and Plug-in version. 
4. Class Name or ID (where the error occurs).
5. Assignment Name or ID (where the error occurs).
6. Time of Error.
7. OS, Browser and versions.
8. An additional text area where the admin may report additional helpful detail.

You will notice most of the above is verbatim from the support emails we get back from Tii tech support.  At the moment, I get regular submission failures that seem to have little reason for failing.  Perhaps 1 out of 50 assignments fail to process in Tii and need to be resubmitted.  Some have a paper id, others do not, but they usually have an error in the errors tab.  In these cases, I usually convert the paper to a PDF and resubmit.  At other times, I may resubmit without conversion and it works fine.  If the above were available, I and others like me may be more inclined to report the error.

See these two screenshots for example:

![mysats__administration__plugins__plagiarism__turnitin_plagiarism_plugin](https://cloud.githubusercontent.com/assets/4638072/12702352/36ce1502-c82f-11e5-9848-66656dfa17e4.jpg)
![tii_pp_error log](https://cloud.githubusercontent.com/assets/4638072/12702353/36fa15d0-c82f-11e5-9685-241f969f2135.jpg)

Thanks again for all the hard work, John.

All the best,
Mathieu

**Comment by jmcgettrick** [comment]
Hi @mkpelletier and thanks!
We are currently working on functionality to allow instructors to create support tickets from within the plugin. This sounds like it might sit alongside this quite well so we'll do some investigating as to how this will fit in.

**Comment by mkpelletier** [comment]
Brilliant!  We are looking forward to it.  I am sure it will also be able to produce error reports that are much more useful to Tii and save everyone loads of time.
