### ISSUE TITLE
Invalid ajax URL on edit submissions page

### ISSUE THREAD

**Issue by micaherne** [turnitin/moodle-plagiarism_turnitin#763]
The turnitin plugin is causing a failed request on the page where students can edit their assignments submission (/mod/assign/view.php?id=12345&action=editsubmission)

![image](https://github.com/user-attachments/assets/d80ee3b8-737a-43d6-8b4f-43c041049d51)

This seems to be caused by the function refreshRubricSelect() constructing a relative URL which isn't valid in this context

![image](https://github.com/user-attachments/assets/816e8d42-b58f-4e81-9d1d-18f5852fdf46)

**Comment by jack-tii** [comment]
Should be resolved by #761
