### ISSUE TITLE
Unneccessary word count check crashing cron

### ISSUE THREAD

**Issue by micaherne** [turnitin/moodle-plagiarism_turnitin#85]
We recently updated to version 2015040111 and are starting to get out of memory errors when running the Moodle cron job (this issue exists in the latest version of the plugin too).

> Fatal error: Allowed memory size of 1048576000 bytes exhausted (tried to allocate 532 bytes) in /moodle/web/plagiarism/turnitin/lib.php on line 2398

The scenario is an engineering assignment which is set up to accept any file, and the students are uploading a couple of very large simulation files (400Mb+) along with a Word document project report, so the assignment is set to accept any file type but is only expecting plagiarism checking on the Word document.

The fatal error is being thrown when the plugin tries to count the words in one of the simulation files, so there are a few issues:

1. The file is a binary file, so trying to count the words is meaningless (it's an archive created by ANSYS)
2. The algorithm for counting the words is really inefficient - it's exploding the file content on the space character, so taking up at least the same amount of memory again. It could just use str_word_count().
3. The file is over the 40Mb limit so wouldn't be sent to Turnitin anyway, but the check for file size takes place after the word count.

It looks like this was caused by https://github.com/turnitin/moodle-plagiarism_turnitin/commit/490c1104c7986575fae0c9e0f4b40379b4f7f90a, as previously the plugin wouldn't try to count words for file submissions.

**Comment by dhattonturnitin** [comment]
Fixed in release v2016011105

**Comment by sk-unikent** [comment]
Where has this been fixed? I don't see it!

**Comment by jmcgettrick** [comment]
Sorry, my mistake. Wrong ticket, re-opening.

**Comment by jmcgettrick** [comment]
Word count has been removed from the  plugin as of 2016072601
