### ISSUE TITLE
v2016011103 Pending event queues

### ISSUE THREAD

**Issue by Syxton** [turnitin/moodle-plagiarism_turnitin#94]
We just updated our dev system to the latest release.  Currently, none of the event queues are being processed successfully.  They all show as Pending.  The cron runs, but the event queue for each submission is failing.

**Comment by dwinn** [comment]
Hi @Syxton 

I have just tested the plugin again on my local environment and submissions are going through to Turnitin fine. Which version did you upgrade from?

It may be that you do not have the PHP extension fileinfo installed (or enabled). That can cause submissions to get stuck in pending if it is not enabled/installed and became a plugin requirement a few versions back.

You can check for that in PHP Info (Site Admin > Server > PHP Info) and look for a section on fileinfo like in the image below:

![Image of fileinfo](http://i.imgur.com/STQnLjG.png)

If you don't see this then it will need to be enabled/installed. Check http://php.net/manual/en/fileinfo.installation.php for more information on that.

**Comment by Syxton** [comment]
From 2016011102 -> 2016011103
Fileinfo is enabled and save versions as shown.

Turnitin debug mode is on, so I can get more info if needed.

**Comment by jmcgettrick** [comment]
Hi @Syxton - can you let us know the cron output with debugging on please?

**Comment by Syxton** [comment]
I created a new assignment, had a single test user submit a single file.  I cleared out all other PP submissions.

Processing cron function for plagiarism_plugin_turnitin...... started 08:43:04. Current memory use 11.6MB.
Exception in TII cron while updating scores for 'file' submission types: exception 'dml_read_exception' with message 'Error reading from database' in /var/www/moodle/lib/dml/moodle_database.php:443
Stack trace:
#0 /var/www/moodle/lib/dml/mysqli_native_moodle_database.php(1080): moodle_database->query_end(false)
#1 /var/www/moodle/lib/dml/moodle_database.php(1307): mysqli_native_moodle_database->get_records_sql('SELECT * FROM {...', Array, 0, 0)
#2 /var/www/moodle/plagiarism/turnitin/lib.php(1740): moodle_database->get_records_select('plagiarism_turn...', ' statuscode = ?...', Array, 'externalid DESC')
#3 /var/www/moodle/lib/plagiarismlib.php(179): plagiarism_plugin_turnitin->cron()
#4 /var/www/moodle/lib/classes/task/plagiarism_cron_task.php(48): plagiarism_cron()
#5 /var/www/moodle/lib/cronlib.php(74): core\task\plagiarism_cron_task->execute()
#6 /var/www/moodle/admin/cron.php(81): cron_run()
#7 {main}
Exception in TII cron while updating scores for 'text_content' submission types: exception 'dml_read_exception' with message 'Error reading from database' in /var/www/moodle/lib/dml/moodle_database.php:443
Stack trace:
#0 /var/www/moodle/lib/dml/mysqli_native_moodle_database.php(1080): moodle_database->query_end(false)
#1 /var/www/moodle/lib/dml/moodle_database.php(1307): mysqli_native_moodle_database->get_records_sql('SELECT * FROM {...', Array, 0, 0)
#2 /var/www/moodle/plagiarism/turnitin/lib.php(1740): moodle_database->get_records_select('plagiarism_turn...', ' statuscode = ?...', Array, 'externalid DESC')
#3 /var/www/moodle/lib/plagiarismlib.php(179): plagiarism_plugin_turnitin->cron()
#4 /var/www/moodle/lib/classes/task/plagiarism_cron_task.php(48): plagiarism_cron()
#5 /var/www/moodle/lib/cronlib.php(74): core\task\plagiarism_cron_task->execute()
#6 /var/www/moodle/admin/cron.php(81): cron_run()
#7 {main}
Exception in TII cron while updating scores for 'forum_post' submission types: exception 'dml_read_exception' with message 'Error reading from database' in /var/www/moodle/lib/dml/moodle_database.php:443
Stack trace:
#0 /var/www/moodle/lib/dml/mysqli_native_moodle_database.php(1080): moodle_database->query_end(false)
#1 /var/www/moodle/lib/dml/moodle_database.php(1307): mysqli_native_moodle_database->get_records_sql('SELECT * FROM {...', Array, 0, 0)
#2 /var/www/moodle/plagiarism/turnitin/lib.php(1740): moodle_database->get_records_select('plagiarism_turn...', ' statuscode = ?...', Array, 'externalid DESC')
#3 /var/www/moodle/lib/plagiarismlib.php(179): plagiarism_plugin_turnitin->cron()
#4 /var/www/moodle/lib/classes/task/plagiarism_cron_task.php(48): plagiarism_cron()
#5 /var/www/moodle/lib/cronlib.php(74): core\task\plagiarism_cron_task->execute()
#6 /var/www/moodle/admin/cron.php(81): cron_run()
#7 {main}
... used 3 dbqueries
... used 0.00553297996521 seconds
Scheduled task complete: Background processing for plagiarism plugin

**Comment by Syxton** [comment]
There is also this:

Number of events in the Plagiarism Plugin events queue: 2
... used 54 dbqueries
... used 3.8756330013275 seconds
Scheduled task complete: Background processing for events

**Comment by Syxton** [comment]
before and after cron runs I have 0 rows of data in mdl_plagiarism_turnitin_files and 3 rows of data in mdl_events_queue

**Comment by jmcgettrick** [comment]
I think your problem is that the upgrade to 2016011103 missed the adding of a db field, see: https://github.com/turnitin/moodle-plagiarism_turnitin/commit/a07e2ff1e41b95f24cec0c575c7080f06090fe0c#diff-c74097fbb0a2db56a0a98aaf7d6a2654L186

That should now be fixed with 2016011104.

**Comment by Syxton** [comment]
Ok, so I uninstalled the pp, mod, and block.  Reinstalled with the versions that were just released a few minutes ago.  I created a single assignment.  Then I had a student account submit a single file.  

First note.  When I clicked "Create an activity or resource->Assignment" I got a debug error.  I created a new issue #98 for that.  The next time I tried it seemed to work fine.

After the submission, I ran cron.  Got the following:

Number of events in the Plagiarism Plugin events queue: 2
This module could not be created on Turnitin, please consult your API logs for further information
This module could not be created on Turnitin, please consult your API logs for further information
-------------------------
This file has not been submitted to Turnitin because there is a problem creating the module in Turnitin which is preventing submissions, please consult your API logs for further information:
User:  6294 - Test User 1 (testuser1@local.host)
Course Module: 349460
-------------------------
This module could not be created on Turnitin, please consult your API logs for further information
... used 100 dbqueries
... used 6.412141084671 seconds
Scheduled task complete: Background processing for events

**Comment by Syxton** [comment]
the file submission queues are gone, but the activity creation row in the event queue is still there.

**Comment by jmcgettrick** [comment]
Can youforward me your API logs? There should be a createLineItem call that's showing an error.

**Comment by Syxton** [comment]
[apilog.txt](https://github.com/turnitin/moodle-plagiarism_turnitin/files/142804/apilog.txt)
I just did a search and found 0 instances of the string "createLineItem"

**Comment by jmcgettrick** [comment]
Sorry, I edited my message, the correct string is createByProxyLineItem. I'm seeing the error "submit_papers_to - invalid value" in there about 20 times.

**Comment by Syxton** [comment]
I forced the setting "Standard Repository" and now the assignment was created.  Thanks for your help.  I agree the problem started with the upgrade missing a db field.  Everything looks good now.
