### ISSUE TITLE
v2016011103 Coding error

### ISSUE THREAD

**Issue by mkpelletier** [turnitin/moodle-plagiarism_turnitin#95]
Hello All,

With the latest update Plagiarism_plugin is returning a 500 error when trying to access the submissions or do anything with an assignment on which turnitin is configured.  php_errors.log has the following:

PHP Parse error:  syntax error, unexpected '=', expecting ')' in /storage/www/moodle/plagiarism/turnitin/lib.php on line 2387

I see that this was changed from the previous version and now adds a conditional to test for an empty value.  Is there something I am missing here?  The plagiarism plugin is now broken with new if statement.

**Comment by mkpelletier** [comment]
I commented out the conditional:
//if (empty($textcontent = $file->get_content())) {
                    //    $errorcode = 9;
                    //}

and added this from 201611102 just above the conditional: 
$textcontent = $file->get_content();  

This is just a stop-gap, since there are errors being generated by empty records.  Can anyone advise what the problem is with the code as released?  What am I missing?

**Comment by mkpelletier** [comment]
Surely this update was tested.  I am getting more errors in my php_errors.log: 

Default exception handler: Field "duedate_report_refresh" does not exist in table "plagiarism_turnitin_files" Debug: 
Error code: ddlfieldnotexist
* line 592 of /lib/dml/moodle_database.php: dml_exception thrown
* line 1699 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
* line 1610 of /plagiarism/turnitin/lib.php: call to moodle_database->set_field()
* line 422 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin->sync_tii_assignment()
* line 159 of /lib/plagiarismlib.php: call to plagiarism_plugin_turnitin->print_disclosure()
* line 3422 of /mod/assign/locallib.php: call to plagiarism_print_disclosure()
* line 3524 of /mod/assign/locallib.php: call to assign->plagiarism_print_disclosure()
* line 535 of /mod/assign/locallib.php: call to assign->view_edit_submission_page()
* line 53 of /mod/assign/view.php: call to assign->view()

**Comment by mkpelletier** [comment]
Default exception handler: Field "duedate_report_refresh" does not exist in table "plagiarism_turnitin_files" Debug: 
Error code: ddlfieldnotexist
* line 592 of /lib/dml/moodle_database.php: dml_exception thrown
* line 1699 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
* line 1610 of /plagiarism/turnitin/lib.php: call to moodle_database->set_field()
* line 853 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin->sync_tii_assignment()
* line 51 of /lib/plagiarismlib.php: call to plagiarism_plugin_turnitin->get_links()
* line 1185 of /mod/assign/renderer.php: call to plagiarism_get_links()
* line 61 of /mod/assign/renderer.php: call to mod_assign_renderer->htmllize_tree()
* line 316 of /lib/outputrenderers.php: call to mod_assign_renderer->render_assign_files()
* line 48 of /mod/assign/renderer.php: call to plugin_renderer_base->render()
* line 4623 of /mod/assign/locallib.php: call to mod_assign_renderer->assign_files()
* line 327 of /mod/assign/submission/file/locallib.php: call to assign->render_area_files()
* line 927 of /mod/assign/renderer.php: call to assign_submission_file->view_summary()
* line 316 of /lib/outputrenderers.php: call to mod_assign_renderer->render_assign_submission_plugin_submission()
* line 697 of /mod/assign/renderer.php: call to plugin_renderer_base->render()
* line 316 of /lib/outputrenderers.php: call to mod_assign_renderer->render_assign_submission_status()
* line 3991 of /mod/assign/locallib.php: call to plugin_renderer_base->render()
* line 4308 of /mod/assign/locallib.php: call to assign->view_student_summary()
* line 559 of /mod/assign/locallib.php: call to assign->view_submission_page()
* line 53 of /mod/assign/view.php: call to assign->view()

**Comment by jmcgettrick** [comment]
Hi @mkpelletier we'll get those both fixed and put a patch out this morning.

**Comment by mkpelletier** [comment]
Thanks John!

**Comment by jmcgettrick** [comment]
Hi @mkpelletier the first error seems to only occur with PHP versions < 5.5.

We'll replace the line with:

$textcontent = $file->get_content();
if (empty($textcontent)) {

**Comment by mkpelletier** [comment]
That seems to take care of the first problem, John.  Thanks.  Can I just add the duedate_refresh_report column as tinyint to my mdl_plagiarism_turnitin_files?

**Comment by mkpelletier** [comment]
Unfortunately, with the second error throwing db exceptions, grademark will not load nor can students submit assignments.  Did the update script fail to create the extra column?

**Comment by dhattonturnitin** [comment]
Hi @mkpelletier 
The issue is caused by a version number conflict. If you create the duedate_refresh_report column as tinyint as suggested above, then this should resolve the issue.

**Comment by jmcgettrick** [comment]
Hi @mkpelletier - we're just testing the qa04 branch to fix these issues. It should be out early this afternoon.

**Comment by mkpelletier** [comment]
Thanks, John.  I went ahead and created the column.  It is working now.

**Comment by dwinn** [comment]
Hi @mkpelletier We have now released version 2016011104 which solves these issues.
