### ISSUE TITLE
Debug Mode shows an issue sometimes when creating a new assignment

### ISSUE THREAD

**Issue by Syxton** [turnitin/moodle-plagiarism_turnitin#98]
Debug info: 
Error code: Turnitin user creation failed<br/><br/>Fault Code: invaliddata | File: [dirroot]/mod/turnitintooltwo/sdk/usersoap.class.php | Line: 39 | Message: email - This field is required 
| Code: 0
$a contents: Turnitin user creation failed<br/><br/>Fault Code: invaliddata | File: [dirroot]/mod/turnitintooltwo/sdk/usersoap.class.php | Line: 39 | Message: email - This field is required 
| Code: 0

**Comment by jmcgettrick** [comment]
As with the other issue, could you forward me your API logs. There should be a createUser request that is failing because one of the user's it's trying to create doesn't have an email address.

**Comment by jmcgettrick** [comment]
The plugin is trying to create a user that doesn't have an email address. I can see this happening with Moodle User 2915.

**Comment by Syxton** [comment]
I have a test user that has an email address of testuser1@local.host (a dummy email address).  Would this cause the problem?

**Comment by jmcgettrick** [comment]
No that one is fine, I've just tested it. The createByProxyPerson requests that are failing in the logs you provided don't have an email address provided.

**Comment by Syxton** [comment]
As a test I just created a brand new Moodle course, enrolled myself and 1 student in the course.  Both have real email addresses.  Went to create an assignment and got the error.  Attached is the api log.
[apilog.txt](https://github.com/turnitin/moodle-plagiarism_turnitin/files/144639/apilog.txt)

**Comment by jmcgettrick** [comment]
This looks a little strange. There's a discoverPersonIds call which queries the API with an email address and then have an id returned to it. That request in those logs has no email address in it, the createByProxyPerson request for a user called "Moodle User 2915" should have a EmailWorkPrimary field but it doesn't have one either. 

I'm assuming that's the same user for both requests, is that the user you created or are they somewhere else in your system?

**Comment by Syxton** [comment]
What does the number 2915 correlate to?  It isn't a Moodle id on our system.  There isn't a user with that name or id in our system.

**Comment by jmcgettrick** [comment]
It's a user on your system (user id: 2915) that doesn't have a name, see: https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/master/turnitintooltwo_user.class.php#L95-L98.

**Comment by Syxton** [comment]
Does this try to create every Moodle user, or is it only users enrolled in the course?  There is no user with the id of 2915, either in the mdl_users table or the mdl_turnitintooltwo_users table.

**Comment by jmcgettrick** [comment]
If the course is being created in Turnitin for the first time, the plugin will try to create and enrol every user that is a Moodle site admin or teacher on the course.
The 2915 should be a user in mdl_users as it's only called from within the constructor in the turnitintooltwo_user class. What are $this and $user after this line https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/master/turnitintooltwo_user.class.php#L82 ?

**Comment by Syxton** [comment]
[Error_Redacted.pdf](https://github.com/turnitin/moodle-plagiarism_turnitin/files/148562/Error_Redacted.pdf)

There are 2 users in my course.  A teacher and a student.  Neither of those users show up when I place debug outputs however.  Only the main moodle admin user shows up.  I have posted out puts of $user and $this and the line numbers where the outputs are placed.  The number 2915 never shows up.

**Comment by Syxton** [comment]
Looks like the 2nd userid sent to get_moodle_user() is id 2915.  That id doesn't exist in the mdl_user table.  The code should skip user id's that don't correspond with a moodle userid.

**Comment by jmcgettrick** [comment]
It must be getting the id 2915 from within the create_tii_course() method. Stack trace is below:

line 1416 of /plagiarism/turnitin/lib.php: call to turnitintooltwo_user­>__construct()
line 508 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin­>create_tii_course()
line 221 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin­>get_course_data()

At that point the plugin will try to enrol all site admins and instructors from the class on to the class in Turnitin. It must be getting the id 2915 from $CFG->siteadmins or the $tutors = get_users_by_capability() call, it could be a user that's inherited their role from site level?

**Comment by Syxton** [comment]
no matter where it get's the id, we should check to see if mdl_user was able to retrieve data on that user id before continuing.  Because that ID doesn't exist anymore.  Maybe it use to, but there isn't a user with that id anywhere in our database.

**Comment by jmcgettrick** [comment]
This is a particular edge case as the plugin is asking Moodle for users who have certain permissions. If Moodle is responding with a user that doesn't exist in the database then I suspect this may be a bug in Moodle and should be raised in the Moodle tracker.
