### ISSUE TITLE
Locked repository setting causes failed uploads.

### ISSUE THREAD

**Issue by Syxton** [turnitin/moodle-plagiarism_turnitin#99]
I have our Default repository setting locked at "Standard Repository".  The test submission fails with a "This file has not been submitted to Turnitin, please consult your system administrator" error.  When I unlock the default, still leaving it set to "Standard Repository".  When I go back to the failing assignment, the repository is set to "No Repository".

**Comment by Syxton** [comment]
On another note, I set the Paper Repository Assignments: to "Submit all papers to standard repository", now I don't have the option of selecting a default setting for repositories.  When I submit an assignment in a PP assignment, I get an error of [[ppsubmissionerrorstudent]] which doesn't even have a Moodle lang string.

**Comment by Syxton** [comment]
In an interesting turn, without changing any settings, I resubmitted the failed upload and it worked on re-submission.

**Comment by jmcgettrick** [comment]
I've added that string into the develop branch so it'll be out on next release. Is the repository saving correctly now? Does it just occur when you change the plugin configuration to give assignment creators the choice?
